// @vitest-environment node
import { spawnSync } from 'node:child_process'
import {
  copyFileSync,
  existsSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { afterAll, describe, expect, it } from 'vitest'

/**
 * The three commands this ticket adds, run the way a person and CI run them. Exit codes are
 * the contract here: `npm run build` chains them with `&&`, so a command that printed an
 * error and exited zero would publish broken content while the log said it had failed.
 */

const root = fileURLToPath(new URL('../../', import.meta.url))
const fixturePgn = 'tools/content/fixtures/pgn/damiano-two-branches.pgn'

const run = (script: string, ...args: string[]) =>
  spawnSync(process.execPath, [`tools/content/${script}`, ...args], { cwd: root, encoding: 'utf8' })

const temporary: string[] = []
const scratch = (): string => {
  const directory = mkdtempSync(join(tmpdir(), 'content-pipeline-'))
  temporary.push(directory)
  return directory
}

afterAll(() => {
  for (const directory of temporary) spawnSync('rm', ['-rf', directory])
})

describe('import-pgn (AC 1)', () => {
  it('writes a YAML skeleton and reports what it found', () => {
    const out = join(scratch(), 'imported.yaml')
    const result = run(
      'import-cli.ts',
      fixturePgn,
      '--side',
      'white',
      '--soundness',
      'sound',
      '--category',
      'trap',
      '--out',
      out,
    )

    expect(result.status).toBe(0)
    expect(result.stdout).toContain('defining line   e4 e5 Nf3 f6 Nxe5 fxe5 Qh5+')
    expect(result.stdout).toContain('branch points   1')
    expect(readFileSync(out, 'utf8')).toContain('ply: Ke7')
  })

  it('says the skeleton already passes the gate when it does', () => {
    const out = join(scratch(), 'imported.yaml')
    const result = run(
      'import-cli.ts',
      fixturePgn,
      '--side',
      'white',
      '--soundness',
      'sound',
      '--out',
      out,
    )

    expect(result.stdout).toContain('passes the content gate')
  })

  it('lists what the gate still demands when the PGN left replies unanswered', () => {
    const directory = scratch()
    const pgn = join(directory, 'partial.pgn')
    writeFileSync(
      pgn,
      '[ECO "C40"]\n[Annotator "t"]\n\n1. e4 e5 2. Nf3 f6 3. Nxe5 fxe5 (3... Qe7) *\n',
    )
    const result = run(
      'import-cli.ts',
      pgn,
      '--side',
      'white',
      '--soundness',
      'sound',
      '--out',
      join(directory, 'p.yaml'),
    )

    expect(result.status).toBe(0)
    expect(result.stdout).toContain('[reply-incomplete]')
    expect(result.stdout).toContain('does not invent them')
  })

  it('refuses without a side, because side decides every derived kind', () => {
    const result = run('import-cli.ts', fixturePgn, '--soundness', 'sound')

    expect(result.status).toBe(1)
    expect(result.stderr).toContain('`--side` is required')
  })

  it('refuses without a soundness label, rather than choosing one', () => {
    const result = run('import-cli.ts', fixturePgn, '--side', 'white')

    expect(result.status).toBe(1)
    expect(result.stderr).toContain('`--soundness` is required')
  })

  /** After the first import the YAML is the source of truth; a second one would erase it. */
  it('refuses to overwrite an entry that already exists', () => {
    const out = join(scratch(), 'imported.yaml')
    const args = [fixturePgn, '--side', 'white', '--soundness', 'sound', '--out', out]

    expect(run('import-cli.ts', ...args).status).toBe(0)
    const second = run('import-cli.ts', ...args)

    expect(second.status).toBe(1)
    expect(second.stderr).toContain('will not be overwritten')
  })
})

describe('export-pgn (AC 2)', () => {
  it('prints a PGN for a published entry', () => {
    const result = run('export-cli.ts', 'damiano-defence-refutation')

    expect(result.status).toBe(0)
    expect(result.stdout).toContain('[ECO "C40"]')
    expect(result.stdout).toContain('1. e4')
  })

  it('names the ids it does know when asked for one it does not', () => {
    const result = run('export-cli.ts', 'no-such-gambit')

    expect(result.status).toBe(1)
    expect(result.stderr).toContain(
      'Known ids: accelerated-london-system-steinitz-countergambit, accelerated-london-system-steinitz-countergambit-accepted, accelerated-london-system-steinitz-countergambit-morris-2, alekhine-defense-four-pawns-attack-cambridge-gambit, alekhine-defense-hunt-variation-lasker-simul-gambit, alekhine-defense-hunt-variation-matsukevich-gambit, alekhine-defense-hunt-variation-mikenas-gambit, alekhine-defense-krejcik-variation-krejcik-gambit, alekhine-defense-osullivan-gambit, alekhine-defense-scandinavian-variation-geschev-gambit, alekhine-defense-scandinavian-variation-myers-gambit, alekhine-defense-spielmann-gambit, amar-opening-paris-gambit-gent-gambit, barnes-opening-gedult-gambit, benko-gambit, benko-gambit-accepted, benko-gambit-accepted-central-storming-variation, benko-gambit-accepted-dlugy-variation, benko-gambit-accepted-fianchetto-variation, benko-gambit-accepted-fully-accepted-variation, benko-gambit-accepted-modern-variation, benko-gambit-accepted-pawn-return-variation, benko-gambit-accepted-yugoslav, benko-gambit-declined-bishop-attack, benko-gambit-declined-hjorring-countergambit, benko-gambit-declined-main-line, benko-gambit-declined-pseudo-samisch, benko-gambit-declined-quiet-line, benko-gambit-declined-sosonko-variation, benko-gambit-fianchetto-variation, benko-gambit-mutkin-countergambit, benko-gambit-nd2-variation, benko-gambit-nescafe-frappe-attack, benko-gambit-zaitsev-system, benko-gambit-zaitsev-variation-nescafe-frappe-attack, benoni-defense-benoni-gambit-accepted, benoni-defense-benoni-gambit-schlenker-defense, benoni-defense-cormorant-gambit, benoni-defense-zilbermints-benoni-gambit, bird-opening-dutch-variation-batavo-gambit, bird-opening-dutch-variation-dudweiler-gambit, bird-opening-froms-gambit, bird-opening-froms-gambit-bahr-gambit, bird-opening-froms-gambit-lipke-variation, bird-opening-hobbs-gambit, bird-opening-hobbs-zilbermints-gambit, bird-opening-lasker-gambit, bird-opening-platz-gambit, bird-opening-schlechter-gambit, bird-opening-sturm-gambit, bird-opening-wagner-zwitersch-gambit, bird-opening-williams-gambit, bishops-gambit-classical-defense-cozio-attack, bishops-opening-anderssen-gambit, bishops-opening-berlin-defense-greco-gambit, bishops-opening-boden-kieseritzky-gambit, bishops-opening-boden-kieseritzky-gambit-lichtenhein-defense, bishops-opening-calabrese-countergambit, bishops-opening-calabrese-countergambit-jaenisch-variation, bishops-opening-four-pawns-gambit, bishops-opening-horwitz-gambit, bishops-opening-khan-gambit, bishops-opening-krejcik-gambit, bishops-opening-lewis-countergambit, bishops-opening-lewis-countergambit-walker-variation, bishops-opening-lewis-gambit, bishops-opening-lopez-gambit, bishops-opening-lopez-variation-lopez-gambit, bishops-opening-mcdonnell-gambit, bishops-opening-mcdonnell-gambit-la-bourdonnais-denker-gambit, bishops-opening-mcdonnell-gambit-mcdonnell-double-gambit, bishops-opening-pachman-gambit, bishops-opening-ponziani-gambit, bishops-opening-stein-gambit, bishops-opening-thorold-gambit, bishops-opening-urusov-gambit, bishops-opening-urusov-gambit-keidansky-gambit, bishops-opening-urusov-gambit-panov-variation, bishops-opening-warsaw-gambit, blackmar-diemer-gambit, blackmar-diemer-gambit-accepted, blackmar-diemer-gambit-accepted-bogoljubow-defense, blackmar-diemer-gambit-accepted-bogoljubow-defense-kloss-attack, blackmar-diemer-gambit-accepted-euwe-defense, blackmar-diemer-gambit-accepted-euwe-defense-duthilleul-gambit, blackmar-diemer-gambit-accepted-euwe-defense-zilbermints-gambit, blackmar-diemer-gambit-accepted-gunderam-defense, blackmar-diemer-gambit-accepted-holwell-defense, blackmar-diemer-gambit-accepted-kaulich-defense, blackmar-diemer-gambit-accepted-pietrowsky-defense, blackmar-diemer-gambit-accepted-ritter-defense, blackmar-diemer-gambit-accepted-ryder-gambit, blackmar-diemer-gambit-accepted-schlutter-defense, blackmar-diemer-gambit-accepted-teichmann-defense, blackmar-diemer-gambit-accepted-ziegler-defense, blackmar-diemer-gambit-blackmar-gambit, blackmar-diemer-gambit-declined-brombacher-countergambit, blackmar-diemer-gambit-declined-elbert-countergambit, blackmar-diemer-gambit-declined-gedult-defense, blackmar-diemer-gambit-declined-lamb-defense, blackmar-diemer-gambit-declined-langeheinicke-defense, blackmar-diemer-gambit-declined-okelly-defense, blackmar-diemer-gambit-declined-vienna-defense, blackmar-diemer-gambit-declined-weinsbach-defense, blackmar-diemer-gambit-declined-weinsbach-defense-pfrang-gambit, blackmar-diemer-gambit-diemer-rosenberg-attack, blackmar-diemer-gambit-fritz-attack, blackmar-diemer-gambit-lemberger-countergambit, blackmar-diemer-gambit-lemberger-countergambit-endgame-variation, blackmar-diemer-gambit-lemberger-countergambit-lange-gambit, blackmar-diemer-gambit-lemberger-countergambit-rasmussen-attack, blackmar-diemer-gambit-lemberger-countergambit-sneiders-attack, blackmar-diemer-gambit-lemberger-countergambit-soller-attack, blackmar-diemer-gambit-netherlands-variation, blackmar-diemer-gambit-rasa-studier-gambit, blackmar-diemer-gambit-reversed-albin-countergambit, blackmar-diemer-gambit-von-popiel-gambit, blackmar-diemer-gambit-von-popiel-gambit-zilbermints-variation, blackmar-diemer-gambit-zeller-defense, blackmar-diemer-gambit-zeller-defense-soller-attack, blumenfeld-countergambit, blumenfeld-countergambit-accepted, blumenfeld-countergambit-duz-khotimirsky-variation, bogoljubow-defense-mad-dog-attack, bogoljubow-defense-nimzowitsch-attack, bogoljubow-defense-studier-attack, borg-defense-borg-gambit, borg-defense-troon-gambit, borg-defense-zilbermints-gambit, budapest-gambit-accepted-fajarowicz-defense-bonsdorf-variation, budapest-gambit-accepted-fajarowicz-defense-steiner-variation, budapest-gambit-accepted-main-line-adler-variation, budapest-gambit-accepted-main-line-alekhine-variation, budapest-gambit-accepted-main-line-rubinstein-variation, caro-kann-defense-alekhine-gambit, caro-kann-defense-labahn-attack-double-gambit, caro-kann-defense-mieses-gambit, caro-kann-defense-von-hennig-gambit, carr-defense-zilbermints-gambit, catalan-opening-hungarian-gambit, center-game-halasz-mcdonnell-gambit, center-game-halasz-mcdonnell-gambit-crocodile-variation, center-game-lanc-arnold-gambit, center-game-lanc-arnold-gambit-schippler-gambit, center-game-ross-gambit, center-game-von-der-lasa-gambit, classical-variation-greco-gambit-anderssen-variation, classical-variation-greco-gambit-moeller-bayonet-attack, classical-variation-greco-gambit-moeller-therkatz-attack, classical-variation-rubinstein-countergambit, damiano-defence-refutation, danish-gambit, danish-gambit-accepted, danish-gambit-accepted-chigorin-defense, danish-gambit-accepted-classical-defense, danish-gambit-accepted-copenhagen-defense, danish-gambit-accepted-schlechter-defense, danish-gambit-accepted-svenonius-defense, danish-gambit-declined-sorensen-defense, delayed-alapin-variation-basman-palatnik-double-gambit, dragon-variation-classical-variation-zollner-gambit, duras-gambit, dutch-defense-bellon-gambit, dutch-defense-blackmars-second-gambit, dutch-defense-janzen-korchnoi-gambit, dutch-defense-kingfisher-gambit, dutch-defense-krejcik-gambit, dutch-defense-krejcik-gambit-tate-gambit, dutch-defense-manhattan-gambit-anti-classical-line, dutch-defense-manhattan-gambit-anti-leningrad, dutch-defense-manhattan-gambit-anti-modern, dutch-defense-manhattan-gambit-anti-stonewall, dutch-defense-omega-isis-gambit, dutch-defense-senechaud-gambit, dutch-defense-spielmann-gambit, dutch-defense-staunton-gambit, dutch-defense-staunton-gambit-accepted, dutch-defense-staunton-gambit-alekhine-variation, dutch-defense-staunton-gambit-american-attack, dutch-defense-staunton-gambit-chigorin-variation, dutch-defense-staunton-gambit-lasker-variation, dutch-defense-staunton-gambit-nimzowitsch-variation, dutch-defense-staunton-gambit-tartakower-variation, elephant-gambit, elephant-gambit-maroczy-gambit, elephant-gambit-paulsen-countergambit, elephant-gambit-wasp-variation, elephant-trap, english-defense-eastbourne-gambit, english-opening-achilles-omega-gambit, english-opening-anglo-dutch-defense-hickmann-gambit, english-opening-anglo-scandinavian-defense-lohn-gambit, english-opening-anglo-scandinavian-defense-schulz-gambit, english-opening-jaenisch-gambit, english-opening-myers-gambit, english-opening-wade-gambit, english-opening-wing-gambit, english-opening-zilbermints-gambit, englund-gambit, englund-gambit-declined, englund-gambit-declined-diemer-counterattack, englund-gambit-declined-reversed-alekhine, englund-gambit-declined-reversed-brooklyn, englund-gambit-declined-reversed-french, englund-gambit-declined-reversed-krebs, englund-gambit-declined-reversed-mokele-mbembe, englund-gambit-felbecker-gambit, englund-gambit-hartlaub-charlick-gambit, englund-gambit-main-line, englund-gambit-mosquito-gambit, englund-gambit-soller-gambit, englund-gambit-soller-gambit-deferred, englund-gambit-stockholm-variation, englund-gambit-trap, englund-gambit-zilbermints-gambit, falkbeer-countergambit-charousek-gambit-accepted, falkbeer-countergambit-charousek-gambit-keres-variation, falkbeer-countergambit-charousek-gambit-main-line, falkbeer-countergambit-charousek-gambit-morphy-defense, falkbeer-countergambit-charousek-gambit-old-line, falkbeer-countergambit-milner-barry-variation, falkbeer-countergambit-nimzowitsch-marshall-countergambit, falkbeer-countergambit-rubinstein-variation, fishing-pole-trap, four-knights-game-halloween-gambit, four-knights-game-halloween-gambit-oldtimer-variation, four-knights-game-halloween-gambit-plasma-variation, four-knights-game-italian-variation-noa-gambit, four-knights-game-scotch-variation-belgrade-gambit, four-knights-game-scotch-variation-krause-gambit, french-defense-advance-variation-milner-barry-gambit, french-defense-alapin-gambit, french-defense-alekhine-chatard-attack-albin-chatard-gambit, french-defense-baeuerle-gambit, french-defense-banzai-leong-gambit, french-defense-carlson-gambit, french-defense-diemer-duhm-gambit, french-defense-diemer-duhm-gambit-accepted, french-defense-fort-knox-queen-trap, french-defense-la-bourdonnais-variation-reuter-gambit, french-defense-marshall-gambit, french-defense-morphy-gambit, french-defense-winawer-variation-alekhine-gambit-accepted, french-defense-winawer-variation-alekhine-gambit-kan-variation, french-defense-wing-gambit, grob-opening-alessi-gambit, grob-opening-double-grob-coca-cola-gambit, grob-opening-grob-gambit, grob-opening-grob-gambit-basman-gambit, grob-opening-grob-gambit-declined, grob-opening-grob-gambit-fritz-gambit, grob-opening-grob-gambit-fritz-gambit-romford-countergambit, grob-opening-grob-gambit-richter-grob-gambit, grob-opening-romford-countergambit, grob-opening-zilbermints-gambit-schiller-defense, grunfeld-defense-brinckmann-attack-grunfeld-gambit-accepted, grunfeld-defense-gibbon-gambit, gunderam-defense-stader-variation, halosar-trap, hamppe-allgaier-gambit-alapin-variation, hamppe-allgaier-gambit-thorold-variation, horwitz-defense-zilbermints-gambit, hungarian-opening-asten-gambit, hungarian-opening-bucker-gambit, hungarian-opening-pachman-gambit, hungarian-opening-van-kuijk-gambit, hungarian-opening-wiedenhagen-beta-gambit, hungarian-opening-winterberg-gambit, indian-defense-anti-grunfeld-adorjan-gambit, indian-defense-budapest-gambit, indian-defense-budapest-gambit-accepted, indian-defense-budapest-gambit-accepted-fajarowicz-defense, indian-defense-gibbins-weidenhagen-gambit, indian-defense-gibbins-weidenhagen-gambit-accepted, indian-defense-gibbins-weidenhagen-gambit-oshima-defense, indian-defense-lazard-gambit, indian-defense-maddigan-gambit, indian-defense-omega-gambit, indian-defense-pyrenees-gambit, irish-gambit, italian-game-belloni-trap, italian-game-blackburne-kostic-gambit, italian-game-classical-variation-albin-gambit, italian-game-classical-variation-greco-gambit-dubov-italian, italian-game-classical-variation-greco-gambit-greco-variation, italian-game-classical-variation-greco-gambit-main-line, italian-game-classical-variation-greco-gambit-modern-line, italian-game-classical-variation-greco-gambit-traditional-line, italian-game-deutz-gambit, italian-game-evans-gambit, italian-game-evans-gambit-accepted, italian-game-evans-gambit-alapin-steinitz-variation, italian-game-evans-gambit-anderssen-defense, italian-game-evans-gambit-anderssen-variation, italian-game-evans-gambit-anderssen-variation-cordel-line, italian-game-evans-gambit-bronstein-defense, italian-game-evans-gambit-compromised-defense, italian-game-evans-gambit-compromised-defense-main-line, italian-game-evans-gambit-compromised-defense-potter-variation, italian-game-evans-gambit-declined, italian-game-evans-gambit-declined-cordel-variation, italian-game-evans-gambit-declined-hicken-variation, italian-game-evans-gambit-declined-hirschbach-variation, italian-game-evans-gambit-declined-lange-variation, italian-game-evans-gambit-declined-pavlov-variation, italian-game-evans-gambit-declined-showalter-variation, italian-game-evans-gambit-declined-vasquez-variation, italian-game-evans-gambit-dufresne-defense, italian-game-evans-gambit-fontaine-countergambit, italian-game-evans-gambit-fraser-attack, italian-game-evans-gambit-fraser-mortimer-attack, italian-game-evans-gambit-goring-attack, italian-game-evans-gambit-harding-variation, italian-game-evans-gambit-hein-countergambit, italian-game-evans-gambit-johner-defense, italian-game-evans-gambit-laroche-variation, italian-game-evans-gambit-lasker-defense, italian-game-evans-gambit-leonhardt-countergambit, italian-game-evans-gambit-levenfish-variation, italian-game-evans-gambit-main-line, italian-game-evans-gambit-mayet-defense, italian-game-evans-gambit-mcdonnell-defense, italian-game-evans-gambit-mcdonnell-defense-main-line, italian-game-evans-gambit-mieses-defense, italian-game-evans-gambit-morphy-attack, italian-game-evans-gambit-mortimer-evans-gambit, italian-game-evans-gambit-paulsen-variation, italian-game-evans-gambit-pierce-defense, italian-game-evans-gambit-richardson-attack, italian-game-evans-gambit-sanders-alapin-variation, italian-game-evans-gambit-slow-variation, italian-game-evans-gambit-sokolsky-variation, italian-game-evans-gambit-steinitz-variation, italian-game-evans-gambit-stone-ware-variation, italian-game-evans-gambit-tartakower-attack, italian-game-evans-gambit-ulvestad-variation, italian-game-evans-gambit-waller-attack, italian-game-giuoco-pianissimo-lucchini-gambit, italian-game-jerome-gambit, italian-game-rosentreter-gambit, italian-game-rousseau-gambit, italian-game-scotch-gambit, italian-game-scotch-gambit-anderssen-attack, italian-game-scotch-gambit-anderssen-attack-main-line, italian-game-scotch-gambit-canal-variation, italian-game-scotch-gambit-de-riviere-defense, italian-game-scotch-gambit-double-gambit-accepted, italian-game-scotch-gambit-janowski-defense, italian-game-scotch-gambit-max-lange-attack, italian-game-scotch-gambit-max-lange-attack-accepted, italian-game-scotch-gambit-max-lange-attack-long-variation, italian-game-scotch-gambit-max-lange-attack-spielmann-defense, italian-game-scotch-gambit-nakhmanson-gambit, italian-game-scotch-gambit-walbrodt-baird-gambit, italian-game-two-knights-defense-fried-liver-attack, italian-game-two-knights-defense-kloss-gambit, italian-game-two-knights-defense-ponziani-steinitz-gambit, italian-game-two-knights-defense-traxler-counterattack, italian-game-two-knights-defense-ulvestad-variation, kadas-opening-kadas-gambit, kadas-opening-schneider-gambit, kadas-opening-steinbok-gambit, kieninger-trap, kieseritzky-gambit-berlin-defense-de-riviere-variation, kieseritzky-gambit-berlin-defense-rubinstein-variation, kieseritzky-gambit-brentano-defense-caro-variation, kieseritzky-gambit-paulsen-defense-deferred, kieseritzky-long-whip-defense-jaenisch-variation, kings-gambit, kings-gambit-accepted, kings-gambit-accepted-abbazia-defense, kings-gambit-accepted-abbazia-defense-main-line, kings-gambit-accepted-allgaier-blackburne-gambit, kings-gambit-accepted-allgaier-cook-variation, kings-gambit-accepted-allgaier-gambit, kings-gambit-accepted-allgaier-gambit-thorold-attack, kings-gambit-accepted-allgaier-gambit-urusov-attack, kings-gambit-accepted-allgaier-horny-defense, kings-gambit-accepted-allgaier-schlechter-defense, kings-gambit-accepted-allgaier-urusov-attack, kings-gambit-accepted-australian-gambit, kings-gambit-accepted-basman-gambit, kings-gambit-accepted-becker-defense, kings-gambit-accepted-bishops-gambit, kings-gambit-accepted-bishops-gambit-anderssen-defense, kings-gambit-accepted-bishops-gambit-anderssen-variation, kings-gambit-accepted-bishops-gambit-bledow-countergambit, kings-gambit-accepted-bishops-gambit-bledow-variation, kings-gambit-accepted-bishops-gambit-boden-variation, kings-gambit-accepted-bishops-gambit-bogoljubow-defense, kings-gambit-accepted-bishops-gambit-bogoljubow-variation, kings-gambit-accepted-bishops-gambit-boren-svenonius-variation, kings-gambit-accepted-bishops-gambit-bryan-countergambit, kings-gambit-accepted-bishops-gambit-chigorins-attack, kings-gambit-accepted-bishops-gambit-classical-defense, kings-gambit-accepted-bishops-gambit-cozio-defense, kings-gambit-accepted-bishops-gambit-cozio-variation, kings-gambit-accepted-bishops-gambit-first-jaenisch-variation, kings-gambit-accepted-bishops-gambit-fraser-variation, kings-gambit-accepted-bishops-gambit-gianutio-gambit, kings-gambit-accepted-bishops-gambit-greco-variation, kings-gambit-accepted-bishops-gambit-grimm-attack, kings-gambit-accepted-bishops-gambit-kieseritzky-gambit, kings-gambit-accepted-bishops-gambit-lopez-defense, kings-gambit-accepted-bishops-gambit-lopez-variation, kings-gambit-accepted-bishops-gambit-maurian-defense, kings-gambit-accepted-bishops-gambit-mcdonnell-attack, kings-gambit-accepted-bishops-gambit-paulsen-attack, kings-gambit-accepted-bishops-gambit-steinitz-defense, kings-gambit-accepted-blachly-gambit, kings-gambit-accepted-bonsch-osmolovsky-variation, kings-gambit-accepted-breyer-gambit, kings-gambit-accepted-carrera-gambit, kings-gambit-accepted-cunningham-defense, kings-gambit-accepted-cunningham-defense-bertin-gambit, kings-gambit-accepted-cunningham-defense-mccormick-defense, kings-gambit-accepted-dodo-variation, kings-gambit-accepted-double-muzio-gambit, kings-gambit-accepted-double-muzio-gambit-baldwin-gambit, kings-gambit-accepted-double-muzio-gambit-bello-gambit, kings-gambit-accepted-double-muzio-gambit-paulsen-defense, kings-gambit-accepted-double-muzio-gambit-young-gambit, kings-gambit-accepted-eisenberg-variation, kings-gambit-accepted-fischer-defense, kings-gambit-accepted-fischer-defense-schulder-gambit, kings-gambit-accepted-fischer-defense-spanish-variation, kings-gambit-accepted-gaga-gambit, kings-gambit-accepted-ghulam-kassim-gambit, kings-gambit-accepted-gianutio-countergambit, kings-gambit-accepted-greco-gambit, kings-gambit-accepted-hanstein-gambit, kings-gambit-accepted-kieseritzky-gambit, kings-gambit-accepted-kieseritzky-gambit-anderssen-cordel-gambit, kings-gambit-accepted-kieseritzky-gambit-anderssen-defense, kings-gambit-accepted-kieseritzky-gambit-berlin-defense, kings-gambit-accepted-kieseritzky-gambit-brentano-defense, kings-gambit-accepted-kieseritzky-gambit-cotter-gambit, kings-gambit-accepted-kieseritzky-gambit-kolisch-defense, kings-gambit-accepted-kieseritzky-gambit-long-whip, kings-gambit-accepted-kieseritzky-gambit-neumann-defense, kings-gambit-accepted-kieseritzky-gambit-paulsen-defense, kings-gambit-accepted-kieseritzky-gambit-rice-gambit, kings-gambit-accepted-kieseritzky-gambit-rosenthal-defense, kings-gambit-accepted-kieseritzky-polerio-defense, kings-gambit-accepted-kieseritzky-rice-gambit, kings-gambit-accepted-kieseritzky-salvio-defense-cozio-variation, kings-gambit-accepted-kings-knights-gambit, kings-gambit-accepted-kotov-gambit, kings-gambit-accepted-lolli-gambit, kings-gambit-accepted-lolli-gambit-young-variation, kings-gambit-accepted-macleod-defense, kings-gambit-accepted-mason-keres-gambit, kings-gambit-accepted-mayet-gambit, kings-gambit-accepted-mcdonnell-gambit, kings-gambit-accepted-middleton-countergambit, kings-gambit-accepted-modern-defense, kings-gambit-accepted-muzio-gambit-accepted-froms-defense, kings-gambit-accepted-muzio-gambit-brentano-defense, kings-gambit-accepted-muzio-gambit-holloway-defense, kings-gambit-accepted-muzio-gambit-sarratt-defense, kings-gambit-accepted-muzio-gambit-wild-muzio-gambit, kings-gambit-accepted-orsini-gambit, kings-gambit-accepted-paris-gambit, kings-gambit-accepted-philidor-gambit, kings-gambit-accepted-philidor-gambit-schultz-variation, kings-gambit-accepted-quaade-gambit, kings-gambit-accepted-rosentreter-gambit, kings-gambit-accepted-rosentreter-gambit-bird-gambit, kings-gambit-accepted-rosentreter-gambit-sorensen-gambit, kings-gambit-accepted-rosentreter-gambit-testa-variation, kings-gambit-accepted-salvio-gambit, kings-gambit-accepted-salvio-gambit-anderssen-counterattack, kings-gambit-accepted-salvio-gambit-cochrane-gambit, kings-gambit-accepted-salvio-gambit-santa-maria-defense, kings-gambit-accepted-salvio-gambit-silberschmidt-defense, kings-gambit-accepted-salvio-gambit-viennese-variation, kings-gambit-accepted-schallopp-defense, kings-gambit-accepted-schallopp-defense-tashkent-attack, kings-gambit-accepted-schurig-gambit-with-bb5, kings-gambit-accepted-schurig-gambit-with-bd3, kings-gambit-accepted-silberschmidt-gambit, kings-gambit-accepted-sorensen-gambit, kings-gambit-accepted-stamma-gambit, kings-gambit-accepted-tartakower-gambit, kings-gambit-accepted-tartakower-gambit-weiss-defense, kings-gambit-accepted-traditional-variation, kings-gambit-accepted-tumbleweed, kings-gambit-accepted-villemson-gambit, kings-gambit-accepted-wagenbach-defense, kings-gambit-declined-classical-hanham-variation, kings-gambit-declined-classical-reti-variation, kings-gambit-declined-classical-soldatenkov-variation, kings-gambit-declined-classical-svenonius-variation, kings-gambit-declined-classical-variation, kings-gambit-declined-classical-variation-euwe-attack, kings-gambit-declined-classical-variation-rotlewi-countergambit, kings-gambit-declined-classical-variation-walthoffen-attack, kings-gambit-declined-falkbeer-countergambit, kings-gambit-declined-falkbeer-countergambit-accepted, kings-gambit-declined-falkbeer-countergambit-alapin-variation, kings-gambit-declined-falkbeer-countergambit-anderssen-attack, kings-gambit-declined-falkbeer-countergambit-blackburne-attack, kings-gambit-declined-falkbeer-countergambit-charousek-gambit, kings-gambit-declined-falkbeer-countergambit-charousek-variation, kings-gambit-declined-falkbeer-countergambit-hinrichsen-gambit, kings-gambit-declined-falkbeer-countergambit-miles-gambit, kings-gambit-declined-falkbeer-countergambit-modern-transfer, kings-gambit-declined-falkbeer-countergambit-pickler-gambit, kings-gambit-declined-falkbeer-countergambit-staunton-line, kings-gambit-declined-falkbeer-countergambit-tarrasch-variation, kings-gambit-declined-hobbs-zilbermints-gambit, kings-gambit-declined-keene-defense, kings-gambit-declined-keenes-defense, kings-gambit-declined-mafia-defense, kings-gambit-declined-miles-defense, kings-gambit-declined-norwalde-variation, kings-gambit-declined-norwalde-variation-bucker-gambit, kings-gambit-declined-norwalde-variation-schubert-variation, kings-gambit-declined-panteldakis-countergambit, kings-gambit-declined-panteldakis-countergambit-greco-variation, kings-gambit-declined-panteldakis-countergambit-shirazi-line, kings-gambit-declined-petrovs-defense, kings-gambit-declined-queens-knight-defense, kings-gambit-declined-senechaud-countergambit, kings-gambit-declined-soller-zilbermints-gambit, kings-gambit-declined-zilbermints-double-countergambit, kings-gambit-declined-zilbermints-double-gambit, kings-indian-attack-omega-delta-gambit, kings-indian-defense-samisch-variation-samisch-gambit, kings-indian-defense-samisch-variation-samisch-gambit-accepted, kings-pawn-game-bavarian-gambit, kings-pawn-game-beyer-gambit, kings-pawn-game-busch-gass-gambit, kings-pawn-game-busch-gass-gambit-chiodini-gambit, kings-pawn-game-clam-variation-kings-gambit-reversed, kings-pawn-game-gunderam-defense-gunderam-gambit, kings-pawn-game-gunderam-gambit, kings-pawn-game-macleod-attack-norwalde-gambit, kings-pawn-game-pachman-wing-gambit, kings-pawn-game-philidor-gambit, kings-pawn-game-schulze-muller-gambit, kings-pawn-game-tayler-opening-basman-gambit, kings-pawn-game-wayward-queen-attack-kiddie-countergambit, kings-pawn-game-weber-gambit, kings-pawn-opening-van-hooydoon-gambit, lasker-pelikan-variation-sveshnikov-variation-peresypkins, lasker-trap, latvian-gambit, latvian-gambit-accepted, latvian-gambit-accepted-bilguer-variation, latvian-gambit-accepted-bronstein-attack, latvian-gambit-accepted-bronstein-gambit, latvian-gambit-accepted-foltys-leonhardt-variation, latvian-gambit-accepted-foltys-variation, latvian-gambit-accepted-leonhardt-variation, latvian-gambit-accepted-main-line, latvian-gambit-accepted-nimzowitsch-attack, latvian-gambit-behting-variation, latvian-gambit-clam-gambit, latvian-gambit-corkscrew-countergambit, latvian-gambit-corkscrew-gambit, latvian-gambit-diepstraten-countergambit, latvian-gambit-lobster-gambit, latvian-gambit-mason-countergambit, latvian-gambit-mayet-attack, latvian-gambit-mlotkowski-variation, legals-mate, lion-defense-anti-philidor-lions-cave-lion-claw-gambit, lopez-gianutio-countergambit-hein-variation, magnus-smith-trap, mexican-defense-horsefly-gambit, mikenas-defense-pozarek-gambit, milner-barry-trap, modern-defense-lizard-defense-pirc-diemer-gambit, modern-defense-masur-gambit, modern-defense-westermann-gambit, modern-defense-wind-gambit, monticelli-trap, morphy-defense-schliemann-defense-deferred-jaenisch-gambit, mortimer-trap, muzio-gambit-kling-and-horwitz-counterattack, nimzo-indian-defense-classical-variation-belyavsky-gambit, nimzo-indian-defense-dilworth-gambit, nimzo-larsen-attack-norfolk-gambit, nimzo-larsen-attack-pachman-gambit, nimzo-larsen-attack-ringelbach-gambit, nimzowitsch-defense-colorado-countergambit, nimzowitsch-defense-colorado-countergambit-accepted, nimzowitsch-defense-hornung-gambit, nimzowitsch-defense-kennedy-variation-bielefelder-gambit, nimzowitsch-defense-kennedy-variation-de-smet-gambit, nimzowitsch-defense-kennedy-variation-hammer-gambit, nimzowitsch-defense-kennedy-variation-herford-gambit, nimzowitsch-defense-wheeler-gambit, noahs-ark-trap, nyezhmetdinov-rossolimo-attack-fianchetto-variation-gufeld, nyezhmetdinov-rossolimo-attack-fianchetto-variation-lutikov, nyezhmetdinov-rossolimo-attack-san-francisco-gambit, old-indian-defense-aged-gibbon-gambit, owen-defense-naselwaus-gambit, owen-defense-smith-gambit, owen-defense-wind-gambit, panov-attack-fianchetto-defense-fianchetto-gambit, panteldakis-countergambit-pawn-sacrifice-line, panteldakis-countergambit-schillers-defense, panteldakis-countergambit-symmetrical-variation, petrovs-defense-cochrane-gambit, petrovs-defense-marshall-trap, petrovs-defense-moody-gambit, petrovs-defense-stafford-gambit, petrovs-defense-stafford-gambit-accepted, philidor-defense-bird-gambit, philidor-defense-lopez-countergambit, philidor-defense-morphy-gambit, philidor-defense-philidor-countergambit, philidor-defense-philidor-countergambit-berger-variation, philidor-defense-philidor-countergambit-del-rio-attack, philidor-defense-philidor-countergambit-zukertort-variation, philidor-defense-philidor-gambit, pirc-defense-roscher-gambit, polish-defense-spassky-gambit-accepted, polish-opening-birmingham-gambit, polish-opening-tartakower-gambit, ponziani-opening-ponziani-countergambit, ponziani-opening-ponziani-countergambit-schmidt-attack, ponziani-opening-vukovic-gambit, portuguese-gambit-melbourne-shuffle-variation, portuguese-opening-miguel-gambit, portuguese-opening-portuguese-gambit, queens-gambit-accepted-old-variation-b5-trap, queens-gambit-declined-albin-countergambit, queens-gambit-declined-albin-countergambit-fianchetto-variation, queens-gambit-declined-albin-countergambit-modern-line, queens-gambit-declined-albin-countergambit-normal-line, queens-gambit-declined-albin-countergambit-spassky-variation, queens-gambit-declined-albin-countergambit-tartakower-defense, queens-indian-defense-classical-variation-polugaevsky-gambit, queens-pawn-game-chigorin-variation-irish-gambit, queens-pawn-game-hubsch-gambit, queens-pawn-game-zurich-gambit, rat-defense-english-rat-lisbon-gambit, reti-opening-zilbermints-gambit, richter-veresov-attack-malich-gambit, rubinstein-trap, ruy-lopez-alapin-defense-alapin-gambit, ruy-lopez-berlin-defense-rio-gambit-accepted, ruy-lopez-central-countergambit, ruy-lopez-classical-variation-cordel-gambit, ruy-lopez-classical-variation-konikowski-gambit, ruy-lopez-classical-variation-spanish-wing-gambit, ruy-lopez-classical-variation-zukertort-gambit, ruy-lopez-closed-alekhine-gambit, ruy-lopez-closed-basque-gambit, ruy-lopez-closed-center-attack-basque-gambit, ruy-lopez-closed-chigorin-defense-gajewski-gambit, ruy-lopez-exchange-variation-alapin-gambit, ruy-lopez-halloween-attack, ruy-lopez-marshall-attack, ruy-lopez-marshall-attack-main-line, ruy-lopez-marshall-attack-main-line-spassky-variation, ruy-lopez-marshall-attack-modern-main-line, ruy-lopez-marshall-attack-modern-variation, ruy-lopez-marshall-attack-original-marshall-attack, ruy-lopez-marshall-attack-re3-variation, ruy-lopez-marshall-attack-steiner-variation, ruy-lopez-morphy-defense-jaffe-gambit, ruy-lopez-morphy-defense-norwegian-variation-nightingale-gambit, ruy-lopez-morphy-defense-schliemann-defense-deferred, ruy-lopez-open-harksen-gambit, ruy-lopez-open-karpov-gambit, ruy-lopez-open-skipworth-gambit, ruy-lopez-schliemann-defense, ruy-lopez-schliemann-defense-classical-variation, ruy-lopez-schliemann-defense-dyckhoff-variation, ruy-lopez-schliemann-defense-exchange-variation, ruy-lopez-schliemann-defense-jaenisch-gambit-accepted, ruy-lopez-schliemann-defense-kostic-defense, ruy-lopez-schliemann-defense-mohring-variation, ruy-lopez-schliemann-defense-schonemann-attack, ruy-lopez-schliemann-defense-tartakower-variation, ruy-lopez-spanish-countergambit, ruy-lopez-spanish-countergambit-harding-gambit, ruy-lopez-steinitz-defense-center-gambit, scandinavian-defense-blackburne-gambit, scandinavian-defense-blackburne-kloosterboer-gambit, scandinavian-defense-boehnke-gambit, scandinavian-defense-icelandic-palme-gambit, scandinavian-defense-kadas-gambit, scandinavian-defense-kiel-variation-trap, scandinavian-defense-main-line-leonhardt-gambit, scandinavian-defense-portuguese-gambit, scandinavian-defense-portuguese-gambit-banker-variation, scandinavian-defense-portuguese-gambit-jadoul-variation, scandinavian-defense-zilbermints-gambit, scandinavian-variation-bogoljubow-variation-richter-gambit, scheveningen-variation-delayed-keres-attack-perenyi-gambit, scholars-mate, scotch-game-alekhine-gambit, scotch-game-goring-gambit, scotch-game-goring-gambit-bardeleben-variation, scotch-game-goring-gambit-double-pawn-sacrifice, scotch-game-goring-gambit-main-line, scotch-game-haxo-gambit, scotch-game-napoleon-gambit, scotch-game-relfsson-gambit, scotch-game-scotch-gambit, scotch-game-scotch-gambit-advance-variation, scotch-game-scotch-gambit-cochrane-anderssen-variation, scotch-game-scotch-gambit-dubois-reti-defense, scotch-game-scotch-gambit-goring-gambit-declined, scotch-game-scotch-gambit-kingside-variation, scotch-game-scotch-gambit-london-defense, scotch-game-scotch-gambit-sarratt-variation, scotch-variation-belgrade-gambit-modern-defense, scotch-variation-krause-gambit-leonhardt-defense, semi-slav-defense-anti-moscow-gambit, semi-slav-defense-gunderam-gambit, semi-slav-defense-marshall-gambit, semi-slav-defense-marshall-gambit-main-line, semi-slav-defense-marshall-gambit-tolush-variation, semi-slav-defense-noteboom-variation-anti-noteboom-gambit, siberian-trap, sicilian-defense-alapin-variation-anti-alapin-gambit, sicilian-defense-brussels-gambit, sicilian-defense-coles-sicilian-gambit, sicilian-defense-delayed-alapin-variation-basman-palatnik-gambit, sicilian-defense-double-dutch-gambit, sicilian-defense-euwe-attack-prins-gambit, sicilian-defense-halasz-gambit, sicilian-defense-kotov-gambit, sicilian-defense-kronberger-variation-nemeth-gambit, sicilian-defense-mcdonnell-attack-tal-gambit, sicilian-defense-modern-variations-ginsberg-gambit, sicilian-defense-morphy-gambit, sicilian-defense-morphy-gambit-andreaschek-gambit, sicilian-defense-moscow-variation-haag-gambit, sicilian-defense-moscow-variation-moscow-gambit, sicilian-defense-najdorf-variation-dekker-gambit, sicilian-defense-okelly-variation-normal-system-cortlever-gambit, sicilian-defense-okelly-variation-venice-system-gambit-line, sicilian-defense-okelly-variation-wing-gambit, sicilian-defense-polish-gambit, sicilian-defense-portsmouth-gambit, sicilian-defense-smith-morra-gambit, sicilian-defense-smith-morra-gambit-accepted, sicilian-defense-smith-morra-gambit-accepted-chicago-defense, sicilian-defense-smith-morra-gambit-accepted-classical-formation, sicilian-defense-smith-morra-gambit-accepted-danish-variation, sicilian-defense-smith-morra-gambit-accepted-fianchetto-defense, sicilian-defense-smith-morra-gambit-accepted-finegold-defense, sicilian-defense-smith-morra-gambit-accepted-kan-formation, sicilian-defense-smith-morra-gambit-accepted-larsen-defense, sicilian-defense-smith-morra-gambit-accepted-morphy-defense, sicilian-defense-smith-morra-gambit-accepted-paulsen-formation, sicilian-defense-smith-morra-gambit-accepted-pin-defense, sicilian-defense-smith-morra-gambit-accepted-siberian-variation, sicilian-defense-smith-morra-gambit-accepted-sozin-formation, sicilian-defense-smith-morra-gambit-accepted-taimanov-formation, sicilian-defense-smith-morra-gambit-declined-alapin-formation, sicilian-defense-smith-morra-gambit-declined-center-formation, sicilian-defense-smith-morra-gambit-declined-dubois-variation, sicilian-defense-smith-morra-gambit-declined-push-variation, sicilian-defense-smith-morra-gambit-declined-wing-formation, sicilian-defense-smith-morra-gambit-deferred, sicilian-defense-taimanov-variation-gary-gambit, sicilian-defense-wing-gambit, sicilian-defense-wing-gambit-abrahams-variation, sicilian-defense-wing-gambit-carlsbad-variation, sicilian-defense-wing-gambit-deferred, sicilian-defense-wing-gambit-deferred-variation, sicilian-defense-wing-gambit-marienbad-variation, sicilian-defense-wing-gambit-marshall-variation, sicilian-defense-wing-gambit-nanu-gambit, sicilian-defense-wing-gambit-romanian-defense, sicilian-defense-wing-gambit-santasiere-variation, slav-defense-diemer-gambit, slav-defense-geller-gambit, slav-defense-slav-gambit-alekhine-attack, slav-defense-winawer-countergambit, slav-defense-winawer-countergambit-anti-winawer-gambit, smith-morra-gambit-accepted-morphy-defense-deferred, smith-morra-gambit-accepted-open-d-file-trap, smith-morra-gambit-accepted-scheveningen-formation, smith-morra-gambit-declined-scandinavian-formation, sodium-attack-durkin-gambit, spanish-countergambit-harding-countergambit-fricke-gambit, st-george-defense-zilbermints-gambit, stafford-gambit-rosen-trap, steinitz-gambit-fraser-minckwitz-defense, steinitz-gambit-paulsen-defense, steinitz-gambit-sorensen-defense, steinitz-gambit-zukertort-defense, taimanov-variation-bastrikov-variation-ponomariov-gambit, tarrasch-defense-classical-variation-classical-tarrasch-gambit, tarrasch-defense-grunfeld-gambit, tarrasch-defense-schara-gambit, tarrasch-defense-tarrasch-gambit, tarrasch-defense-von-hennig-gambit, tarrasch-trap, tarrasch-variation-open-system-shaposhnikov-gambit, teichmann-defense-ciesielski-variation, teichmann-defense-classical-variation, teichmann-defense-seidel-hall-attack, torre-attack-classical-defense-petrosian-gambit, torre-attack-wagner-gambit, traxler-counterattack-ke2-trap, trompowsky-attack-edge-variation-hergert-gambit, trompowsky-attack-raptor-variation-hergert-gambit, two-knights-defense-traxler-counterattack-bishop-sacrifice-line, two-knights-defense-traxler-counterattack-king-march-line, two-knights-defense-traxler-counterattack-knight-sacrifice-line, two-knights-defense-traxler-variation-trencianske-teplice-gambit, two-knights-defense-ulvestad-variation-kurkin-gambit, two-knights-variation-suttles-variation-tal-gambit, van-geet-opening-berlin-gambit, van-geet-opening-dougherty-gambit, van-geet-opening-hector-gambit, van-geet-opening-laroche-gambit, van-geet-opening-sleipnir-gambit, vant-kruijs-opening-keoni-hiva-gambit-akahi-variation, vant-kruijs-opening-keoni-hiva-gambit-alua-variation, vienna-gambit-with-max-lange-defense, vienna-gambit-with-max-lange-defense-cunningham-defense, vienna-gambit-with-max-lange-defense-hamppe-allgaier-gambit, vienna-gambit-with-max-lange-defense-hamppe-muzio-gambit, vienna-gambit-with-max-lange-defense-knight-variation, vienna-gambit-with-max-lange-defense-pierce-gambit, vienna-gambit-with-max-lange-defense-quelle-gambit, vienna-gambit-with-max-lange-defense-steinitz-gambit, vienna-gambit-with-max-lange-defense-steinitz-gambit-main-line, vienna-game-adams-gambit, vienna-game-frankenstein-dracula-qd5-trap, vienna-game-frankenstein-dracula-variation, vienna-game-fyfe-gambit, vienna-game-hamppe-muzio-gambit, vienna-game-mieses-variation-erben-gambit, vienna-game-omaha-gambit, vienna-game-paulsen-variation-mariotti-gambit, vienna-game-paulsen-variation-pollock-gambit, vienna-game-philidor-countergambit, vienna-game-pierce-gambit-rushmere-attack, vienna-game-stanley-variation-bronstein-gambit, vienna-game-stanley-variation-eifel-gambit, vienna-game-stanley-variation-meitner-mieses-gambit, vienna-game-vienna-gambit, vienna-game-vienna-gambit-bardeleben-variation, vienna-game-vienna-gambit-breyer-variation, vienna-game-vienna-gambit-kaufmann-variation, vienna-game-vienna-gambit-main-line, vienna-game-vienna-gambit-modern-variation, vienna-game-vienna-gambit-paulsen-attack, vienna-game-vienna-gambit-steinitz-variation, vienna-game-wurzburger-trap, vienna-game-zhuravlev-countergambit, ware-opening-ware-gambit, ware-opening-wing-gambit, winawer-variation-alekhine-gambit-alatortsev-variation, zukertort-opening-herrstrom-gambit, zukertort-opening-lemberger-gambit, zukertort-opening-lisitsyn-gambit, zukertort-opening-ross-gambit, zukertort-opening-shabalov-gambit, zukertort-opening-tennison-gambit, zukertort-opening-tennison-gambit-briggs-trap, zukertort-opening-vos-gambit.',
    )
  })

  /** The export is generated; a `.pgn` committed beside its `.yaml` is a second source of truth. */
  it('refuses to write into the content directory', () => {
    const result = run('export-cli.ts', 'damiano-defence-refutation', '--out', 'content/x.pgn')

    expect(result.status).toBe(1)
    expect(result.stderr).toContain('second source of truth')
    expect(existsSync(join(root, 'content/x.pgn'))).toBe(false)
  })
})

describe('compile (AC 3)', () => {
  it('writes one minified JSON file per entry', () => {
    const out = scratch()
    const result = run('compile-cli.ts', '--out', out)

    expect(result.status).toBe(0)
    expect([...readdirSync(out)].sort()).toStrictEqual([
      'accelerated-london-system-steinitz-countergambit-accepted.json',
      'accelerated-london-system-steinitz-countergambit-morris-2.json',
      'accelerated-london-system-steinitz-countergambit.json',
      'alekhine-defense-four-pawns-attack-cambridge-gambit.json',
      'alekhine-defense-hunt-variation-lasker-simul-gambit.json',
      'alekhine-defense-hunt-variation-matsukevich-gambit.json',
      'alekhine-defense-hunt-variation-mikenas-gambit.json',
      'alekhine-defense-krejcik-variation-krejcik-gambit.json',
      'alekhine-defense-osullivan-gambit.json',
      'alekhine-defense-scandinavian-variation-geschev-gambit.json',
      'alekhine-defense-scandinavian-variation-myers-gambit.json',
      'alekhine-defense-spielmann-gambit.json',
      'amar-opening-paris-gambit-gent-gambit.json',
      'barnes-opening-gedult-gambit.json',
      'benko-gambit-accepted-central-storming-variation.json',
      'benko-gambit-accepted-dlugy-variation.json',
      'benko-gambit-accepted-fianchetto-variation.json',
      'benko-gambit-accepted-fully-accepted-variation.json',
      'benko-gambit-accepted-modern-variation.json',
      'benko-gambit-accepted-pawn-return-variation.json',
      'benko-gambit-accepted-yugoslav.json',
      'benko-gambit-accepted.json',
      'benko-gambit-declined-bishop-attack.json',
      'benko-gambit-declined-hjorring-countergambit.json',
      'benko-gambit-declined-main-line.json',
      'benko-gambit-declined-pseudo-samisch.json',
      'benko-gambit-declined-quiet-line.json',
      'benko-gambit-declined-sosonko-variation.json',
      'benko-gambit-fianchetto-variation.json',
      'benko-gambit-mutkin-countergambit.json',
      'benko-gambit-nd2-variation.json',
      'benko-gambit-nescafe-frappe-attack.json',
      'benko-gambit-zaitsev-system.json',
      'benko-gambit-zaitsev-variation-nescafe-frappe-attack.json',
      'benko-gambit.json',
      'benoni-defense-benoni-gambit-accepted.json',
      'benoni-defense-benoni-gambit-schlenker-defense.json',
      'benoni-defense-cormorant-gambit.json',
      'benoni-defense-zilbermints-benoni-gambit.json',
      'bird-opening-dutch-variation-batavo-gambit.json',
      'bird-opening-dutch-variation-dudweiler-gambit.json',
      'bird-opening-froms-gambit-bahr-gambit.json',
      'bird-opening-froms-gambit-lipke-variation.json',
      'bird-opening-froms-gambit.json',
      'bird-opening-hobbs-gambit.json',
      'bird-opening-hobbs-zilbermints-gambit.json',
      'bird-opening-lasker-gambit.json',
      'bird-opening-platz-gambit.json',
      'bird-opening-schlechter-gambit.json',
      'bird-opening-sturm-gambit.json',
      'bird-opening-wagner-zwitersch-gambit.json',
      'bird-opening-williams-gambit.json',
      'bishops-gambit-classical-defense-cozio-attack.json',
      'bishops-opening-anderssen-gambit.json',
      'bishops-opening-berlin-defense-greco-gambit.json',
      'bishops-opening-boden-kieseritzky-gambit-lichtenhein-defense.json',
      'bishops-opening-boden-kieseritzky-gambit.json',
      'bishops-opening-calabrese-countergambit-jaenisch-variation.json',
      'bishops-opening-calabrese-countergambit.json',
      'bishops-opening-four-pawns-gambit.json',
      'bishops-opening-horwitz-gambit.json',
      'bishops-opening-khan-gambit.json',
      'bishops-opening-krejcik-gambit.json',
      'bishops-opening-lewis-countergambit-walker-variation.json',
      'bishops-opening-lewis-countergambit.json',
      'bishops-opening-lewis-gambit.json',
      'bishops-opening-lopez-gambit.json',
      'bishops-opening-lopez-variation-lopez-gambit.json',
      'bishops-opening-mcdonnell-gambit-la-bourdonnais-denker-gambit.json',
      'bishops-opening-mcdonnell-gambit-mcdonnell-double-gambit.json',
      'bishops-opening-mcdonnell-gambit.json',
      'bishops-opening-pachman-gambit.json',
      'bishops-opening-ponziani-gambit.json',
      'bishops-opening-stein-gambit.json',
      'bishops-opening-thorold-gambit.json',
      'bishops-opening-urusov-gambit-keidansky-gambit.json',
      'bishops-opening-urusov-gambit-panov-variation.json',
      'bishops-opening-urusov-gambit.json',
      'bishops-opening-warsaw-gambit.json',
      'blackmar-diemer-gambit-accepted-bogoljubow-defense-kloss-attack.json',
      'blackmar-diemer-gambit-accepted-bogoljubow-defense.json',
      'blackmar-diemer-gambit-accepted-euwe-defense-duthilleul-gambit.json',
      'blackmar-diemer-gambit-accepted-euwe-defense-zilbermints-gambit.json',
      'blackmar-diemer-gambit-accepted-euwe-defense.json',
      'blackmar-diemer-gambit-accepted-gunderam-defense.json',
      'blackmar-diemer-gambit-accepted-holwell-defense.json',
      'blackmar-diemer-gambit-accepted-kaulich-defense.json',
      'blackmar-diemer-gambit-accepted-pietrowsky-defense.json',
      'blackmar-diemer-gambit-accepted-ritter-defense.json',
      'blackmar-diemer-gambit-accepted-ryder-gambit.json',
      'blackmar-diemer-gambit-accepted-schlutter-defense.json',
      'blackmar-diemer-gambit-accepted-teichmann-defense.json',
      'blackmar-diemer-gambit-accepted-ziegler-defense.json',
      'blackmar-diemer-gambit-accepted.json',
      'blackmar-diemer-gambit-blackmar-gambit.json',
      'blackmar-diemer-gambit-declined-brombacher-countergambit.json',
      'blackmar-diemer-gambit-declined-elbert-countergambit.json',
      'blackmar-diemer-gambit-declined-gedult-defense.json',
      'blackmar-diemer-gambit-declined-lamb-defense.json',
      'blackmar-diemer-gambit-declined-langeheinicke-defense.json',
      'blackmar-diemer-gambit-declined-okelly-defense.json',
      'blackmar-diemer-gambit-declined-vienna-defense.json',
      'blackmar-diemer-gambit-declined-weinsbach-defense-pfrang-gambit.json',
      'blackmar-diemer-gambit-declined-weinsbach-defense.json',
      'blackmar-diemer-gambit-diemer-rosenberg-attack.json',
      'blackmar-diemer-gambit-fritz-attack.json',
      'blackmar-diemer-gambit-lemberger-countergambit-endgame-variation.json',
      'blackmar-diemer-gambit-lemberger-countergambit-lange-gambit.json',
      'blackmar-diemer-gambit-lemberger-countergambit-rasmussen-attack.json',
      'blackmar-diemer-gambit-lemberger-countergambit-sneiders-attack.json',
      'blackmar-diemer-gambit-lemberger-countergambit-soller-attack.json',
      'blackmar-diemer-gambit-lemberger-countergambit.json',
      'blackmar-diemer-gambit-netherlands-variation.json',
      'blackmar-diemer-gambit-rasa-studier-gambit.json',
      'blackmar-diemer-gambit-reversed-albin-countergambit.json',
      'blackmar-diemer-gambit-von-popiel-gambit-zilbermints-variation.json',
      'blackmar-diemer-gambit-von-popiel-gambit.json',
      'blackmar-diemer-gambit-zeller-defense-soller-attack.json',
      'blackmar-diemer-gambit-zeller-defense.json',
      'blackmar-diemer-gambit.json',
      'blumenfeld-countergambit-accepted.json',
      'blumenfeld-countergambit-duz-khotimirsky-variation.json',
      'blumenfeld-countergambit.json',
      'bogoljubow-defense-mad-dog-attack.json',
      'bogoljubow-defense-nimzowitsch-attack.json',
      'bogoljubow-defense-studier-attack.json',
      'borg-defense-borg-gambit.json',
      'borg-defense-troon-gambit.json',
      'borg-defense-zilbermints-gambit.json',
      'budapest-gambit-accepted-fajarowicz-defense-bonsdorf-variation.json',
      'budapest-gambit-accepted-fajarowicz-defense-steiner-variation.json',
      'budapest-gambit-accepted-main-line-adler-variation.json',
      'budapest-gambit-accepted-main-line-alekhine-variation.json',
      'budapest-gambit-accepted-main-line-rubinstein-variation.json',
      'caro-kann-defense-alekhine-gambit.json',
      'caro-kann-defense-labahn-attack-double-gambit.json',
      'caro-kann-defense-mieses-gambit.json',
      'caro-kann-defense-von-hennig-gambit.json',
      'carr-defense-zilbermints-gambit.json',
      'catalan-opening-hungarian-gambit.json',
      'center-game-halasz-mcdonnell-gambit-crocodile-variation.json',
      'center-game-halasz-mcdonnell-gambit.json',
      'center-game-lanc-arnold-gambit-schippler-gambit.json',
      'center-game-lanc-arnold-gambit.json',
      'center-game-ross-gambit.json',
      'center-game-von-der-lasa-gambit.json',
      'classical-variation-greco-gambit-anderssen-variation.json',
      'classical-variation-greco-gambit-moeller-bayonet-attack.json',
      'classical-variation-greco-gambit-moeller-therkatz-attack.json',
      'classical-variation-rubinstein-countergambit.json',
      'damiano-defence-refutation.json',
      'danish-gambit-accepted-chigorin-defense.json',
      'danish-gambit-accepted-classical-defense.json',
      'danish-gambit-accepted-copenhagen-defense.json',
      'danish-gambit-accepted-schlechter-defense.json',
      'danish-gambit-accepted-svenonius-defense.json',
      'danish-gambit-accepted.json',
      'danish-gambit-declined-sorensen-defense.json',
      'danish-gambit.json',
      'delayed-alapin-variation-basman-palatnik-double-gambit.json',
      'dragon-variation-classical-variation-zollner-gambit.json',
      'duras-gambit.json',
      'dutch-defense-bellon-gambit.json',
      'dutch-defense-blackmars-second-gambit.json',
      'dutch-defense-janzen-korchnoi-gambit.json',
      'dutch-defense-kingfisher-gambit.json',
      'dutch-defense-krejcik-gambit-tate-gambit.json',
      'dutch-defense-krejcik-gambit.json',
      'dutch-defense-manhattan-gambit-anti-classical-line.json',
      'dutch-defense-manhattan-gambit-anti-leningrad.json',
      'dutch-defense-manhattan-gambit-anti-modern.json',
      'dutch-defense-manhattan-gambit-anti-stonewall.json',
      'dutch-defense-omega-isis-gambit.json',
      'dutch-defense-senechaud-gambit.json',
      'dutch-defense-spielmann-gambit.json',
      'dutch-defense-staunton-gambit-accepted.json',
      'dutch-defense-staunton-gambit-alekhine-variation.json',
      'dutch-defense-staunton-gambit-american-attack.json',
      'dutch-defense-staunton-gambit-chigorin-variation.json',
      'dutch-defense-staunton-gambit-lasker-variation.json',
      'dutch-defense-staunton-gambit-nimzowitsch-variation.json',
      'dutch-defense-staunton-gambit-tartakower-variation.json',
      'dutch-defense-staunton-gambit.json',
      'elephant-gambit-maroczy-gambit.json',
      'elephant-gambit-paulsen-countergambit.json',
      'elephant-gambit-wasp-variation.json',
      'elephant-gambit.json',
      'elephant-trap.json',
      'english-defense-eastbourne-gambit.json',
      'english-opening-achilles-omega-gambit.json',
      'english-opening-anglo-dutch-defense-hickmann-gambit.json',
      'english-opening-anglo-scandinavian-defense-lohn-gambit.json',
      'english-opening-anglo-scandinavian-defense-schulz-gambit.json',
      'english-opening-jaenisch-gambit.json',
      'english-opening-myers-gambit.json',
      'english-opening-wade-gambit.json',
      'english-opening-wing-gambit.json',
      'english-opening-zilbermints-gambit.json',
      'englund-gambit-declined-diemer-counterattack.json',
      'englund-gambit-declined-reversed-alekhine.json',
      'englund-gambit-declined-reversed-brooklyn.json',
      'englund-gambit-declined-reversed-french.json',
      'englund-gambit-declined-reversed-krebs.json',
      'englund-gambit-declined-reversed-mokele-mbembe.json',
      'englund-gambit-declined.json',
      'englund-gambit-felbecker-gambit.json',
      'englund-gambit-hartlaub-charlick-gambit.json',
      'englund-gambit-main-line.json',
      'englund-gambit-mosquito-gambit.json',
      'englund-gambit-soller-gambit-deferred.json',
      'englund-gambit-soller-gambit.json',
      'englund-gambit-stockholm-variation.json',
      'englund-gambit-trap.json',
      'englund-gambit-zilbermints-gambit.json',
      'englund-gambit.json',
      'falkbeer-countergambit-charousek-gambit-accepted.json',
      'falkbeer-countergambit-charousek-gambit-keres-variation.json',
      'falkbeer-countergambit-charousek-gambit-main-line.json',
      'falkbeer-countergambit-charousek-gambit-morphy-defense.json',
      'falkbeer-countergambit-charousek-gambit-old-line.json',
      'falkbeer-countergambit-milner-barry-variation.json',
      'falkbeer-countergambit-nimzowitsch-marshall-countergambit.json',
      'falkbeer-countergambit-rubinstein-variation.json',
      'fishing-pole-trap.json',
      'four-knights-game-halloween-gambit-oldtimer-variation.json',
      'four-knights-game-halloween-gambit-plasma-variation.json',
      'four-knights-game-halloween-gambit.json',
      'four-knights-game-italian-variation-noa-gambit.json',
      'four-knights-game-scotch-variation-belgrade-gambit.json',
      'four-knights-game-scotch-variation-krause-gambit.json',
      'french-defense-advance-variation-milner-barry-gambit.json',
      'french-defense-alapin-gambit.json',
      'french-defense-alekhine-chatard-attack-albin-chatard-gambit.json',
      'french-defense-baeuerle-gambit.json',
      'french-defense-banzai-leong-gambit.json',
      'french-defense-carlson-gambit.json',
      'french-defense-diemer-duhm-gambit-accepted.json',
      'french-defense-diemer-duhm-gambit.json',
      'french-defense-fort-knox-queen-trap.json',
      'french-defense-la-bourdonnais-variation-reuter-gambit.json',
      'french-defense-marshall-gambit.json',
      'french-defense-morphy-gambit.json',
      'french-defense-winawer-variation-alekhine-gambit-accepted.json',
      'french-defense-winawer-variation-alekhine-gambit-kan-variation.json',
      'french-defense-wing-gambit.json',
      'grob-opening-alessi-gambit.json',
      'grob-opening-double-grob-coca-cola-gambit.json',
      'grob-opening-grob-gambit-basman-gambit.json',
      'grob-opening-grob-gambit-declined.json',
      'grob-opening-grob-gambit-fritz-gambit-romford-countergambit.json',
      'grob-opening-grob-gambit-fritz-gambit.json',
      'grob-opening-grob-gambit-richter-grob-gambit.json',
      'grob-opening-grob-gambit.json',
      'grob-opening-romford-countergambit.json',
      'grob-opening-zilbermints-gambit-schiller-defense.json',
      'grunfeld-defense-brinckmann-attack-grunfeld-gambit-accepted.json',
      'grunfeld-defense-gibbon-gambit.json',
      'gunderam-defense-stader-variation.json',
      'halosar-trap.json',
      'hamppe-allgaier-gambit-alapin-variation.json',
      'hamppe-allgaier-gambit-thorold-variation.json',
      'horwitz-defense-zilbermints-gambit.json',
      'hungarian-opening-asten-gambit.json',
      'hungarian-opening-bucker-gambit.json',
      'hungarian-opening-pachman-gambit.json',
      'hungarian-opening-van-kuijk-gambit.json',
      'hungarian-opening-wiedenhagen-beta-gambit.json',
      'hungarian-opening-winterberg-gambit.json',
      'indian-defense-anti-grunfeld-adorjan-gambit.json',
      'indian-defense-budapest-gambit-accepted-fajarowicz-defense.json',
      'indian-defense-budapest-gambit-accepted.json',
      'indian-defense-budapest-gambit.json',
      'indian-defense-gibbins-weidenhagen-gambit-accepted.json',
      'indian-defense-gibbins-weidenhagen-gambit-oshima-defense.json',
      'indian-defense-gibbins-weidenhagen-gambit.json',
      'indian-defense-lazard-gambit.json',
      'indian-defense-maddigan-gambit.json',
      'indian-defense-omega-gambit.json',
      'indian-defense-pyrenees-gambit.json',
      'irish-gambit.json',
      'italian-game-belloni-trap.json',
      'italian-game-blackburne-kostic-gambit.json',
      'italian-game-classical-variation-albin-gambit.json',
      'italian-game-classical-variation-greco-gambit-dubov-italian.json',
      'italian-game-classical-variation-greco-gambit-greco-variation.json',
      'italian-game-classical-variation-greco-gambit-main-line.json',
      'italian-game-classical-variation-greco-gambit-modern-line.json',
      'italian-game-classical-variation-greco-gambit-traditional-line.json',
      'italian-game-deutz-gambit.json',
      'italian-game-evans-gambit-accepted.json',
      'italian-game-evans-gambit-alapin-steinitz-variation.json',
      'italian-game-evans-gambit-anderssen-defense.json',
      'italian-game-evans-gambit-anderssen-variation-cordel-line.json',
      'italian-game-evans-gambit-anderssen-variation.json',
      'italian-game-evans-gambit-bronstein-defense.json',
      'italian-game-evans-gambit-compromised-defense-main-line.json',
      'italian-game-evans-gambit-compromised-defense-potter-variation.json',
      'italian-game-evans-gambit-compromised-defense.json',
      'italian-game-evans-gambit-declined-cordel-variation.json',
      'italian-game-evans-gambit-declined-hicken-variation.json',
      'italian-game-evans-gambit-declined-hirschbach-variation.json',
      'italian-game-evans-gambit-declined-lange-variation.json',
      'italian-game-evans-gambit-declined-pavlov-variation.json',
      'italian-game-evans-gambit-declined-showalter-variation.json',
      'italian-game-evans-gambit-declined-vasquez-variation.json',
      'italian-game-evans-gambit-declined.json',
      'italian-game-evans-gambit-dufresne-defense.json',
      'italian-game-evans-gambit-fontaine-countergambit.json',
      'italian-game-evans-gambit-fraser-attack.json',
      'italian-game-evans-gambit-fraser-mortimer-attack.json',
      'italian-game-evans-gambit-goring-attack.json',
      'italian-game-evans-gambit-harding-variation.json',
      'italian-game-evans-gambit-hein-countergambit.json',
      'italian-game-evans-gambit-johner-defense.json',
      'italian-game-evans-gambit-laroche-variation.json',
      'italian-game-evans-gambit-lasker-defense.json',
      'italian-game-evans-gambit-leonhardt-countergambit.json',
      'italian-game-evans-gambit-levenfish-variation.json',
      'italian-game-evans-gambit-main-line.json',
      'italian-game-evans-gambit-mayet-defense.json',
      'italian-game-evans-gambit-mcdonnell-defense-main-line.json',
      'italian-game-evans-gambit-mcdonnell-defense.json',
      'italian-game-evans-gambit-mieses-defense.json',
      'italian-game-evans-gambit-morphy-attack.json',
      'italian-game-evans-gambit-mortimer-evans-gambit.json',
      'italian-game-evans-gambit-paulsen-variation.json',
      'italian-game-evans-gambit-pierce-defense.json',
      'italian-game-evans-gambit-richardson-attack.json',
      'italian-game-evans-gambit-sanders-alapin-variation.json',
      'italian-game-evans-gambit-slow-variation.json',
      'italian-game-evans-gambit-sokolsky-variation.json',
      'italian-game-evans-gambit-steinitz-variation.json',
      'italian-game-evans-gambit-stone-ware-variation.json',
      'italian-game-evans-gambit-tartakower-attack.json',
      'italian-game-evans-gambit-ulvestad-variation.json',
      'italian-game-evans-gambit-waller-attack.json',
      'italian-game-evans-gambit.json',
      'italian-game-giuoco-pianissimo-lucchini-gambit.json',
      'italian-game-jerome-gambit.json',
      'italian-game-rosentreter-gambit.json',
      'italian-game-rousseau-gambit.json',
      'italian-game-scotch-gambit-anderssen-attack-main-line.json',
      'italian-game-scotch-gambit-anderssen-attack.json',
      'italian-game-scotch-gambit-canal-variation.json',
      'italian-game-scotch-gambit-de-riviere-defense.json',
      'italian-game-scotch-gambit-double-gambit-accepted.json',
      'italian-game-scotch-gambit-janowski-defense.json',
      'italian-game-scotch-gambit-max-lange-attack-accepted.json',
      'italian-game-scotch-gambit-max-lange-attack-long-variation.json',
      'italian-game-scotch-gambit-max-lange-attack-spielmann-defense.json',
      'italian-game-scotch-gambit-max-lange-attack.json',
      'italian-game-scotch-gambit-nakhmanson-gambit.json',
      'italian-game-scotch-gambit-walbrodt-baird-gambit.json',
      'italian-game-scotch-gambit.json',
      'italian-game-two-knights-defense-fried-liver-attack.json',
      'italian-game-two-knights-defense-kloss-gambit.json',
      'italian-game-two-knights-defense-ponziani-steinitz-gambit.json',
      'italian-game-two-knights-defense-traxler-counterattack.json',
      'italian-game-two-knights-defense-ulvestad-variation.json',
      'kadas-opening-kadas-gambit.json',
      'kadas-opening-schneider-gambit.json',
      'kadas-opening-steinbok-gambit.json',
      'kieninger-trap.json',
      'kieseritzky-gambit-berlin-defense-de-riviere-variation.json',
      'kieseritzky-gambit-berlin-defense-rubinstein-variation.json',
      'kieseritzky-gambit-brentano-defense-caro-variation.json',
      'kieseritzky-gambit-paulsen-defense-deferred.json',
      'kieseritzky-long-whip-defense-jaenisch-variation.json',
      'kings-gambit-accepted-abbazia-defense-main-line.json',
      'kings-gambit-accepted-abbazia-defense.json',
      'kings-gambit-accepted-allgaier-blackburne-gambit.json',
      'kings-gambit-accepted-allgaier-cook-variation.json',
      'kings-gambit-accepted-allgaier-gambit-thorold-attack.json',
      'kings-gambit-accepted-allgaier-gambit-urusov-attack.json',
      'kings-gambit-accepted-allgaier-gambit.json',
      'kings-gambit-accepted-allgaier-horny-defense.json',
      'kings-gambit-accepted-allgaier-schlechter-defense.json',
      'kings-gambit-accepted-allgaier-urusov-attack.json',
      'kings-gambit-accepted-australian-gambit.json',
      'kings-gambit-accepted-basman-gambit.json',
      'kings-gambit-accepted-becker-defense.json',
      'kings-gambit-accepted-bishops-gambit-anderssen-defense.json',
      'kings-gambit-accepted-bishops-gambit-anderssen-variation.json',
      'kings-gambit-accepted-bishops-gambit-bledow-countergambit.json',
      'kings-gambit-accepted-bishops-gambit-bledow-variation.json',
      'kings-gambit-accepted-bishops-gambit-boden-variation.json',
      'kings-gambit-accepted-bishops-gambit-bogoljubow-defense.json',
      'kings-gambit-accepted-bishops-gambit-bogoljubow-variation.json',
      'kings-gambit-accepted-bishops-gambit-boren-svenonius-variation.json',
      'kings-gambit-accepted-bishops-gambit-bryan-countergambit.json',
      'kings-gambit-accepted-bishops-gambit-chigorins-attack.json',
      'kings-gambit-accepted-bishops-gambit-classical-defense.json',
      'kings-gambit-accepted-bishops-gambit-cozio-defense.json',
      'kings-gambit-accepted-bishops-gambit-cozio-variation.json',
      'kings-gambit-accepted-bishops-gambit-first-jaenisch-variation.json',
      'kings-gambit-accepted-bishops-gambit-fraser-variation.json',
      'kings-gambit-accepted-bishops-gambit-gianutio-gambit.json',
      'kings-gambit-accepted-bishops-gambit-greco-variation.json',
      'kings-gambit-accepted-bishops-gambit-grimm-attack.json',
      'kings-gambit-accepted-bishops-gambit-kieseritzky-gambit.json',
      'kings-gambit-accepted-bishops-gambit-lopez-defense.json',
      'kings-gambit-accepted-bishops-gambit-lopez-variation.json',
      'kings-gambit-accepted-bishops-gambit-maurian-defense.json',
      'kings-gambit-accepted-bishops-gambit-mcdonnell-attack.json',
      'kings-gambit-accepted-bishops-gambit-paulsen-attack.json',
      'kings-gambit-accepted-bishops-gambit-steinitz-defense.json',
      'kings-gambit-accepted-bishops-gambit.json',
      'kings-gambit-accepted-blachly-gambit.json',
      'kings-gambit-accepted-bonsch-osmolovsky-variation.json',
      'kings-gambit-accepted-breyer-gambit.json',
      'kings-gambit-accepted-carrera-gambit.json',
      'kings-gambit-accepted-cunningham-defense-bertin-gambit.json',
      'kings-gambit-accepted-cunningham-defense-mccormick-defense.json',
      'kings-gambit-accepted-cunningham-defense.json',
      'kings-gambit-accepted-dodo-variation.json',
      'kings-gambit-accepted-double-muzio-gambit-baldwin-gambit.json',
      'kings-gambit-accepted-double-muzio-gambit-bello-gambit.json',
      'kings-gambit-accepted-double-muzio-gambit-paulsen-defense.json',
      'kings-gambit-accepted-double-muzio-gambit-young-gambit.json',
      'kings-gambit-accepted-double-muzio-gambit.json',
      'kings-gambit-accepted-eisenberg-variation.json',
      'kings-gambit-accepted-fischer-defense-schulder-gambit.json',
      'kings-gambit-accepted-fischer-defense-spanish-variation.json',
      'kings-gambit-accepted-fischer-defense.json',
      'kings-gambit-accepted-gaga-gambit.json',
      'kings-gambit-accepted-ghulam-kassim-gambit.json',
      'kings-gambit-accepted-gianutio-countergambit.json',
      'kings-gambit-accepted-greco-gambit.json',
      'kings-gambit-accepted-hanstein-gambit.json',
      'kings-gambit-accepted-kieseritzky-gambit-anderssen-cordel-gambit.json',
      'kings-gambit-accepted-kieseritzky-gambit-anderssen-defense.json',
      'kings-gambit-accepted-kieseritzky-gambit-berlin-defense.json',
      'kings-gambit-accepted-kieseritzky-gambit-brentano-defense.json',
      'kings-gambit-accepted-kieseritzky-gambit-cotter-gambit.json',
      'kings-gambit-accepted-kieseritzky-gambit-kolisch-defense.json',
      'kings-gambit-accepted-kieseritzky-gambit-long-whip.json',
      'kings-gambit-accepted-kieseritzky-gambit-neumann-defense.json',
      'kings-gambit-accepted-kieseritzky-gambit-paulsen-defense.json',
      'kings-gambit-accepted-kieseritzky-gambit-rice-gambit.json',
      'kings-gambit-accepted-kieseritzky-gambit-rosenthal-defense.json',
      'kings-gambit-accepted-kieseritzky-gambit.json',
      'kings-gambit-accepted-kieseritzky-polerio-defense.json',
      'kings-gambit-accepted-kieseritzky-rice-gambit.json',
      'kings-gambit-accepted-kieseritzky-salvio-defense-cozio-variation.json',
      'kings-gambit-accepted-kings-knights-gambit.json',
      'kings-gambit-accepted-kotov-gambit.json',
      'kings-gambit-accepted-lolli-gambit-young-variation.json',
      'kings-gambit-accepted-lolli-gambit.json',
      'kings-gambit-accepted-macleod-defense.json',
      'kings-gambit-accepted-mason-keres-gambit.json',
      'kings-gambit-accepted-mayet-gambit.json',
      'kings-gambit-accepted-mcdonnell-gambit.json',
      'kings-gambit-accepted-middleton-countergambit.json',
      'kings-gambit-accepted-modern-defense.json',
      'kings-gambit-accepted-muzio-gambit-accepted-froms-defense.json',
      'kings-gambit-accepted-muzio-gambit-brentano-defense.json',
      'kings-gambit-accepted-muzio-gambit-holloway-defense.json',
      'kings-gambit-accepted-muzio-gambit-sarratt-defense.json',
      'kings-gambit-accepted-muzio-gambit-wild-muzio-gambit.json',
      'kings-gambit-accepted-orsini-gambit.json',
      'kings-gambit-accepted-paris-gambit.json',
      'kings-gambit-accepted-philidor-gambit-schultz-variation.json',
      'kings-gambit-accepted-philidor-gambit.json',
      'kings-gambit-accepted-quaade-gambit.json',
      'kings-gambit-accepted-rosentreter-gambit-bird-gambit.json',
      'kings-gambit-accepted-rosentreter-gambit-sorensen-gambit.json',
      'kings-gambit-accepted-rosentreter-gambit-testa-variation.json',
      'kings-gambit-accepted-rosentreter-gambit.json',
      'kings-gambit-accepted-salvio-gambit-anderssen-counterattack.json',
      'kings-gambit-accepted-salvio-gambit-cochrane-gambit.json',
      'kings-gambit-accepted-salvio-gambit-santa-maria-defense.json',
      'kings-gambit-accepted-salvio-gambit-silberschmidt-defense.json',
      'kings-gambit-accepted-salvio-gambit-viennese-variation.json',
      'kings-gambit-accepted-salvio-gambit.json',
      'kings-gambit-accepted-schallopp-defense-tashkent-attack.json',
      'kings-gambit-accepted-schallopp-defense.json',
      'kings-gambit-accepted-schurig-gambit-with-bb5.json',
      'kings-gambit-accepted-schurig-gambit-with-bd3.json',
      'kings-gambit-accepted-silberschmidt-gambit.json',
      'kings-gambit-accepted-sorensen-gambit.json',
      'kings-gambit-accepted-stamma-gambit.json',
      'kings-gambit-accepted-tartakower-gambit-weiss-defense.json',
      'kings-gambit-accepted-tartakower-gambit.json',
      'kings-gambit-accepted-traditional-variation.json',
      'kings-gambit-accepted-tumbleweed.json',
      'kings-gambit-accepted-villemson-gambit.json',
      'kings-gambit-accepted-wagenbach-defense.json',
      'kings-gambit-accepted.json',
      'kings-gambit-declined-classical-hanham-variation.json',
      'kings-gambit-declined-classical-reti-variation.json',
      'kings-gambit-declined-classical-soldatenkov-variation.json',
      'kings-gambit-declined-classical-svenonius-variation.json',
      'kings-gambit-declined-classical-variation-euwe-attack.json',
      'kings-gambit-declined-classical-variation-rotlewi-countergambit.json',
      'kings-gambit-declined-classical-variation-walthoffen-attack.json',
      'kings-gambit-declined-classical-variation.json',
      'kings-gambit-declined-falkbeer-countergambit-accepted.json',
      'kings-gambit-declined-falkbeer-countergambit-alapin-variation.json',
      'kings-gambit-declined-falkbeer-countergambit-anderssen-attack.json',
      'kings-gambit-declined-falkbeer-countergambit-blackburne-attack.json',
      'kings-gambit-declined-falkbeer-countergambit-charousek-gambit.json',
      'kings-gambit-declined-falkbeer-countergambit-charousek-variation.json',
      'kings-gambit-declined-falkbeer-countergambit-hinrichsen-gambit.json',
      'kings-gambit-declined-falkbeer-countergambit-miles-gambit.json',
      'kings-gambit-declined-falkbeer-countergambit-modern-transfer.json',
      'kings-gambit-declined-falkbeer-countergambit-pickler-gambit.json',
      'kings-gambit-declined-falkbeer-countergambit-staunton-line.json',
      'kings-gambit-declined-falkbeer-countergambit-tarrasch-variation.json',
      'kings-gambit-declined-falkbeer-countergambit.json',
      'kings-gambit-declined-hobbs-zilbermints-gambit.json',
      'kings-gambit-declined-keene-defense.json',
      'kings-gambit-declined-keenes-defense.json',
      'kings-gambit-declined-mafia-defense.json',
      'kings-gambit-declined-miles-defense.json',
      'kings-gambit-declined-norwalde-variation-bucker-gambit.json',
      'kings-gambit-declined-norwalde-variation-schubert-variation.json',
      'kings-gambit-declined-norwalde-variation.json',
      'kings-gambit-declined-panteldakis-countergambit-greco-variation.json',
      'kings-gambit-declined-panteldakis-countergambit-shirazi-line.json',
      'kings-gambit-declined-panteldakis-countergambit.json',
      'kings-gambit-declined-petrovs-defense.json',
      'kings-gambit-declined-queens-knight-defense.json',
      'kings-gambit-declined-senechaud-countergambit.json',
      'kings-gambit-declined-soller-zilbermints-gambit.json',
      'kings-gambit-declined-zilbermints-double-countergambit.json',
      'kings-gambit-declined-zilbermints-double-gambit.json',
      'kings-gambit.json',
      'kings-indian-attack-omega-delta-gambit.json',
      'kings-indian-defense-samisch-variation-samisch-gambit-accepted.json',
      'kings-indian-defense-samisch-variation-samisch-gambit.json',
      'kings-pawn-game-bavarian-gambit.json',
      'kings-pawn-game-beyer-gambit.json',
      'kings-pawn-game-busch-gass-gambit-chiodini-gambit.json',
      'kings-pawn-game-busch-gass-gambit.json',
      'kings-pawn-game-clam-variation-kings-gambit-reversed.json',
      'kings-pawn-game-gunderam-defense-gunderam-gambit.json',
      'kings-pawn-game-gunderam-gambit.json',
      'kings-pawn-game-macleod-attack-norwalde-gambit.json',
      'kings-pawn-game-pachman-wing-gambit.json',
      'kings-pawn-game-philidor-gambit.json',
      'kings-pawn-game-schulze-muller-gambit.json',
      'kings-pawn-game-tayler-opening-basman-gambit.json',
      'kings-pawn-game-wayward-queen-attack-kiddie-countergambit.json',
      'kings-pawn-game-weber-gambit.json',
      'kings-pawn-opening-van-hooydoon-gambit.json',
      'lasker-pelikan-variation-sveshnikov-variation-peresypkins.json',
      'lasker-trap.json',
      'latvian-gambit-accepted-bilguer-variation.json',
      'latvian-gambit-accepted-bronstein-attack.json',
      'latvian-gambit-accepted-bronstein-gambit.json',
      'latvian-gambit-accepted-foltys-leonhardt-variation.json',
      'latvian-gambit-accepted-foltys-variation.json',
      'latvian-gambit-accepted-leonhardt-variation.json',
      'latvian-gambit-accepted-main-line.json',
      'latvian-gambit-accepted-nimzowitsch-attack.json',
      'latvian-gambit-accepted.json',
      'latvian-gambit-behting-variation.json',
      'latvian-gambit-clam-gambit.json',
      'latvian-gambit-corkscrew-countergambit.json',
      'latvian-gambit-corkscrew-gambit.json',
      'latvian-gambit-diepstraten-countergambit.json',
      'latvian-gambit-lobster-gambit.json',
      'latvian-gambit-mason-countergambit.json',
      'latvian-gambit-mayet-attack.json',
      'latvian-gambit-mlotkowski-variation.json',
      'latvian-gambit.json',
      'legals-mate.json',
      'lion-defense-anti-philidor-lions-cave-lion-claw-gambit.json',
      'lopez-gianutio-countergambit-hein-variation.json',
      'magnus-smith-trap.json',
      'mexican-defense-horsefly-gambit.json',
      'mikenas-defense-pozarek-gambit.json',
      'milner-barry-trap.json',
      'modern-defense-lizard-defense-pirc-diemer-gambit.json',
      'modern-defense-masur-gambit.json',
      'modern-defense-westermann-gambit.json',
      'modern-defense-wind-gambit.json',
      'monticelli-trap.json',
      'morphy-defense-schliemann-defense-deferred-jaenisch-gambit.json',
      'mortimer-trap.json',
      'muzio-gambit-kling-and-horwitz-counterattack.json',
      'nimzo-indian-defense-classical-variation-belyavsky-gambit.json',
      'nimzo-indian-defense-dilworth-gambit.json',
      'nimzo-larsen-attack-norfolk-gambit.json',
      'nimzo-larsen-attack-pachman-gambit.json',
      'nimzo-larsen-attack-ringelbach-gambit.json',
      'nimzowitsch-defense-colorado-countergambit-accepted.json',
      'nimzowitsch-defense-colorado-countergambit.json',
      'nimzowitsch-defense-hornung-gambit.json',
      'nimzowitsch-defense-kennedy-variation-bielefelder-gambit.json',
      'nimzowitsch-defense-kennedy-variation-de-smet-gambit.json',
      'nimzowitsch-defense-kennedy-variation-hammer-gambit.json',
      'nimzowitsch-defense-kennedy-variation-herford-gambit.json',
      'nimzowitsch-defense-wheeler-gambit.json',
      'noahs-ark-trap.json',
      'nyezhmetdinov-rossolimo-attack-fianchetto-variation-gufeld.json',
      'nyezhmetdinov-rossolimo-attack-fianchetto-variation-lutikov.json',
      'nyezhmetdinov-rossolimo-attack-san-francisco-gambit.json',
      'old-indian-defense-aged-gibbon-gambit.json',
      'owen-defense-naselwaus-gambit.json',
      'owen-defense-smith-gambit.json',
      'owen-defense-wind-gambit.json',
      'panov-attack-fianchetto-defense-fianchetto-gambit.json',
      'panteldakis-countergambit-pawn-sacrifice-line.json',
      'panteldakis-countergambit-schillers-defense.json',
      'panteldakis-countergambit-symmetrical-variation.json',
      'petrovs-defense-cochrane-gambit.json',
      'petrovs-defense-marshall-trap.json',
      'petrovs-defense-moody-gambit.json',
      'petrovs-defense-stafford-gambit-accepted.json',
      'petrovs-defense-stafford-gambit.json',
      'philidor-defense-bird-gambit.json',
      'philidor-defense-lopez-countergambit.json',
      'philidor-defense-morphy-gambit.json',
      'philidor-defense-philidor-countergambit-berger-variation.json',
      'philidor-defense-philidor-countergambit-del-rio-attack.json',
      'philidor-defense-philidor-countergambit-zukertort-variation.json',
      'philidor-defense-philidor-countergambit.json',
      'philidor-defense-philidor-gambit.json',
      'pirc-defense-roscher-gambit.json',
      'polish-defense-spassky-gambit-accepted.json',
      'polish-opening-birmingham-gambit.json',
      'polish-opening-tartakower-gambit.json',
      'ponziani-opening-ponziani-countergambit-schmidt-attack.json',
      'ponziani-opening-ponziani-countergambit.json',
      'ponziani-opening-vukovic-gambit.json',
      'portuguese-gambit-melbourne-shuffle-variation.json',
      'portuguese-opening-miguel-gambit.json',
      'portuguese-opening-portuguese-gambit.json',
      'queens-gambit-accepted-old-variation-b5-trap.json',
      'queens-gambit-declined-albin-countergambit-fianchetto-variation.json',
      'queens-gambit-declined-albin-countergambit-modern-line.json',
      'queens-gambit-declined-albin-countergambit-normal-line.json',
      'queens-gambit-declined-albin-countergambit-spassky-variation.json',
      'queens-gambit-declined-albin-countergambit-tartakower-defense.json',
      'queens-gambit-declined-albin-countergambit.json',
      'queens-indian-defense-classical-variation-polugaevsky-gambit.json',
      'queens-pawn-game-chigorin-variation-irish-gambit.json',
      'queens-pawn-game-hubsch-gambit.json',
      'queens-pawn-game-zurich-gambit.json',
      'rat-defense-english-rat-lisbon-gambit.json',
      'reti-opening-zilbermints-gambit.json',
      'richter-veresov-attack-malich-gambit.json',
      'rubinstein-trap.json',
      'ruy-lopez-alapin-defense-alapin-gambit.json',
      'ruy-lopez-berlin-defense-rio-gambit-accepted.json',
      'ruy-lopez-central-countergambit.json',
      'ruy-lopez-classical-variation-cordel-gambit.json',
      'ruy-lopez-classical-variation-konikowski-gambit.json',
      'ruy-lopez-classical-variation-spanish-wing-gambit.json',
      'ruy-lopez-classical-variation-zukertort-gambit.json',
      'ruy-lopez-closed-alekhine-gambit.json',
      'ruy-lopez-closed-basque-gambit.json',
      'ruy-lopez-closed-center-attack-basque-gambit.json',
      'ruy-lopez-closed-chigorin-defense-gajewski-gambit.json',
      'ruy-lopez-exchange-variation-alapin-gambit.json',
      'ruy-lopez-halloween-attack.json',
      'ruy-lopez-marshall-attack-main-line-spassky-variation.json',
      'ruy-lopez-marshall-attack-main-line.json',
      'ruy-lopez-marshall-attack-modern-main-line.json',
      'ruy-lopez-marshall-attack-modern-variation.json',
      'ruy-lopez-marshall-attack-original-marshall-attack.json',
      'ruy-lopez-marshall-attack-re3-variation.json',
      'ruy-lopez-marshall-attack-steiner-variation.json',
      'ruy-lopez-marshall-attack.json',
      'ruy-lopez-morphy-defense-jaffe-gambit.json',
      'ruy-lopez-morphy-defense-norwegian-variation-nightingale-gambit.json',
      'ruy-lopez-morphy-defense-schliemann-defense-deferred.json',
      'ruy-lopez-open-harksen-gambit.json',
      'ruy-lopez-open-karpov-gambit.json',
      'ruy-lopez-open-skipworth-gambit.json',
      'ruy-lopez-schliemann-defense-classical-variation.json',
      'ruy-lopez-schliemann-defense-dyckhoff-variation.json',
      'ruy-lopez-schliemann-defense-exchange-variation.json',
      'ruy-lopez-schliemann-defense-jaenisch-gambit-accepted.json',
      'ruy-lopez-schliemann-defense-kostic-defense.json',
      'ruy-lopez-schliemann-defense-mohring-variation.json',
      'ruy-lopez-schliemann-defense-schonemann-attack.json',
      'ruy-lopez-schliemann-defense-tartakower-variation.json',
      'ruy-lopez-schliemann-defense.json',
      'ruy-lopez-spanish-countergambit-harding-gambit.json',
      'ruy-lopez-spanish-countergambit.json',
      'ruy-lopez-steinitz-defense-center-gambit.json',
      'scandinavian-defense-blackburne-gambit.json',
      'scandinavian-defense-blackburne-kloosterboer-gambit.json',
      'scandinavian-defense-boehnke-gambit.json',
      'scandinavian-defense-icelandic-palme-gambit.json',
      'scandinavian-defense-kadas-gambit.json',
      'scandinavian-defense-kiel-variation-trap.json',
      'scandinavian-defense-main-line-leonhardt-gambit.json',
      'scandinavian-defense-portuguese-gambit-banker-variation.json',
      'scandinavian-defense-portuguese-gambit-jadoul-variation.json',
      'scandinavian-defense-portuguese-gambit.json',
      'scandinavian-defense-zilbermints-gambit.json',
      'scandinavian-variation-bogoljubow-variation-richter-gambit.json',
      'scheveningen-variation-delayed-keres-attack-perenyi-gambit.json',
      'scholars-mate.json',
      'scotch-game-alekhine-gambit.json',
      'scotch-game-goring-gambit-bardeleben-variation.json',
      'scotch-game-goring-gambit-double-pawn-sacrifice.json',
      'scotch-game-goring-gambit-main-line.json',
      'scotch-game-goring-gambit.json',
      'scotch-game-haxo-gambit.json',
      'scotch-game-napoleon-gambit.json',
      'scotch-game-relfsson-gambit.json',
      'scotch-game-scotch-gambit-advance-variation.json',
      'scotch-game-scotch-gambit-cochrane-anderssen-variation.json',
      'scotch-game-scotch-gambit-dubois-reti-defense.json',
      'scotch-game-scotch-gambit-goring-gambit-declined.json',
      'scotch-game-scotch-gambit-kingside-variation.json',
      'scotch-game-scotch-gambit-london-defense.json',
      'scotch-game-scotch-gambit-sarratt-variation.json',
      'scotch-game-scotch-gambit.json',
      'scotch-variation-belgrade-gambit-modern-defense.json',
      'scotch-variation-krause-gambit-leonhardt-defense.json',
      'semi-slav-defense-anti-moscow-gambit.json',
      'semi-slav-defense-gunderam-gambit.json',
      'semi-slav-defense-marshall-gambit-main-line.json',
      'semi-slav-defense-marshall-gambit-tolush-variation.json',
      'semi-slav-defense-marshall-gambit.json',
      'semi-slav-defense-noteboom-variation-anti-noteboom-gambit.json',
      'siberian-trap.json',
      'sicilian-defense-alapin-variation-anti-alapin-gambit.json',
      'sicilian-defense-brussels-gambit.json',
      'sicilian-defense-coles-sicilian-gambit.json',
      'sicilian-defense-delayed-alapin-variation-basman-palatnik-gambit.json',
      'sicilian-defense-double-dutch-gambit.json',
      'sicilian-defense-euwe-attack-prins-gambit.json',
      'sicilian-defense-halasz-gambit.json',
      'sicilian-defense-kotov-gambit.json',
      'sicilian-defense-kronberger-variation-nemeth-gambit.json',
      'sicilian-defense-mcdonnell-attack-tal-gambit.json',
      'sicilian-defense-modern-variations-ginsberg-gambit.json',
      'sicilian-defense-morphy-gambit-andreaschek-gambit.json',
      'sicilian-defense-morphy-gambit.json',
      'sicilian-defense-moscow-variation-haag-gambit.json',
      'sicilian-defense-moscow-variation-moscow-gambit.json',
      'sicilian-defense-najdorf-variation-dekker-gambit.json',
      'sicilian-defense-okelly-variation-normal-system-cortlever-gambit.json',
      'sicilian-defense-okelly-variation-venice-system-gambit-line.json',
      'sicilian-defense-okelly-variation-wing-gambit.json',
      'sicilian-defense-polish-gambit.json',
      'sicilian-defense-portsmouth-gambit.json',
      'sicilian-defense-smith-morra-gambit-accepted-chicago-defense.json',
      'sicilian-defense-smith-morra-gambit-accepted-classical-formation.json',
      'sicilian-defense-smith-morra-gambit-accepted-danish-variation.json',
      'sicilian-defense-smith-morra-gambit-accepted-fianchetto-defense.json',
      'sicilian-defense-smith-morra-gambit-accepted-finegold-defense.json',
      'sicilian-defense-smith-morra-gambit-accepted-kan-formation.json',
      'sicilian-defense-smith-morra-gambit-accepted-larsen-defense.json',
      'sicilian-defense-smith-morra-gambit-accepted-morphy-defense.json',
      'sicilian-defense-smith-morra-gambit-accepted-paulsen-formation.json',
      'sicilian-defense-smith-morra-gambit-accepted-pin-defense.json',
      'sicilian-defense-smith-morra-gambit-accepted-siberian-variation.json',
      'sicilian-defense-smith-morra-gambit-accepted-sozin-formation.json',
      'sicilian-defense-smith-morra-gambit-accepted-taimanov-formation.json',
      'sicilian-defense-smith-morra-gambit-accepted.json',
      'sicilian-defense-smith-morra-gambit-declined-alapin-formation.json',
      'sicilian-defense-smith-morra-gambit-declined-center-formation.json',
      'sicilian-defense-smith-morra-gambit-declined-dubois-variation.json',
      'sicilian-defense-smith-morra-gambit-declined-push-variation.json',
      'sicilian-defense-smith-morra-gambit-declined-wing-formation.json',
      'sicilian-defense-smith-morra-gambit-deferred.json',
      'sicilian-defense-smith-morra-gambit.json',
      'sicilian-defense-taimanov-variation-gary-gambit.json',
      'sicilian-defense-wing-gambit-abrahams-variation.json',
      'sicilian-defense-wing-gambit-carlsbad-variation.json',
      'sicilian-defense-wing-gambit-deferred-variation.json',
      'sicilian-defense-wing-gambit-deferred.json',
      'sicilian-defense-wing-gambit-marienbad-variation.json',
      'sicilian-defense-wing-gambit-marshall-variation.json',
      'sicilian-defense-wing-gambit-nanu-gambit.json',
      'sicilian-defense-wing-gambit-romanian-defense.json',
      'sicilian-defense-wing-gambit-santasiere-variation.json',
      'sicilian-defense-wing-gambit.json',
      'slav-defense-diemer-gambit.json',
      'slav-defense-geller-gambit.json',
      'slav-defense-slav-gambit-alekhine-attack.json',
      'slav-defense-winawer-countergambit-anti-winawer-gambit.json',
      'slav-defense-winawer-countergambit.json',
      'smith-morra-gambit-accepted-morphy-defense-deferred.json',
      'smith-morra-gambit-accepted-open-d-file-trap.json',
      'smith-morra-gambit-accepted-scheveningen-formation.json',
      'smith-morra-gambit-declined-scandinavian-formation.json',
      'sodium-attack-durkin-gambit.json',
      'spanish-countergambit-harding-countergambit-fricke-gambit.json',
      'st-george-defense-zilbermints-gambit.json',
      'stafford-gambit-rosen-trap.json',
      'steinitz-gambit-fraser-minckwitz-defense.json',
      'steinitz-gambit-paulsen-defense.json',
      'steinitz-gambit-sorensen-defense.json',
      'steinitz-gambit-zukertort-defense.json',
      'taimanov-variation-bastrikov-variation-ponomariov-gambit.json',
      'tarrasch-defense-classical-variation-classical-tarrasch-gambit.json',
      'tarrasch-defense-grunfeld-gambit.json',
      'tarrasch-defense-schara-gambit.json',
      'tarrasch-defense-tarrasch-gambit.json',
      'tarrasch-defense-von-hennig-gambit.json',
      'tarrasch-trap.json',
      'tarrasch-variation-open-system-shaposhnikov-gambit.json',
      'teichmann-defense-ciesielski-variation.json',
      'teichmann-defense-classical-variation.json',
      'teichmann-defense-seidel-hall-attack.json',
      'torre-attack-classical-defense-petrosian-gambit.json',
      'torre-attack-wagner-gambit.json',
      'traxler-counterattack-ke2-trap.json',
      'trompowsky-attack-edge-variation-hergert-gambit.json',
      'trompowsky-attack-raptor-variation-hergert-gambit.json',
      'two-knights-defense-traxler-counterattack-bishop-sacrifice-line.json',
      'two-knights-defense-traxler-counterattack-king-march-line.json',
      'two-knights-defense-traxler-counterattack-knight-sacrifice-line.json',
      'two-knights-defense-traxler-variation-trencianske-teplice-gambit.json',
      'two-knights-defense-ulvestad-variation-kurkin-gambit.json',
      'two-knights-variation-suttles-variation-tal-gambit.json',
      'van-geet-opening-berlin-gambit.json',
      'van-geet-opening-dougherty-gambit.json',
      'van-geet-opening-hector-gambit.json',
      'van-geet-opening-laroche-gambit.json',
      'van-geet-opening-sleipnir-gambit.json',
      'vant-kruijs-opening-keoni-hiva-gambit-akahi-variation.json',
      'vant-kruijs-opening-keoni-hiva-gambit-alua-variation.json',
      'vienna-gambit-with-max-lange-defense-cunningham-defense.json',
      'vienna-gambit-with-max-lange-defense-hamppe-allgaier-gambit.json',
      'vienna-gambit-with-max-lange-defense-hamppe-muzio-gambit.json',
      'vienna-gambit-with-max-lange-defense-knight-variation.json',
      'vienna-gambit-with-max-lange-defense-pierce-gambit.json',
      'vienna-gambit-with-max-lange-defense-quelle-gambit.json',
      'vienna-gambit-with-max-lange-defense-steinitz-gambit-main-line.json',
      'vienna-gambit-with-max-lange-defense-steinitz-gambit.json',
      'vienna-gambit-with-max-lange-defense.json',
      'vienna-game-adams-gambit.json',
      'vienna-game-frankenstein-dracula-qd5-trap.json',
      'vienna-game-frankenstein-dracula-variation.json',
      'vienna-game-fyfe-gambit.json',
      'vienna-game-hamppe-muzio-gambit.json',
      'vienna-game-mieses-variation-erben-gambit.json',
      'vienna-game-omaha-gambit.json',
      'vienna-game-paulsen-variation-mariotti-gambit.json',
      'vienna-game-paulsen-variation-pollock-gambit.json',
      'vienna-game-philidor-countergambit.json',
      'vienna-game-pierce-gambit-rushmere-attack.json',
      'vienna-game-stanley-variation-bronstein-gambit.json',
      'vienna-game-stanley-variation-eifel-gambit.json',
      'vienna-game-stanley-variation-meitner-mieses-gambit.json',
      'vienna-game-vienna-gambit-bardeleben-variation.json',
      'vienna-game-vienna-gambit-breyer-variation.json',
      'vienna-game-vienna-gambit-kaufmann-variation.json',
      'vienna-game-vienna-gambit-main-line.json',
      'vienna-game-vienna-gambit-modern-variation.json',
      'vienna-game-vienna-gambit-paulsen-attack.json',
      'vienna-game-vienna-gambit-steinitz-variation.json',
      'vienna-game-vienna-gambit.json',
      'vienna-game-wurzburger-trap.json',
      'vienna-game-zhuravlev-countergambit.json',
      'ware-opening-ware-gambit.json',
      'ware-opening-wing-gambit.json',
      'winawer-variation-alekhine-gambit-alatortsev-variation.json',
      'zukertort-opening-herrstrom-gambit.json',
      'zukertort-opening-lemberger-gambit.json',
      'zukertort-opening-lisitsyn-gambit.json',
      'zukertort-opening-ross-gambit.json',
      'zukertort-opening-shabalov-gambit.json',
      'zukertort-opening-tennison-gambit-briggs-trap.json',
      'zukertort-opening-tennison-gambit.json',
      'zukertort-opening-vos-gambit.json',
    ])
    const json = readFileSync(join(out, 'damiano-defence-refutation.json'), 'utf8')
    expect(json).not.toContain('\n')
    expect(json).toContain('"tier":"taught"')
  })

  /**
   * The acceptance criterion in one test: the compile fails if validation fails. `npm run
   * build` runs this first and chains with `&&`, so this exit code is what stops a broken
   * entry from reaching a browser.
   */
  it('fails, and writes nothing, when an entry does not pass the gate', () => {
    const source = scratch()
    const out = scratch()
    copyFileSync(
      join(root, 'tools/content/fixtures/invalid/false-mate-claim.yaml'),
      join(source, 'broken.yaml'),
    )
    const result = run('compile-cli.ts', '--source', source, '--out', out)

    expect(result.status).toBe(1)
    expect(result.stderr).toContain('Nothing was compiled')
    expect(readdirSync(out)).toStrictEqual([])
  })

  it('removes a stale file for an entry that no longer exists', () => {
    const out = scratch()
    writeFileSync(join(out, 'deleted-gambit.json'), '{}')
    run('compile-cli.ts', '--out', out)

    expect(readdirSync(out)).not.toContain('deleted-gambit.json')
  })

  /** Deleting a directory a flag pointed at is worth one look first. */
  it('refuses to clear an output directory holding anything it did not write', () => {
    const out = scratch()
    writeFileSync(join(out, 'important.txt'), 'not mine')
    const result = run('compile-cli.ts', '--out', out)

    expect(result.status).toBe(1)
    expect(existsSync(join(out, 'important.txt'))).toBe(true)
  })
})
