import type { ContentIssue } from './issue.ts'
import { joinDataPath } from './issue.ts'
import type { YamlSource } from './yaml-source.ts'

/**
 * Refuse anything a content file is not entitled to state.
 *
 * `kind`, `tier`, a FEN and a proved mate are all *derived*. A file that can state them is
 * a file that can lie: a hand-written FEN drifts from the moves beside it, a hand-written
 * tier is a claim the content has not earned, and a hand-written mate is the exact false
 * claim this project exists to prevent (`docs/CONTEXT.md`, invariants 1, 2, 4 and 8).
 *
 * This runs before schema validation so the author gets the real reason rather than
 * "unrecognized key".
 */

/** Eight ranks of piece placement — the one part of a FEN that cannot occur in prose by accident. */
const FEN_PLACEMENT = /(?:[pnbrqkPNBRQK1-8]{1,8}\/){7}[pnbrqkPNBRQK1-8]{1,8}/

type ForbiddenKey = { readonly test: (key: string) => boolean; readonly explain: string }

const FORBIDDEN_KEYS: readonly ForbiddenKey[] = [
  {
    test: (key) => key === 'kind',
    explain:
      "`kind` (learner or opponent) is derived from side to move and the entry's `side`. It is never authored and never stored in a content file (docs/CONTEXT.md, invariant 2). Remove it. An outcome is discriminated by `type`, not by `kind`, for exactly this reason.",
  },
  {
    test: (key) => key === 'tier',
    explain:
      '`tier` is derived at build time from the content itself and is absent from content files (docs/CONTEXT.md, invariant 8). A tier is a claim about the content, and content is the only thing entitled to make it.',
  },
  {
    test: (key) => /fen/i.test(key),
    explain:
      'A position is derived by replaying plies from the standard start position and is never stored (docs/CONTEXT.md, invariant 1). A stored FEN is one more thing that can silently drift out of sync with the moves beside it.',
  },
]

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value)

const issueAt = (
  source: YamlSource,
  path: readonly (string | number)[],
  message: string,
): ContentIssue => ({
  file: source.file,
  code: 'derived-field',
  dataPath: joinDataPath(path),
  nodePath: undefined,
  at: source.locate(path),
  message,
})

export const findDerivedFields = (source: YamlSource): readonly ContentIssue[] => {
  const issues: ContentIssue[] = []
  const stack: { value: unknown; path: readonly (string | number)[] }[] = [
    { value: source.data, path: [] },
  ]

  while (stack.length > 0) {
    const frame = stack.pop()
    if (frame === undefined) break
    const { value, path } = frame

    if (typeof value === 'string') {
      if (FEN_PLACEMENT.test(value)) {
        issues.push(
          issueAt(
            source,
            path,
            `This value contains a FEN. Positions are derived by replaying plies from the standard start position and are never written into content (docs/CONTEXT.md, invariant 1).`,
          ),
        )
      }
      continue
    }

    if (Array.isArray(value)) {
      value.forEach((item, index) => stack.push({ value: item, path: [...path, index] }))
      continue
    }

    if (!isRecord(value)) continue

    for (const [key, child] of Object.entries(value)) {
      const childPath = [...path, key]
      const forbidden = FORBIDDEN_KEYS.find((candidate) => candidate.test(key))
      if (forbidden !== undefined) {
        issues.push(issueAt(source, childPath, forbidden.explain))
        continue
      }
      if (key === 'type' && child === 'mate') {
        issues.push(
          issueAt(
            source,
            childPath,
            'A forced mate is generated by the build, never authored (docs/CONTEXT.md, invariant 4; ADR-0005). The author states the moves and writes neither a move count nor the word "mate"; the build proves it or refuses the claim.',
          ),
        )
        continue
      }
      stack.push({ value: child, path: childPath })
    }
  }

  return issues
}
