/**
 * The domain types for a content entry, per `docs/CONTEXT.md`.
 *
 * These describe content *after* validation and derivation. They are deliberately not
 * the same shape as the authored YAML: `kind`, `tier` and every position are derived
 * here and rejected there, because a file that can state them is a file that can lie
 * (invariants 1, 2 and 8).
 *
 * Build-time only. Nothing in this file ships to the browser.
 */

export type Locale = 'vi' | 'en' | 'fr'

/** Vietnamese is the source locale; `en` and `fr` fall back to it and are marked untranslated. */
export type Annotation = {
  readonly vi: string
  readonly en?: string | undefined
  readonly fr?: string | undefined
}

export type Side = 'white' | 'black'
export type Category = 'gambit' | 'trap'
export type SoundnessValue = 'sound' | 'dubious' | 'unsound'
export type ReplyQuality = 'best' | 'good' | 'inaccuracy' | 'mistake' | 'blunder'
export type Frequency = 'common' | 'occasional' | 'rare'

/** Derived from side to move and the entry's `side`. Never authored (invariant 2). */
export type NodeKind = 'learner' | 'opponent'

/** Derived by the build from the content itself. Never authored (invariant 8). */
export type Tier = 'listed' | 'mapped' | 'taught'

/**
 * Where a claim came from. A machine proof and an author's opinion are rendered
 * differently, because giving an unverified opinion the visual weight of a proof is
 * worse than proving nothing at all.
 */
export type Proved = {
  readonly basis: 'proved'
  readonly by: 'certificate'
  /** The certificate's file name, so the proof can be found and replayed (ADR-0005). */
  readonly certificate: string
}

export type Judgement = {
  readonly basis: 'judgement'
  readonly by: string
  readonly at: string
  readonly source?: string | undefined
}

export type Provenance = Proved | Judgement

/**
 * The opponent is checkmated in `inMoves` moves however they defend.
 *
 * Generated by the build, never hand-authored (invariant 4, ADR-0005). The author marks a
 * leaf as a claimed trap and writes neither a move count nor the word "mate"; `validate.ts`
 * replaces that claim with this shape only once a committed certificate has been verified
 * move by move, and refuses the file otherwise.
 *
 * `basis` is the narrow `Proved` provenance rather than the full union, so a hand-judged
 * mate is not expressible: there is no way to construct this type without naming a
 * certificate. That is the type-level half of invariant 4.
 */
export type ForcedMate = {
  readonly kind: 'mate'
  readonly inMoves: number
  /**
   * The longest line in the net, in plies from this leaf — the mate as it goes when the
   * defender holds out longest. A mate in N runs to `2N - 1` plies.
   */
  readonly sequence: readonly string[]
  /**
   * Which half of the proof carries "mate within N". A net with defender branching is
   * proved by set equality against the legal move list (`modelled-net`); where the attacker
   * mates at once there is no net to model and a one-ply exhaustive search settles it
   * (`search`). Minimality is established by bounded search in both cases, and is not what
   * this field records (docs/CONTEXT.md, invariant 4).
   */
  readonly provedBy: 'search' | 'modelled-net'
  readonly basis: Proved
}

/**
 * The opponent defended adequately. The normal outcome for a gambit, not a consolation prize.
 *
 * `basis` is the narrow `Judgement` and not the full union, for the mirror image of
 * `ForcedMate`'s reason: `Proved` names a mate certificate (ADR-0005) and a merely winning
 * position has none to name, so a proved assessment is not expressible either.
 */
export type Assessment = {
  readonly kind: 'position'
  readonly evaluation: Annotation
  readonly plan: Annotation
  readonly basis: Judgement
}

/** Not mapped yet. Exists so half-finished work is committable; holds the entry below Mapped. */
export type Unexplored = { readonly kind: 'unexplored' }

export type Outcome = ForcedMate | Assessment | Unexplored

export type DismissedReply = {
  readonly ply: string
  readonly reason: string
}

/**
 * One catch-all standing in for every legal reply that is neither modelled nor individually
 * dismissed.
 *
 * Thirty-four hand-written dismissals per node is not work anyone completes, and an author
 * who stops modelling opponent nodes leaves a larger hole than the one invariant 7a exists
 * to close. The guarantee is unchanged: a learner is never met with a reply the site has
 * nothing to say about, and "any other move here does not challenge the gambit" is an
 * answer.
 *
 * Its `reason` is localised, unlike `DismissedReply.reason`: a per-move dismissal is a
 * maintainer's note read in a diff, whereas this one is shown to the learner.
 */
export type DismissRest = {
  readonly reason: Annotation
  /**
   * The replies this catch-all actually covers, derived from the legal move list at
   * validation time. Never authored — the whole point is that the number is computed and
   * stated rather than hidden behind one line.
   */
  readonly covers: readonly string[]
}

/** A position in the tree, reached by one ply from its parent. */
export type ContentNode = {
  /** The single SAN move that reached this node. Absent on the root. */
  readonly ply: string | undefined
  /** Derived, never authored. */
  readonly kind: NodeKind
  /** Derived by replaying from the standard start position; never stored in a file. */
  readonly fen: string
  readonly annotation: Annotation | undefined
  readonly replyQuality: ReplyQuality | undefined
  readonly frequency: Frequency | undefined
  readonly dismissed: readonly DismissedReply[]
  /** Only on an opponent node that models replies. See `DismissRest`. */
  readonly dismissRest: DismissRest | undefined
  readonly children: readonly ContentNode[]
  readonly outcome: Outcome | undefined
  /** SAN path from the entry root that this position transposes into. */
  readonly transposesTo: readonly string[] | undefined
}

export type Soundness = {
  readonly value: SoundnessValue
  readonly reviewedAt: string
  readonly basis: Provenance
}

/**
 * One position of the **prelude**: the walk from the initial position through the defining
 * line, ending at the gambit root.
 *
 * Derived, exactly like a node's FEN and for the same reason (invariant 1). The browser has
 * no rules engine — chess.js is a build dependency and the board tripwire keeps it that way
 * — so the only place these boards can come from is the same replay that validated the
 * line.
 *
 * `ply` is absent on the first step, which is the initial position and was reached by no
 * move. That mirrors `ContentNode.ply`, which is absent on the root for the same reason.
 */
export type PreludeStep = {
  readonly ply: string | undefined
  readonly fen: string
}

export type Entry = {
  readonly id: string
  readonly name: string
  readonly eco: string
  readonly category: Category
  /** The side the learner plays. Determines which nodes are learner nodes. */
  readonly side: Side
  readonly definingLine: readonly string[]
  /**
   * The initial position and every position the defining line passes through, in order, so
   * its length is `definingLine.length + 1` and its last entry is the root's own position.
   */
  readonly prelude: readonly PreludeStep[]
  readonly soundness: Soundness
  /**
   * Provenance for every authored judgement in this entry that is not a leaf assessment:
   * annotations, reply qualities and frequencies. They are one author's impression on one
   * date, and invariant 7b requires them to say so.
   */
  readonly judgement: Provenance
  readonly tree: ContentNode
  /** Derived, never authored. */
  readonly tier: Tier
}

/**
 * Narrowing helper used by every exhaustive switch. It takes `never`, so adding a fourth
 * outcome shape without handling it is a compile error rather than a silent fallthrough.
 */
export const assertNever = (value: never): never => {
  throw new Error(`Unhandled variant: ${JSON.stringify(value)}`)
}
