import type { Position } from './board.ts'
import { applyPly, replay } from './board.ts'
import type { ContentIssue, IssueCode, SourceLocation } from './issue.ts'
import { joinDataPath, joinNodePath } from './issue.ts'
import { findDerivedFields } from './derived-fields.ts'
import type {
  AuthoredAnnotation,
  AuthoredDismissRest,
  AuthoredEntry,
  AuthoredNode,
  AuthoredOutcome,
  AuthoredRoot,
} from './schema.ts'
import { parseEntry } from './schema.ts'
import type {
  Annotation,
  ContentNode,
  DismissRest,
  DismissedReply,
  Entry,
  NodeKind,
  Outcome,
  Side,
  Tier,
} from './types.ts'
import { assertNever } from './types.ts'
import type { YamlSource } from './yaml-source.ts'
import { loadYaml } from './yaml-source.ts'

/**
 * The content gate (requirement F12). Implements the blocking checks of ADR-0004 that do
 * not need a mate proof: schema, legality, SAN canonicalisation, checkmate and non-mate
 * assertion, reply completeness, duplicates and transpositions, i18n completeness and side
 * consistency. Mate proving is ADR-0005 and issue #5.
 *
 * Every issue names the file and the node, as a SAN path and as a data path, because an
 * error the author cannot locate is an error they will work around rather than fix.
 */

export type Coverage = {
  readonly slots: number
  readonly vi: number
  readonly en: number
  readonly fr: number
}

/**
 * One accepted `dismissRest` and what it actually covers.
 *
 * The catch-all is one line of YAML standing in for any number of replies, so the validator
 * states that number back at the author rather than letting the line hide it (issue #29,
 * AC 4). It is not an issue: a counted, reasoned omission is what invariant 7a asks for.
 */
export type DismissRestReport = {
  /** The node as a chess player reads it, e.g. `tree > Bxb4`. */
  readonly nodePath: string
  readonly dataPath: string
  readonly covers: readonly string[]
  readonly legalReplies: number
}

export type EntryReport = {
  readonly file: string
  readonly issues: readonly ContentIssue[]
  /** Present only when the file validated; carries the derived `kind`, position and `tier`. */
  readonly entry: Entry | undefined
  readonly coverage: Coverage
  readonly nodeCount: number
  readonly dismissedCount: number
  readonly dismissRest: readonly DismissRestReport[]
}

type Walk = {
  readonly source: YamlSource
  readonly learnerSide: Side
  readonly issues: ContentIssue[]
  /** Canonical SAN path from the entry root -> the position there, for transposition lookup. */
  readonly byPath: Map<string, Position>
  /** First-four-FEN-fields -> the node paths that reach it, for duplicate detection. */
  readonly byPositionKey: Map<string, string[]>
  readonly transpositions: {
    readonly from: readonly string[]
    readonly to: readonly string[]
    readonly position: Position
    readonly dataPath: readonly (string | number)[]
  }[]
  coverage: { slots: number; vi: number; en: number; fr: number }
  nodeCount: number
  dismissedCount: number
  readonly dismissRest: DismissRestReport[]
}

const report = (
  walk: Walk,
  code: IssueCode,
  dataPath: readonly (string | number)[],
  sanPath: readonly string[] | undefined,
  message: string,
): void => {
  const at: SourceLocation | undefined = walk.source.locate(dataPath)
  walk.issues.push({
    file: walk.source.file,
    code,
    dataPath: joinDataPath(dataPath),
    nodePath: sanPath === undefined ? undefined : joinNodePath(sanPath),
    at,
    message,
  })
}

const toAnnotation = (authored: AuthoredAnnotation): Annotation => ({
  vi: authored.vi,
  en: authored.en,
  fr: authored.fr,
})

const toOutcome = (authored: AuthoredOutcome): Outcome => {
  switch (authored.type) {
    case 'unexplored':
      return { kind: 'unexplored' }
    case 'position':
      return {
        kind: 'position',
        evaluation: toAnnotation(authored.evaluation),
        plan: toAnnotation(authored.plan),
        basis: {
          basis: 'judgement',
          by: authored.basis.by,
          at: authored.basis.at,
          source: authored.basis.source,
        },
      }
    default:
      return assertNever(authored)
  }
}

/** What an outcome contributes to the derived tier. Exhaustive over all three shapes. */
const outcomeReachesTier = (outcome: Outcome): { mapped: boolean; taught: boolean } => {
  switch (outcome.kind) {
    case 'mate':
      // Generated by the build (#5). A proved mate is fully mapped and fully taught.
      return { mapped: true, taught: true }
    case 'position':
      return { mapped: true, taught: true }
    case 'unexplored':
      // The honest "not yet mapped" state; it is what holds an entry below Mapped.
      return { mapped: false, taught: false }
    default:
      return assertNever(outcome)
  }
}

const countAnnotation = (walk: Walk, annotation: AuthoredAnnotation | undefined): void => {
  walk.coverage.slots += 1
  if (annotation === undefined) return
  walk.coverage.vi += 1
  if (annotation.en !== undefined) walk.coverage.en += 1
  if (annotation.fr !== undefined) walk.coverage.fr += 1
}

const shapesOf = (node: AuthoredRoot | AuthoredNode): readonly string[] =>
  [
    node.children === undefined ? undefined : 'children',
    node.outcome === undefined ? undefined : 'outcome',
    node.transposesTo === undefined ? undefined : 'transposesTo',
  ].filter((name) => name !== undefined)

/**
 * Compare the authored SAN with what `chess.js` re-serialises the move as (ADR-0004 check 3).
 * A claimed checkmate that is not checkmate, and a real checkmate that was not claimed, are
 * reported as themselves rather than as a generic spelling difference — they are the two
 * halves of the error class this project was started to demonstrate.
 */
const checkCanonical = (
  walk: Walk,
  authored: string,
  canonical: string,
  after: Position,
  dataPath: readonly (string | number)[],
  sanPath: readonly string[],
): void => {
  if (authored === canonical) return

  if (authored.endsWith('#') && !after.isCheckmate) {
    report(
      walk,
      'false-mate-claim',
      dataPath,
      sanPath,
      `\`${authored}\` claims checkmate, but the position it reaches is not checkmate. The move is \`${canonical}\` (docs/CONTEXT.md, invariant 6).`,
    )
    return
  }

  if (authored.endsWith('+') && !canonical.endsWith('+') && !canonical.endsWith('#')) {
    report(
      walk,
      'false-check-claim',
      dataPath,
      sanPath,
      `\`${authored}\` claims check, but the move gives no check. The move is \`${canonical}\`.`,
    )
    return
  }

  if (canonical.endsWith('#') && !authored.endsWith('#')) {
    report(
      walk,
      'unclaimed-mate',
      dataPath,
      sanPath,
      `\`${authored}\` is checkmate and must be written \`${canonical}\`. An unmarked mate is how a line that ends the game gets published as an ordinary move.`,
    )
    return
  }

  report(
    walk,
    'san-not-canonical',
    dataPath,
    sanPath,
    `\`${authored}\` is legal but is not the canonical SAN for the move. Write \`${canonical}\`. A move that re-serialises differently corrupts the tree silently (ADR-0004, check 3).`,
  )
}

/**
 * ADR-0004 check 7. The check the product turns on.
 *
 * Returns the replies a `dismissRest` covers here — the leftovers after modelled children
 * and individual dismissals — or nothing when there is no catch-all or it was refused.
 */
const checkReplyCompleteness = (
  walk: Walk,
  position: Position,
  modelled: ReadonlySet<string>,
  dismissed: ReadonlySet<string>,
  dismissRest: AuthoredDismissRest | undefined,
  dataPath: readonly (string | number)[],
  sanPath: readonly string[],
): readonly string[] => {
  const covered = new Set([...modelled, ...dismissed])
  const rest = position.legalMoves.filter((move) => !covered.has(move))
  const both = [...modelled].filter((move) => dismissed.has(move))

  if (dismissRest === undefined) {
    if (rest.length > 0) {
      report(
        walk,
        'reply-incomplete',
        dataPath,
        sanPath,
        `${rest.length} of ${position.legalMoves.length} legal replies are neither modelled nor dismissed: ${rest.join(', ')}. At an opponent node the learner controls nothing, so every legal reply must be answered or explicitly dismissed with a reason (docs/CONTEXT.md, invariant 7a). Where the honest answer is the same for all of them, one \`dismissRest\` with a reason covers the lot.`,
      )
    }
  } else if (rest.length === 0) {
    report(
      walk,
      'dismiss-rest-covers-nothing',
      [...dataPath, 'dismissRest'],
      sanPath,
      `\`dismissRest\` covers nothing here: all ${position.legalMoves.length} legal replies are already modelled or individually dismissed. A catch-all that answers no reply is decoration, and decoration is how it ends up pasted at every node whether it says anything or not. Remove it.`,
    )
  }

  // Checked whether or not there is a catch-all. `dismissRest` covers only what is left
  // over, so an overlap between `children` and `dismissed` is arithmetically invisible to
  // it — and a catch-all that could silence this check would be a way to file a modelled
  // reply as one of the replies nobody looked at.
  if (both.length > 0) {
    report(
      walk,
      'dismissed-also-modelled',
      dataPath,
      sanPath,
      `${both.join(', ')} ${both.length === 1 ? 'is' : 'are'} both modelled as a child and listed in \`dismissed\`. A reply is one or the other.`,
    )
  }

  return dismissRest === undefined ? [] : rest
}

const walkNode = (
  walk: Walk,
  node: AuthoredRoot | AuthoredNode,
  position: Position,
  dataPath: readonly (string | number)[],
  sanPath: readonly string[],
  ply: string | undefined,
  parentKind: NodeKind | undefined,
): ContentNode => {
  walk.nodeCount += 1
  const kind: NodeKind = position.turn === walk.learnerSide ? 'learner' : 'opponent'

  const existing = walk.byPositionKey.get(position.key) ?? []
  if (node.transposesTo === undefined) {
    walk.byPositionKey.set(position.key, [...existing, joinNodePath(sanPath)])
  }
  walk.byPath.set(sanPath.join(' '), position)

  const shapes = shapesOf(node)
  if (shapes.length !== 1) {
    report(
      walk,
      'node-shape',
      dataPath,
      sanPath,
      shapes.length === 0
        ? 'A node must have exactly one of `children`, `outcome` or `transposesTo`. This one has none, so the line stops with no statement about where it stopped (ADR-0004, schema decisions).'
        : `A node must have exactly one of \`children\`, \`outcome\` or \`transposesTo\`. This one has ${shapes.join(' and ')}. Only a leaf carries an outcome (docs/CONTEXT.md, invariant 3).`,
    )
  }

  countAnnotation(walk, node.annotation)

  if ('replyQuality' in node && node.replyQuality !== undefined && parentKind !== 'opponent') {
    report(
      walk,
      'kind-mismatch',
      [...dataPath, 'replyQuality'],
      sanPath,
      `\`replyQuality\` describes how bad the opponent's reply was, so it belongs only on a child of an opponent node. \`${ply ?? '(root)'}\` is a ${walk.learnerSide} move the gambit prescribes, not a reply (docs/CONTEXT.md, Node; ADR-0004 check 12).`,
    )
  }

  if ('frequency' in node && node.frequency !== undefined && parentKind !== 'opponent') {
    report(
      walk,
      'kind-mismatch',
      [...dataPath, 'frequency'],
      sanPath,
      `\`frequency\` describes how often the opponent plays a reply, so it belongs only on a child of an opponent node.`,
    )
  }

  const dismissedReplies: DismissedReply[] = []
  const dismissedSet = new Set<string>()
  if (node.dismissed !== undefined) {
    walk.dismissedCount += node.dismissed.length
    if (kind !== 'opponent') {
      report(
        walk,
        'kind-mismatch',
        [...dataPath, 'dismissed'],
        sanPath,
        `\`dismissed\` lists opponent replies that are deliberately not modelled, so it belongs only on an opponent node. Here it is ${walk.learnerSide}'s turn, and what ${walk.learnerSide} plays is the gambit's choice (docs/CONTEXT.md, Node).`,
      )
    }
    if (node.children === undefined) {
      report(
        walk,
        'dismissed-without-children',
        [...dataPath, 'dismissed'],
        sanPath,
        '`dismissed` records the replies not modelled *beside* the ones that are. A node that models no replies is a leaf and states an `outcome` instead.',
      )
    }
    node.dismissed.forEach((entry, index) => {
      const at = [...dataPath, 'dismissed', index, 'ply']
      const played = applyPly(position, entry.ply)
      if (!played.ok) {
        report(
          walk,
          'dismissed-not-legal',
          at,
          sanPath,
          `\`${entry.ply}\` is dismissed as a reply but is not legal here. Dismissing a move that cannot be played hides a reply that can.${played.suggestions.length === 0 ? '' : ` Legal moves to that square: ${played.suggestions.join(', ')}.`}`,
        )
        return
      }
      checkCanonical(walk, entry.ply, played.canonical, played.position, at, sanPath)
      dismissedSet.add(played.canonical)
      dismissedReplies.push({ ply: played.canonical, reason: entry.reason })
    })
  }

  if (node.dismissRest !== undefined) {
    // A learner reads this reason, so it is counted as translatable prose like any other
    // learner-facing text. A catch-all left untranslated is a locale in which 34 replies
    // are answered in Vietnamese.
    countAnnotation(walk, node.dismissRest.reason)

    if (kind !== 'opponent') {
      report(
        walk,
        'kind-mismatch',
        [...dataPath, 'dismissRest'],
        sanPath,
        `\`dismissRest\` answers the opponent replies that are not modelled, so it belongs only on an opponent node. Here it is ${walk.learnerSide}'s turn, and what ${walk.learnerSide} plays is the gambit's choice, not a reply to be covered (docs/CONTEXT.md, Node).`,
      )
    }

    if (node.children === undefined) {
      report(
        walk,
        'dismissed-without-children',
        [...dataPath, 'dismissRest'],
        sanPath,
        '`dismissRest` answers the replies not modelled *beside* the ones that are. A node that models no replies is a leaf and states an `outcome` instead — a catch-all here would be silently ignored.',
      )
    }
  }

  const children: ContentNode[] = []
  const modelled = new Set<string>()
  if (node.children !== undefined) {
    const seen = new Set<string>()
    node.children.forEach((child, index) => {
      const at = [...dataPath, 'children', index]
      if (seen.has(child.ply)) {
        report(
          walk,
          'duplicate-san',
          [...at, 'ply'],
          sanPath,
          `Two children of this node are both \`${child.ply}\`. A position has one node per reply (ADR-0004, check 9).`,
        )
        return
      }
      seen.add(child.ply)

      const played = applyPly(position, child.ply)
      if (!played.ok) {
        report(
          walk,
          'illegal-move',
          [...at, 'ply'],
          sanPath,
          `\`${child.ply}\` is not a legal move in this position.${played.suggestions.length === 0 ? '' : ` Did you mean ${played.suggestions.join(' or ')}? A move that needs disambiguation must carry it.`}`,
        )
        return
      }

      checkCanonical(
        walk,
        child.ply,
        played.canonical,
        played.position,
        [...at, 'ply'],
        [...sanPath, played.canonical],
      )
      modelled.add(played.canonical)
      children.push(
        walkNode(
          walk,
          child,
          played.position,
          at,
          [...sanPath, played.canonical],
          played.canonical,
          kind,
        ),
      )
    })
  }

  const covers =
    kind === 'opponent' && node.children !== undefined
      ? checkReplyCompleteness(
          walk,
          position,
          modelled,
          dismissedSet,
          node.dismissRest,
          dataPath,
          sanPath,
        )
      : []

  const dismissRest: DismissRest | undefined =
    node.dismissRest === undefined
      ? undefined
      : { reason: toAnnotation(node.dismissRest.reason), covers }

  if (covers.length > 0) {
    walk.dismissRest.push({
      nodePath: joinNodePath(sanPath),
      dataPath: joinDataPath([...dataPath, 'dismissRest']),
      covers,
      legalReplies: position.legalMoves.length,
    })
  }

  const outcome = node.outcome === undefined ? undefined : toOutcome(node.outcome)
  if (outcome !== undefined && outcome.kind === 'position') {
    walk.coverage.slots += 2
    walk.coverage.vi += 2
    if (outcome.evaluation.en !== undefined) walk.coverage.en += 1
    if (outcome.plan.en !== undefined) walk.coverage.en += 1
    if (outcome.evaluation.fr !== undefined) walk.coverage.fr += 1
    if (outcome.plan.fr !== undefined) walk.coverage.fr += 1

    if (position.isCheckmate || position.isStalemate) {
      report(
        walk,
        'assessment-is-terminal',
        [...dataPath, 'outcome'],
        sanPath,
        `This leaf is assessed as a playable position, but the game is over here — it is ${position.isCheckmate ? 'checkmate' : 'stalemate'}. This is the reverse of a false mate claim, and it is what mislabels a finished game as a middlegame (ADR-0004, check 5).`,
      )
    }
  }

  if (node.transposesTo !== undefined) {
    walk.transpositions.push({
      from: sanPath,
      to: node.transposesTo,
      position,
      dataPath: [...dataPath, 'transposesTo'],
    })
  }

  return {
    ply,
    kind,
    fen: position.fen,
    annotation: node.annotation === undefined ? undefined : toAnnotation(node.annotation),
    replyQuality: 'replyQuality' in node ? node.replyQuality : undefined,
    frequency: 'frequency' in node ? node.frequency : undefined,
    dismissed: dismissedReplies,
    dismissRest,
    children,
    outcome,
    transposesTo: node.transposesTo,
  }
}

/** ADR-0004 check 9, scoped within one entry (docs/CONTEXT.md, invariant 12). */
const checkDuplicatePositions = (walk: Walk): void => {
  for (const [key, paths] of walk.byPositionKey) {
    if (paths.length < 2) continue
    report(
      walk,
      'duplicate-position',
      ['tree'],
      undefined,
      `${paths.length} nodes reach the same position (${key}): ${paths.join(' , ')}. Point the later one at the first with \`transposesTo\` rather than duplicating the subtree, which would drift out of sync along with its annotations (ADR-0004, check 9).`,
    )
  }
}

const checkTranspositions = (walk: Walk): void => {
  for (const transposition of walk.transpositions) {
    const targetKey = transposition.to.join(' ')
    const fromKey = transposition.from.join(' ')
    const target = walk.byPath.get(targetKey)

    if (target === undefined) {
      report(
        walk,
        'transposition-unresolved',
        transposition.dataPath,
        transposition.from,
        `No node at \`${joinNodePath(transposition.to)}\`. A \`transposesTo\` path is canonical SAN from the entry root — the position after the defining line, not the initial position (docs/CONTEXT.md, Path).`,
      )
      continue
    }

    if (targetKey === fromKey || targetKey.startsWith(`${fromKey} `)) {
      report(
        walk,
        'transposition-cycle',
        transposition.dataPath,
        transposition.from,
        'A node cannot transpose into itself or into its own subtree.',
      )
      continue
    }

    if (target.key !== transposition.position.key) {
      report(
        walk,
        'transposition-mismatch',
        transposition.dataPath,
        transposition.from,
        `These are different positions, so this is not a transposition.\n    here:   ${transposition.position.key}\n    target: ${target.key}\n  Compared on the first four FEN fields only (docs/CONTEXT.md, invariant 12).`,
      )
    }
  }
}

const hasUnexplored = (node: ContentNode): boolean => {
  if (node.outcome !== undefined && !outcomeReachesTier(node.outcome).mapped) return true
  return node.children.some(hasUnexplored)
}

const isFullyTaught = (node: ContentNode, coverage: Coverage): boolean => {
  if (coverage.slots === 0) return false
  if (coverage.vi !== coverage.slots) return false
  if (coverage.en !== coverage.slots || coverage.fr !== coverage.slots) return false
  const taughtLeaves = (candidate: ContentNode): boolean => {
    if (candidate.outcome !== undefined && !outcomeReachesTier(candidate.outcome).taught)
      return false
    return candidate.children.every(taughtLeaves)
  }
  return taughtLeaves(node)
}

/** Derived from the content, never authored (docs/CONTEXT.md, invariant 8). */
const deriveTier = (tree: ContentNode, coverage: Coverage): Tier => {
  if (tree.children.length === 0) return 'listed'
  if (hasUnexplored(tree)) return 'listed'
  return isFullyTaught(tree, coverage) ? 'taught' : 'mapped'
}

const emptyCoverage: Coverage = { slots: 0, vi: 0, en: 0, fr: 0 }

const failed = (file: string, issues: readonly ContentIssue[]): EntryReport => ({
  file,
  issues,
  entry: undefined,
  coverage: emptyCoverage,
  nodeCount: 0,
  dismissedCount: 0,
  dismissRest: [],
})

const buildEntry = (source: YamlSource, authored: AuthoredEntry): EntryReport => {
  const walk: Walk = {
    source,
    learnerSide: authored.side,
    issues: [],
    byPath: new Map(),
    byPositionKey: new Map(),
    transpositions: [],
    coverage: { slots: 0, vi: 0, en: 0, fr: 0 },
    nodeCount: 0,
    dismissedCount: 0,
    dismissRest: [],
  }

  const opening = replay(authored.definingLine)
  if (!opening.ok) {
    report(
      walk,
      'illegal-move',
      ['definingLine', opening.index],
      undefined,
      `\`${authored.definingLine[opening.index] ?? ''}\` is not legal at ply ${opening.index + 1} of the defining line.${opening.suggestions.length === 0 ? '' : ` Did you mean ${opening.suggestions.join(' or ')}?`}`,
    )
    return failed(source.file, walk.issues)
  }

  opening.canonical.forEach((canonical, index) => {
    const authoredPly = authored.definingLine[index]
    if (authoredPly !== undefined && authoredPly !== canonical) {
      report(
        walk,
        'san-not-canonical',
        ['definingLine', index],
        undefined,
        `\`${authoredPly}\` is legal but is not the canonical SAN. Write \`${canonical}\`.`,
      )
    }
  })

  const tree = walkNode(walk, authored.tree, opening.position, ['tree'], [], undefined, undefined)
  checkDuplicatePositions(walk)
  checkTranspositions(walk)

  const coverage: Coverage = { ...walk.coverage }
  const entry: Entry = {
    id: authored.id,
    name: authored.name,
    eco: authored.eco,
    category: authored.category,
    side: authored.side,
    definingLine: opening.canonical,
    soundness: {
      value: authored.soundness.value,
      reviewedAt: authored.soundness.reviewedAt,
      basis: {
        basis: 'judgement',
        by: authored.soundness.basis.by,
        at: authored.soundness.basis.at,
        source: authored.soundness.basis.source,
      },
    },
    judgement: {
      basis: 'judgement',
      by: authored.judgement.by,
      at: authored.judgement.at,
      source: authored.judgement.source,
    },
    tree,
    tier: deriveTier(tree, coverage),
  }

  return {
    file: source.file,
    issues: walk.issues,
    entry: walk.issues.length === 0 ? entry : undefined,
    coverage,
    nodeCount: walk.nodeCount,
    dismissedCount: walk.dismissedCount,
    dismissRest: walk.dismissRest,
  }
}

export const validateText = (file: string, text: string): EntryReport => {
  const loaded = loadYaml(file, text)
  if (!loaded.ok) return failed(file, loaded.issues)

  const derived = findDerivedFields(loaded.source)
  if (derived.length > 0) return failed(file, derived)

  const parsed = parseEntry(loaded.source)
  if (!parsed.ok) return failed(file, parsed.issues)

  return buildEntry(loaded.source, parsed.entry)
}
