import { expect, test, type Page } from '@playwright/test'
import { compileEntry } from '../tools/content/compile.ts'
import { loadContent } from '../tools/content/entries.ts'
import { countableBranches } from '../src/components/progress/branches.ts'
import type { CompiledNode } from '../src/lib/content-types.ts'
import { lineSearch, parseLine } from '../src/lib/line.ts'
import { routeSegments } from '../src/lib/routes.ts'
import vi from '../src/locales/vi.ts'

/**
 * AC 7 of #15, and the only test in the suite that touches published content rather than a
 * fixture: every taught entry is walked from the catalogue index to **every one of its
 * leaves**, by clicking, against the built site on a real static host.
 *
 * The leaves are read from `content/` and compiled here rather than from the JSON the site
 * serves, and that direction matters. Taking them from the served file would make the test
 * agree with whatever the compile step emitted, so a compile that silently dropped a
 * subtree would still pass — it would simply have fewer leaves to check. Reading the
 * authored tree and then requiring the deployed site to answer for each of its leaves is
 * the assertion that has something to fail on.
 *
 * `countableBranches` is imported rather than reimplemented for the same reason
 * `tools/catalogue/build.ts` imports it: the set of root-to-leaf lines is one rule, and a
 * second copy of it here would eventually disagree with the number on the card.
 */

const basePath = process.env.BASE_PATH ?? '/chess-gambits/'
const cataloguePath = `${basePath}vi/${routeSegments.catalogue}`

const content = loadContent('content')
if (!content.ok) {
  throw new Error(
    `content/ does not pass the gate, so there is nothing to walk:\n${content.issues
      .map((issue) => `${issue.file}: ${issue.message}`)
      .join('\n')}`,
  )
}

/** One taught entry, with every root-to-leaf line its authored tree has. */
const taught = content.entries
  .map(({ entry }) => entry)
  .filter((entry) => entry.tier === 'taught')
  .map((entry) => {
    const compiled = compileEntry(entry)
    return {
      id: entry.id,
      name: entry.name,
      eco: entry.eco,
      tree: compiled.tree,
      leaves: countableBranches(compiled.tree).map(
        (key) => parseLine(decodeURIComponent(key)).plies,
      ),
    }
  })

/** The node a path names, so the outcome asserted at a leaf is the one the content states. */
const nodeAt = (tree: CompiledNode, path: readonly string[]): CompiledNode =>
  path.reduce<CompiledNode>((node, ply) => {
    const child = node.children?.find((candidate) => candidate.ply === ply)
    if (child === undefined) throw new Error(`no child \`${ply}\` under ${path.join(' ')}`)
    return child
  }, tree)

/** The card each outcome shape renders as. A leaf must show its own one and no other. */
const CARDS = {
  mate: '.mate-outcome',
  position: '.assessment-outcome',
  unexplored: '.unexplored-outcome',
} as const

const atGambit = async (page: Page, id: string, line: readonly string[]): Promise<void> => {
  await expect(page).toHaveURL(
    new RegExp(
      `/vi/${routeSegments.catalogue}/${id}${lineSearch(line).replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}$`,
    ),
  )
}

test.describe('every taught entry, from the catalogue to every leaf (AC 7)', () => {
  test('there are one thousand and forty-seven of them, and they are the ones the content tickets authored', () => {
    expect(taught.map((entry) => entry.id).sort()).toEqual([
      'accelerated-london-system-steinitz-countergambit',
      'accelerated-london-system-steinitz-countergambit-accepted',
      'accelerated-london-system-steinitz-countergambit-morris',
      'accelerated-london-system-steinitz-countergambit-morris-2',
      'advance-variation-milner-barry-gambit-hector-variation',
      'advance-variation-milner-barry-gambit-sorensen-variation',
      'albin-countergambit-fianchetto-variation-be6-line',
      'albin-countergambit-fianchetto-variation-bf5-line',
      'albin-countergambit-fianchetto-variation-bg4-line',
      'alekhine-defense-four-pawns-attack-cambridge-gambit',
      'alekhine-defense-hunt-variation-lasker-simul-gambit',
      'alekhine-defense-hunt-variation-matsukevich-gambit',
      'alekhine-defense-hunt-variation-mikenas-gambit',
      'alekhine-defense-krejcik-variation-krejcik-gambit',
      'alekhine-defense-osullivan-gambit',
      'alekhine-defense-scandinavian-variation-geschev-gambit',
      'alekhine-defense-scandinavian-variation-myers-gambit',
      'alekhine-defense-spielmann-gambit',
      'amar-opening-paris-gambit-gent-gambit',
      'barnes-opening-gedult-gambit',
      'benko-gambit',
      'benko-gambit-accepted',
      'benko-gambit-accepted-central-storming-variation',
      'benko-gambit-accepted-dlugy-variation',
      'benko-gambit-accepted-fianchetto-variation',
      'benko-gambit-accepted-fully-accepted-variation',
      'benko-gambit-accepted-modern-variation',
      'benko-gambit-accepted-pawn-return-variation',
      'benko-gambit-accepted-yugoslav',
      'benko-gambit-declined-bishop-attack',
      'benko-gambit-declined-hjorring-countergambit',
      'benko-gambit-declined-main-line',
      'benko-gambit-declined-pseudo-samisch',
      'benko-gambit-declined-quiet-line',
      'benko-gambit-declined-sosonko-variation',
      'benko-gambit-mutkin-countergambit',
      'benko-gambit-nd2-variation',
      'benko-gambit-nescafe-frappe-attack',
      'benko-gambit-zaitsev-system',
      'benko-gambit-zaitsev-variation-nescafe-frappe-attack',
      'benoni-defense-benoni-gambit-accepted',
      'benoni-defense-benoni-gambit-schlenker-defense',
      'benoni-defense-benoni-staunton-gambit',
      'benoni-defense-cormorant-gambit',
      'benoni-defense-zilbermints-benoni-gambit',
      'bird-opening-birds-eye-view-trap',
      'bird-opening-dutch-variation-batavo-gambit',
      'bird-opening-dutch-variation-dudweiler-gambit',
      'bird-opening-froms-gambit',
      'bird-opening-froms-gambit-bahr-gambit',
      'bird-opening-froms-gambit-lasker-variation',
      'bird-opening-froms-gambit-lipke-variation',
      'bird-opening-hobbs-gambit',
      'bird-opening-hobbs-zilbermints-gambit',
      'bird-opening-lasker-gambit',
      'bird-opening-platz-gambit',
      'bird-opening-schlechter-gambit',
      'bird-opening-siegener-gambit',
      'bird-opening-sturm-gambit',
      'bird-opening-swiss-gambit',
      'bird-opening-thomas-gambit',
      'bird-opening-wagner-zwitersch-gambit',
      'bird-opening-williams-gambit',
      'bird-opening-williams-zilbermints-gambit',
      'bishops-gambit-classical-defense-cozio-attack',
      'bishops-opening-anderssen-gambit',
      'bishops-opening-berlin-defense-greco-gambit',
      'bishops-opening-boden-kieseritzky-gambit',
      'bishops-opening-boden-kieseritzky-gambit-lichtenhein-defense',
      'bishops-opening-calabrese-countergambit',
      'bishops-opening-calabrese-countergambit-jaenisch-variation',
      'bishops-opening-four-pawns-gambit',
      'bishops-opening-horwitz-gambit',
      'bishops-opening-khan-gambit',
      'bishops-opening-krejcik-gambit',
      'bishops-opening-lewis-countergambit',
      'bishops-opening-lewis-countergambit-walker-variation',
      'bishops-opening-lewis-gambit',
      'bishops-opening-lopez-gambit',
      'bishops-opening-lopez-variation-lopez-gambit',
      'bishops-opening-mcdonnell-gambit',
      'bishops-opening-mcdonnell-gambit-la-bourdonnais-denker-gambit',
      'bishops-opening-mcdonnell-gambit-mcdonnell-double-gambit',
      'bishops-opening-pachman-gambit',
      'bishops-opening-ponziani-gambit',
      'bishops-opening-stein-gambit',
      'bishops-opening-thorold-gambit',
      'bishops-opening-urusov-gambit',
      'bishops-opening-urusov-gambit-keidansky-gambit',
      'bishops-opening-urusov-gambit-panov-variation',
      'bishops-opening-warsaw-gambit',
      'blackmar-diemer-gambit',
      'blackmar-diemer-gambit-accepted',
      'blackmar-diemer-gambit-accepted-bogoljubow-defense',
      'blackmar-diemer-gambit-accepted-bogoljubow-defense-kloss-attack',
      'blackmar-diemer-gambit-accepted-euwe-defense',
      'blackmar-diemer-gambit-accepted-euwe-defense-duthilleul-gambit',
      'blackmar-diemer-gambit-accepted-euwe-defense-zilbermints-gambit',
      'blackmar-diemer-gambit-accepted-gunderam-defense',
      'blackmar-diemer-gambit-accepted-holwell-defense',
      'blackmar-diemer-gambit-accepted-kaulich-defense',
      'blackmar-diemer-gambit-accepted-pietrowsky-defense',
      'blackmar-diemer-gambit-accepted-ritter-defense',
      'blackmar-diemer-gambit-accepted-ryder-gambit',
      'blackmar-diemer-gambit-accepted-schlutter-defense',
      'blackmar-diemer-gambit-accepted-teichmann-defense',
      'blackmar-diemer-gambit-accepted-ziegler-defense',
      'blackmar-diemer-gambit-blackmar-gambit',
      'blackmar-diemer-gambit-declined-brombacher-countergambit',
      'blackmar-diemer-gambit-declined-elbert-countergambit',
      'blackmar-diemer-gambit-declined-gedult-defense',
      'blackmar-diemer-gambit-declined-lamb-defense',
      'blackmar-diemer-gambit-declined-langeheinicke-defense',
      'blackmar-diemer-gambit-declined-okelly-defense',
      'blackmar-diemer-gambit-declined-vienna-defense',
      'blackmar-diemer-gambit-declined-weinsbach-defense',
      'blackmar-diemer-gambit-declined-weinsbach-defense-pfrang-gambit',
      'blackmar-diemer-gambit-diemer-rosenberg-attack',
      'blackmar-diemer-gambit-fritz-attack',
      'blackmar-diemer-gambit-lemberger-countergambit',
      'blackmar-diemer-gambit-lemberger-countergambit-endgame-variation',
      'blackmar-diemer-gambit-lemberger-countergambit-lange-gambit',
      'blackmar-diemer-gambit-lemberger-countergambit-rasmussen-attack',
      'blackmar-diemer-gambit-lemberger-countergambit-sneiders-attack',
      'blackmar-diemer-gambit-lemberger-countergambit-soller-attack',
      'blackmar-diemer-gambit-netherlands-variation',
      'blackmar-diemer-gambit-rasa-studier-gambit',
      'blackmar-diemer-gambit-reversed-albin-countergambit',
      'blackmar-diemer-gambit-von-popiel-gambit',
      'blackmar-diemer-gambit-von-popiel-gambit-zilbermints-variation',
      'blackmar-diemer-gambit-zeller-defense',
      'blackmar-diemer-gambit-zeller-defense-soller-attack',
      'blumenfeld-countergambit',
      'blumenfeld-countergambit-accepted',
      'blumenfeld-countergambit-duz-khotimirsky-variation',
      'blumenfeld-countergambit-spielmann-variation',
      'bogoljubow-defense-mad-dog-attack',
      'bogoljubow-defense-nimzowitsch-attack',
      'bogoljubow-defense-studier-attack',
      'borg-defense-borg-gambit',
      'borg-defense-troon-gambit',
      'borg-defense-zilbermints-gambit',
      'budapest-gambit-accepted-fajarowicz-defense-bonsdorf-variation',
      'budapest-gambit-accepted-fajarowicz-defense-steiner-variation',
      'budapest-gambit-accepted-main-line-adler-variation',
      'budapest-gambit-accepted-main-line-alekhine-variation',
      'budapest-gambit-accepted-main-line-alekhine-variation-2',
      'budapest-gambit-accepted-main-line-alekhine-variation-abonyi',
      'budapest-gambit-accepted-main-line-rubinstein-variation',
      'busch-gass-gambit-trap',
      'caro-kann-defense-alekhine-gambit',
      'caro-kann-defense-alien-gambit',
      'caro-kann-defense-dinic-gambit',
      'caro-kann-defense-hector-gambit',
      'caro-kann-defense-hillbilly-attack-schaeffer-gambit',
      'caro-kann-defense-labahn-attack-double-gambit',
      'caro-kann-defense-maroczy-variation-maroczy-gambit',
      'caro-kann-defense-martian-gambit',
      'caro-kann-defense-mieses-attack-landau-gambit',
      'caro-kann-defense-mieses-gambit',
      'caro-kann-defense-rasa-studier-gambit',
      'caro-kann-defense-scorpion-horus-gambit',
      'caro-kann-defense-spike-variation-scorpion-grob-gambit',
      'caro-kann-defense-ulysses-gambit',
      'caro-kann-defense-von-hennig-gambit',
      'carr-defense-zilbermints-gambit',
      'catalan-opening-closed-spassky-gambit',
      'catalan-opening-hungarian-gambit',
      'center-game-halasz-mcdonnell-gambit',
      'center-game-halasz-mcdonnell-gambit-crocodile-variation',
      'center-game-lanc-arnold-gambit',
      'center-game-lanc-arnold-gambit-schippler-gambit',
      'center-game-ross-gambit',
      'center-game-von-der-lasa-gambit',
      'classical-attack-marshall-variation-chinese-gambit',
      'classical-variation-greco-gambit-anderssen-variation',
      'classical-variation-greco-gambit-moeller-bayonet-attack',
      'classical-variation-greco-gambit-moeller-therkatz-attack',
      'classical-variation-rubinstein-countergambit',
      'damiano-defence-refutation',
      'danish-gambit',
      'danish-gambit-accepted',
      'danish-gambit-accepted-chigorin-defense',
      'danish-gambit-accepted-classical-defense',
      'danish-gambit-accepted-copenhagen-defense',
      'danish-gambit-accepted-schlechter-defense',
      'danish-gambit-accepted-svenonius-defense',
      'danish-gambit-declined-sorensen-defense',
      'delayed-alapin-variation-basman-palatnik-double-gambit',
      'dragon-variation-classical-variation-zollner-gambit',
      'duras-gambit',
      'dutch-defense-bellon-gambit',
      'dutch-defense-blackmars-second-gambit',
      'dutch-defense-janzen-korchnoi-gambit',
      'dutch-defense-kingfisher-gambit',
      'dutch-defense-krejcik-gambit',
      'dutch-defense-krejcik-gambit-tate-gambit',
      'dutch-defense-manhattan-gambit-anti-classical-line',
      'dutch-defense-manhattan-gambit-anti-leningrad',
      'dutch-defense-manhattan-gambit-anti-modern',
      'dutch-defense-manhattan-gambit-anti-stonewall',
      'dutch-defense-omega-isis-gambit',
      'dutch-defense-senechaud-gambit',
      'dutch-defense-spielmann-gambit',
      'dutch-defense-staunton-gambit',
      'dutch-defense-staunton-gambit-accepted',
      'dutch-defense-staunton-gambit-alekhine-variation',
      'dutch-defense-staunton-gambit-american-attack',
      'dutch-defense-staunton-gambit-chigorin-variation',
      'dutch-defense-staunton-gambit-lasker-variation',
      'dutch-defense-staunton-gambit-nimzowitsch-variation',
      'dutch-defense-staunton-gambit-tartakower-variation',
      'elephant-gambit',
      'elephant-gambit-maroczy-gambit',
      'elephant-gambit-paulsen-countergambit',
      'elephant-gambit-wasp-variation',
      'elephant-trap',
      'english-defense-eastbourne-gambit',
      'english-defense-hartlaub-gambit-accepted',
      'english-defense-poli-gambit',
      'english-opening-achilles-omega-gambit',
      'english-opening-anglo-dutch-defense-hickmann-gambit',
      'english-opening-anglo-dutch-variation-chabanon-gambit',
      'english-opening-anglo-dutch-variation-ferenc-gambit',
      'english-opening-anglo-scandinavian-defense-lohn-gambit',
      'english-opening-anglo-scandinavian-defense-schulz-gambit',
      'english-opening-jaenisch-gambit',
      'english-opening-kings-english-erbenheimer-gambit',
      'english-opening-kings-english-variation-adhiban-gambit',
      'english-opening-kings-english-variation-bellon-gambit',
      'english-opening-kings-english-variation-kahiko-hula-gambit',
      'english-opening-myers-gambit',
      'english-opening-symmetrical-variation-combe-hasenfuss-trap',
      'english-opening-symmetrical-variation-napolitano-gambit',
      'english-opening-wade-gambit',
      'english-opening-wing-gambit',
      'english-opening-zilbermints-gambit',
      'englund-gambit',
      'englund-gambit-declined',
      'englund-gambit-declined-diemer-counterattack',
      'englund-gambit-declined-reversed-alekhine',
      'englund-gambit-declined-reversed-brooklyn',
      'englund-gambit-declined-reversed-french',
      'englund-gambit-declined-reversed-krebs',
      'englund-gambit-declined-reversed-mokele-mbembe',
      'englund-gambit-felbecker-gambit',
      'englund-gambit-hartlaub-charlick-gambit',
      'englund-gambit-main-line',
      'englund-gambit-mosquito-gambit',
      'englund-gambit-soller-gambit',
      'englund-gambit-soller-gambit-deferred',
      'englund-gambit-stockholm-variation',
      'englund-gambit-trap',
      'englund-gambit-zilbermints-gambit',
      'falkbeer-countergambit-charousek-gambit-accepted',
      'falkbeer-countergambit-charousek-gambit-keres-variation',
      'falkbeer-countergambit-charousek-gambit-main-line',
      'falkbeer-countergambit-charousek-gambit-morphy-defense',
      'falkbeer-countergambit-charousek-gambit-old-line',
      'falkbeer-countergambit-milner-barry-variation',
      'falkbeer-countergambit-nimzowitsch-marshall-countergambit',
      'falkbeer-countergambit-rubinstein-variation',
      'fishing-pole-trap',
      'four-knights-game-halloween-gambit',
      'four-knights-game-halloween-gambit-oldtimer-variation',
      'four-knights-game-halloween-gambit-plasma-variation',
      'four-knights-game-italian-variation-noa-gambit',
      'four-knights-game-scotch-variation-belgrade-gambit',
      'four-knights-game-scotch-variation-krause-gambit',
      'french-defense-advance-variation-frenkel-gambit',
      'french-defense-advance-variation-milner-barry-gambit',
      'french-defense-advance-variation-milner-barry-gambit-main-line',
      'french-defense-advance-variation-nimzowitsch-gambit',
      'french-defense-advance-variation-ruisdonk-gambit',
      'french-defense-alapin-gambit',
      'french-defense-alekhine-chatard-attack-albin-chatard-gambit',
      'french-defense-baeuerle-gambit',
      'french-defense-banzai-leong-gambit',
      'french-defense-banzai-leong-gambit-pinova-gambit',
      'french-defense-carlson-gambit',
      'french-defense-diemer-duhm-gambit',
      'french-defense-diemer-duhm-gambit-accepted',
      'french-defense-fort-knox-queen-trap',
      'french-defense-horwitz-attack-papa-ticulat-gambit',
      'french-defense-la-bourdonnais-variation-reuter-gambit',
      'french-defense-marshall-gambit',
      'french-defense-mccutcheon-variation-wolf-gambit',
      'french-defense-morphy-gambit',
      'french-defense-orthoschnapp-gambit',
      'french-defense-perseus-gambit',
      'french-defense-rubinstein-variation-ellis-gambit',
      'french-defense-st-george-defense-sanky-george-gambit',
      'french-defense-st-george-defense-st-george-gambit',
      'french-defense-winawer-variation-alekhine-gambit-accepted',
      'french-defense-winawer-variation-alekhine-gambit-kan-variation',
      'french-defense-winawer-variation-alekhine-maroczy-gambit',
      'french-defense-winawer-variation-winckelmann-reimer-gambit',
      'french-defense-wing-gambit',
      'grob-opening-alessi-gambit',
      'grob-opening-double-grob-coca-cola-gambit',
      'grob-opening-grob-gambit',
      'grob-opening-grob-gambit-basman-gambit',
      'grob-opening-grob-gambit-declined',
      'grob-opening-grob-gambit-fritz-gambit',
      'grob-opening-grob-gambit-fritz-gambit-romford-countergambit',
      'grob-opening-grob-gambit-keres-gambit',
      'grob-opening-grob-gambit-richter-grob-gambit',
      'grob-opening-romford-countergambit',
      'grob-opening-zilbermints-gambit',
      'grob-opening-zilbermints-gambit-schiller-defense',
      'grob-opening-zilbermints-gambit-zilbermints-hartlaub-gambit',
      'grunfeld-defense-brinckmann-attack-grunfeld-gambit-accepted',
      'grunfeld-defense-brinckmann-attack-reshevsky-gambit',
      'grunfeld-defense-exchange-variation-seville-variation',
      'grunfeld-defense-gibbon-gambit',
      'gunderam-defense-stader-variation',
      'halosar-trap',
      'hamppe-allgaier-gambit-alapin-variation',
      'hamppe-allgaier-gambit-thorold-variation',
      'horwitz-defense-zilbermints-gambit',
      'hungarian-opening-asten-gambit',
      'hungarian-opening-bucker-gambit',
      'hungarian-opening-burk-gambit',
      'hungarian-opening-pachman-gambit',
      'hungarian-opening-paris-gambit',
      'hungarian-opening-van-kuijk-gambit',
      'hungarian-opening-wiedenhagen-beta-gambit',
      'hungarian-opening-winterberg-gambit',
      'indian-defense-anti-grunfeld-adorjan-gambit',
      'indian-defense-anti-grunfeld-alekhine-variation-leko-gambit',
      'indian-defense-budapest-gambit',
      'indian-defense-budapest-gambit-accepted',
      'indian-defense-budapest-gambit-accepted-fajarowicz-defense',
      'indian-defense-budapest-gambit-accepted-main-line',
      'indian-defense-devin-gambit',
      'indian-defense-gibbins-weidenhagen-gambit',
      'indian-defense-gibbins-weidenhagen-gambit-accepted',
      'indian-defense-gibbins-weidenhagen-gambit-maltese-falcon',
      'indian-defense-gibbins-weidenhagen-gambit-oshima-defense',
      'indian-defense-gibbins-weidenhagen-gambit-stummer-gambit',
      'indian-defense-lazard-gambit',
      'indian-defense-maddigan-gambit',
      'indian-defense-medusa-gambit',
      'indian-defense-omega-gambit',
      'indian-defense-omega-gambit-arafat-gambit',
      'indian-defense-paleface-attack-blackmar-diemer-gambit-deferred',
      'indian-defense-pyrenees-gambit',
      'indian-defense-schnepper-gambit',
      'irish-gambit',
      'italian-game-belloni-trap',
      'italian-game-blackburne-kostic-gambit',
      'italian-game-classical-variation-albin-gambit',
      'italian-game-classical-variation-greco-gambit-dubov-italian',
      'italian-game-classical-variation-greco-gambit-greco-variation',
      'italian-game-classical-variation-greco-gambit-main-line',
      'italian-game-classical-variation-greco-gambit-modern-line',
      'italian-game-classical-variation-greco-gambit-traditional-line',
      'italian-game-deutz-gambit',
      'italian-game-evans-gambit',
      'italian-game-evans-gambit-accepted',
      'italian-game-evans-gambit-alapin-steinitz-variation',
      'italian-game-evans-gambit-anderssen-defense',
      'italian-game-evans-gambit-anderssen-variation',
      'italian-game-evans-gambit-anderssen-variation-cordel-line',
      'italian-game-evans-gambit-bronstein-defense',
      'italian-game-evans-gambit-compromised-defense',
      'italian-game-evans-gambit-compromised-defense-main-line',
      'italian-game-evans-gambit-compromised-defense-potter-variation',
      'italian-game-evans-gambit-declined',
      'italian-game-evans-gambit-declined-cordel-variation',
      'italian-game-evans-gambit-declined-hicken-variation',
      'italian-game-evans-gambit-declined-hirschbach-variation',
      'italian-game-evans-gambit-declined-lange-variation',
      'italian-game-evans-gambit-declined-pavlov-variation',
      'italian-game-evans-gambit-declined-showalter-variation',
      'italian-game-evans-gambit-declined-vasquez-variation',
      'italian-game-evans-gambit-dufresne-defense',
      'italian-game-evans-gambit-fontaine-countergambit',
      'italian-game-evans-gambit-fraser-attack',
      'italian-game-evans-gambit-fraser-mortimer-attack',
      'italian-game-evans-gambit-goring-attack',
      'italian-game-evans-gambit-harding-variation',
      'italian-game-evans-gambit-hein-countergambit',
      'italian-game-evans-gambit-johner-defense',
      'italian-game-evans-gambit-laroche-variation',
      'italian-game-evans-gambit-lasker-defense',
      'italian-game-evans-gambit-leonhardt-countergambit',
      'italian-game-evans-gambit-levenfish-variation',
      'italian-game-evans-gambit-main-line',
      'italian-game-evans-gambit-mayet-defense',
      'italian-game-evans-gambit-mcdonnell-defense',
      'italian-game-evans-gambit-mcdonnell-defense-main-line',
      'italian-game-evans-gambit-mieses-defense',
      'italian-game-evans-gambit-morphy-attack',
      'italian-game-evans-gambit-mortimer-evans-gambit',
      'italian-game-evans-gambit-paulsen-variation',
      'italian-game-evans-gambit-pierce-defense',
      'italian-game-evans-gambit-richardson-attack',
      'italian-game-evans-gambit-sanders-alapin-variation',
      'italian-game-evans-gambit-slow-variation',
      'italian-game-evans-gambit-sokolsky-variation',
      'italian-game-evans-gambit-steinitz-variation',
      'italian-game-evans-gambit-stone-ware-variation',
      'italian-game-evans-gambit-tartakower-attack',
      'italian-game-evans-gambit-ulvestad-variation',
      'italian-game-evans-gambit-waller-attack',
      'italian-game-giuoco-pianissimo-lucchini-gambit',
      'italian-game-jerome-gambit',
      'italian-game-rosentreter-gambit',
      'italian-game-rousseau-gambit',
      'italian-game-scotch-gambit',
      'italian-game-scotch-gambit-anderssen-attack',
      'italian-game-scotch-gambit-anderssen-attack-main-line',
      'italian-game-scotch-gambit-canal-variation',
      'italian-game-scotch-gambit-de-riviere-defense',
      'italian-game-scotch-gambit-double-gambit-accepted',
      'italian-game-scotch-gambit-janowski-defense',
      'italian-game-scotch-gambit-max-lange-attack',
      'italian-game-scotch-gambit-max-lange-attack-accepted',
      'italian-game-scotch-gambit-max-lange-attack-long-variation',
      'italian-game-scotch-gambit-max-lange-attack-spielmann-defense',
      'italian-game-scotch-gambit-nakhmanson-gambit',
      'italian-game-scotch-gambit-walbrodt-baird-gambit',
      'italian-game-two-knights-defense-fried-liver-attack',
      'italian-game-two-knights-defense-fritz-gruber-variation',
      'italian-game-two-knights-defense-fritz-variation',
      'italian-game-two-knights-defense-kloss-gambit',
      'italian-game-two-knights-defense-lolli-attack',
      'italian-game-two-knights-defense-polerio-defense',
      'italian-game-two-knights-defense-polerio-defense-suhle-defense',
      'italian-game-two-knights-defense-ponziani-steinitz-gambit',
      'italian-game-two-knights-defense-traxler-counterattack',
      'italian-game-two-knights-defense-ulvestad-variation',
      'kadas-opening-kadas-gambit',
      'kadas-opening-schneider-gambit',
      'kadas-opening-steinbok-gambit',
      'kieninger-trap',
      'kieseritzky-gambit-berlin-defense-de-riviere-variation',
      'kieseritzky-gambit-berlin-defense-rubinstein-variation',
      'kieseritzky-gambit-brentano-defense-caro-variation',
      'kieseritzky-gambit-paulsen-defense-deferred',
      'kieseritzky-long-whip-defense-jaenisch-variation',
      'kings-gambit',
      'kings-gambit-accepted',
      'kings-gambit-accepted-abbazia-defense',
      'kings-gambit-accepted-abbazia-defense-main-line',
      'kings-gambit-accepted-allgaier-blackburne-gambit',
      'kings-gambit-accepted-allgaier-cook-variation',
      'kings-gambit-accepted-allgaier-gambit',
      'kings-gambit-accepted-allgaier-gambit-thorold-attack',
      'kings-gambit-accepted-allgaier-gambit-urusov-attack',
      'kings-gambit-accepted-allgaier-horny-defense',
      'kings-gambit-accepted-allgaier-schlechter-defense',
      'kings-gambit-accepted-allgaier-urusov-attack',
      'kings-gambit-accepted-australian-gambit',
      'kings-gambit-accepted-basman-gambit',
      'kings-gambit-accepted-becker-defense',
      'kings-gambit-accepted-bishops-gambit',
      'kings-gambit-accepted-bishops-gambit-anderssen-defense',
      'kings-gambit-accepted-bishops-gambit-anderssen-variation',
      'kings-gambit-accepted-bishops-gambit-bledow-countergambit',
      'kings-gambit-accepted-bishops-gambit-bledow-variation',
      'kings-gambit-accepted-bishops-gambit-boden-variation',
      'kings-gambit-accepted-bishops-gambit-bogoljubow-defense',
      'kings-gambit-accepted-bishops-gambit-bogoljubow-variation',
      'kings-gambit-accepted-bishops-gambit-boren-svenonius-variation',
      'kings-gambit-accepted-bishops-gambit-bryan-countergambit',
      'kings-gambit-accepted-bishops-gambit-chigorins-attack',
      'kings-gambit-accepted-bishops-gambit-classical-defense',
      'kings-gambit-accepted-bishops-gambit-cozio-defense',
      'kings-gambit-accepted-bishops-gambit-cozio-variation',
      'kings-gambit-accepted-bishops-gambit-first-jaenisch-variation',
      'kings-gambit-accepted-bishops-gambit-fraser-variation',
      'kings-gambit-accepted-bishops-gambit-gianutio-gambit',
      'kings-gambit-accepted-bishops-gambit-greco-variation',
      'kings-gambit-accepted-bishops-gambit-grimm-attack',
      'kings-gambit-accepted-bishops-gambit-kieseritzky-gambit',
      'kings-gambit-accepted-bishops-gambit-lopez-defense',
      'kings-gambit-accepted-bishops-gambit-lopez-variation',
      'kings-gambit-accepted-bishops-gambit-maurian-defense',
      'kings-gambit-accepted-bishops-gambit-mcdonnell-attack',
      'kings-gambit-accepted-bishops-gambit-paulsen-attack',
      'kings-gambit-accepted-bishops-gambit-steinitz-defense',
      'kings-gambit-accepted-blachly-gambit',
      'kings-gambit-accepted-bonsch-osmolovsky-variation',
      'kings-gambit-accepted-breyer-gambit',
      'kings-gambit-accepted-carrera-gambit',
      'kings-gambit-accepted-cunningham-defense',
      'kings-gambit-accepted-cunningham-defense-bertin-gambit',
      'kings-gambit-accepted-cunningham-defense-mccormick-defense',
      'kings-gambit-accepted-dodo-variation',
      'kings-gambit-accepted-double-muzio-gambit',
      'kings-gambit-accepted-double-muzio-gambit-baldwin-gambit',
      'kings-gambit-accepted-double-muzio-gambit-bello-gambit',
      'kings-gambit-accepted-double-muzio-gambit-paulsen-defense',
      'kings-gambit-accepted-double-muzio-gambit-young-gambit',
      'kings-gambit-accepted-eisenberg-variation',
      'kings-gambit-accepted-fischer-defense',
      'kings-gambit-accepted-fischer-defense-schulder-gambit',
      'kings-gambit-accepted-fischer-defense-spanish-variation',
      'kings-gambit-accepted-gaga-gambit',
      'kings-gambit-accepted-ghulam-kassim-gambit',
      'kings-gambit-accepted-gianutio-countergambit',
      'kings-gambit-accepted-greco-gambit',
      'kings-gambit-accepted-hanstein-gambit',
      'kings-gambit-accepted-kieseritzky-gambit',
      'kings-gambit-accepted-kieseritzky-gambit-anderssen-cordel-gambit',
      'kings-gambit-accepted-kieseritzky-gambit-anderssen-defense',
      'kings-gambit-accepted-kieseritzky-gambit-berlin-defense',
      'kings-gambit-accepted-kieseritzky-gambit-brentano-defense',
      'kings-gambit-accepted-kieseritzky-gambit-cotter-gambit',
      'kings-gambit-accepted-kieseritzky-gambit-kolisch-defense',
      'kings-gambit-accepted-kieseritzky-gambit-long-whip',
      'kings-gambit-accepted-kieseritzky-gambit-neumann-defense',
      'kings-gambit-accepted-kieseritzky-gambit-paulsen-defense',
      'kings-gambit-accepted-kieseritzky-gambit-rice-gambit',
      'kings-gambit-accepted-kieseritzky-gambit-rosenthal-defense',
      'kings-gambit-accepted-kieseritzky-polerio-defense',
      'kings-gambit-accepted-kieseritzky-rice-gambit',
      'kings-gambit-accepted-kieseritzky-salvio-defense-cozio-variation',
      'kings-gambit-accepted-kings-knights-gambit',
      'kings-gambit-accepted-kotov-gambit',
      'kings-gambit-accepted-lolli-gambit',
      'kings-gambit-accepted-lolli-gambit-young-variation',
      'kings-gambit-accepted-macleod-defense',
      'kings-gambit-accepted-mason-keres-gambit',
      'kings-gambit-accepted-mayet-gambit',
      'kings-gambit-accepted-mcdonnell-gambit',
      'kings-gambit-accepted-middleton-countergambit',
      'kings-gambit-accepted-modern-defense',
      'kings-gambit-accepted-muzio-gambit-accepted-froms-defense',
      'kings-gambit-accepted-muzio-gambit-brentano-defense',
      'kings-gambit-accepted-muzio-gambit-holloway-defense',
      'kings-gambit-accepted-muzio-gambit-sarratt-defense',
      'kings-gambit-accepted-muzio-gambit-wild-muzio-gambit',
      'kings-gambit-accepted-orsini-gambit',
      'kings-gambit-accepted-paris-gambit',
      'kings-gambit-accepted-philidor-gambit',
      'kings-gambit-accepted-philidor-gambit-schultz-variation',
      'kings-gambit-accepted-quaade-gambit',
      'kings-gambit-accepted-rosentreter-gambit',
      'kings-gambit-accepted-rosentreter-gambit-bird-gambit',
      'kings-gambit-accepted-rosentreter-gambit-sorensen-gambit',
      'kings-gambit-accepted-rosentreter-gambit-testa-variation',
      'kings-gambit-accepted-salvio-gambit',
      'kings-gambit-accepted-salvio-gambit-anderssen-counterattack',
      'kings-gambit-accepted-salvio-gambit-cochrane-gambit',
      'kings-gambit-accepted-salvio-gambit-santa-maria-defense',
      'kings-gambit-accepted-salvio-gambit-silberschmidt-defense',
      'kings-gambit-accepted-salvio-gambit-viennese-variation',
      'kings-gambit-accepted-schallopp-defense',
      'kings-gambit-accepted-schallopp-defense-tashkent-attack',
      'kings-gambit-accepted-schurig-gambit-with-bb5',
      'kings-gambit-accepted-schurig-gambit-with-bd3',
      'kings-gambit-accepted-silberschmidt-gambit',
      'kings-gambit-accepted-sorensen-gambit',
      'kings-gambit-accepted-stamma-gambit',
      'kings-gambit-accepted-tartakower-gambit',
      'kings-gambit-accepted-tartakower-gambit-weiss-defense',
      'kings-gambit-accepted-traditional-variation',
      'kings-gambit-accepted-tumbleweed',
      'kings-gambit-accepted-villemson-gambit',
      'kings-gambit-accepted-wagenbach-defense',
      'kings-gambit-declined-classical-hanham-variation',
      'kings-gambit-declined-classical-reti-variation',
      'kings-gambit-declined-classical-soldatenkov-variation',
      'kings-gambit-declined-classical-svenonius-variation',
      'kings-gambit-declined-classical-variation',
      'kings-gambit-declined-classical-variation-euwe-attack',
      'kings-gambit-declined-classical-variation-rotlewi-countergambit',
      'kings-gambit-declined-classical-variation-walthoffen-attack',
      'kings-gambit-declined-falkbeer-countergambit',
      'kings-gambit-declined-falkbeer-countergambit-accepted',
      'kings-gambit-declined-falkbeer-countergambit-alapin-variation',
      'kings-gambit-declined-falkbeer-countergambit-anderssen-attack',
      'kings-gambit-declined-falkbeer-countergambit-blackburne-attack',
      'kings-gambit-declined-falkbeer-countergambit-charousek-gambit',
      'kings-gambit-declined-falkbeer-countergambit-charousek-variation',
      'kings-gambit-declined-falkbeer-countergambit-hinrichsen-gambit',
      'kings-gambit-declined-falkbeer-countergambit-miles-gambit',
      'kings-gambit-declined-falkbeer-countergambit-modern-transfer',
      'kings-gambit-declined-falkbeer-countergambit-pickler-gambit',
      'kings-gambit-declined-falkbeer-countergambit-staunton-line',
      'kings-gambit-declined-falkbeer-countergambit-tarrasch-variation',
      'kings-gambit-declined-hobbs-zilbermints-gambit',
      'kings-gambit-declined-keene-defense',
      'kings-gambit-declined-keenes-defense',
      'kings-gambit-declined-mafia-defense',
      'kings-gambit-declined-miles-defense',
      'kings-gambit-declined-norwalde-variation',
      'kings-gambit-declined-norwalde-variation-bucker-gambit',
      'kings-gambit-declined-norwalde-variation-schubert-variation',
      'kings-gambit-declined-panteldakis-countergambit',
      'kings-gambit-declined-panteldakis-countergambit-greco-variation',
      'kings-gambit-declined-panteldakis-countergambit-shirazi-line',
      'kings-gambit-declined-petrovs-defense',
      'kings-gambit-declined-queens-knight-defense',
      'kings-gambit-declined-senechaud-countergambit',
      'kings-gambit-declined-soller-zilbermints-gambit',
      'kings-gambit-declined-zilbermints-double-countergambit',
      'kings-gambit-declined-zilbermints-double-gambit',
      'kings-indian-attack-omega-delta-gambit',
      'kings-indian-defense-four-pawns-attack-florentine-gambit',
      'kings-indian-defense-samisch-variation-samisch-gambit',
      'kings-indian-defense-samisch-variation-samisch-gambit-accepted',
      'kings-pawn-game-bavarian-gambit',
      'kings-pawn-game-beyer-gambit',
      'kings-pawn-game-busch-gass-gambit',
      'kings-pawn-game-busch-gass-gambit-chiodini-gambit',
      'kings-pawn-game-clam-variation-kings-gambit-reversed',
      'kings-pawn-game-clam-variation-radisch-gambit',
      'kings-pawn-game-gunderam-defense-gunderam-gambit',
      'kings-pawn-game-gunderam-gambit',
      'kings-pawn-game-la-bourdonnais-gambit',
      'kings-pawn-game-macleod-attack-lasa-gambit',
      'kings-pawn-game-macleod-attack-norwalde-gambit',
      'kings-pawn-game-pachman-wing-gambit',
      'kings-pawn-game-philidor-gambit',
      'kings-pawn-game-schulze-muller-gambit',
      'kings-pawn-game-tayler-opening-basman-gambit',
      'kings-pawn-game-wayward-queen-attack-kiddie-countergambit',
      'kings-pawn-game-wayward-queen-attack-mellon-gambit',
      'kings-pawn-game-weber-gambit',
      'kings-pawn-opening-van-hooydoon-gambit',
      'lasker-pelikan-variation-sveshnikov-variation-peresypkins',
      'lasker-trap',
      'latvian-gambit',
      'latvian-gambit-accepted',
      'latvian-gambit-accepted-bilguer-variation',
      'latvian-gambit-accepted-bronstein-attack',
      'latvian-gambit-accepted-bronstein-gambit',
      'latvian-gambit-accepted-foltys-leonhardt-variation',
      'latvian-gambit-accepted-foltys-variation',
      'latvian-gambit-accepted-leonhardt-variation',
      'latvian-gambit-accepted-main-line',
      'latvian-gambit-accepted-nimzowitsch-attack',
      'latvian-gambit-behting-variation',
      'latvian-gambit-clam-gambit',
      'latvian-gambit-corkscrew-countergambit',
      'latvian-gambit-corkscrew-gambit',
      'latvian-gambit-diepstraten-countergambit',
      'latvian-gambit-fraser-defense',
      'latvian-gambit-greco-variation',
      'latvian-gambit-lobster-gambit',
      'latvian-gambit-mason-countergambit',
      'latvian-gambit-mayet-attack',
      'latvian-gambit-mayet-attack-morgado-defense',
      'latvian-gambit-mayet-attack-poisoned-pawn-variation',
      'latvian-gambit-mayet-attack-polerio-svedenborg-variation',
      'latvian-gambit-mayet-attack-strautins-gambit',
      'latvian-gambit-mlotkowski-variation',
      'latvian-gambit-senechaud-gambit',
      'legals-mate',
      'lion-defense-anti-philidor-lions-cave-lion-claw-gambit',
      'lopez-gianutio-countergambit-hein-variation',
      'magnus-smith-trap',
      'mexican-defense-horsefly-gambit',
      'mikenas-defense-pozarek-gambit',
      'milner-barry-trap',
      'modern-defense-bishop-attack-bucker-gambit',
      'modern-defense-lizard-defense-mittenberger-gambit',
      'modern-defense-lizard-defense-pirc-diemer-gambit',
      'modern-defense-masur-gambit',
      'modern-defense-norwegian-defense-norwegian-gambit',
      'modern-defense-westermann-gambit',
      'modern-defense-wind-gambit',
      'monticelli-trap',
      'morphy-defense-schliemann-defense-deferred-jaenisch-gambit',
      'mortimer-trap',
      'muzio-gambit-kling-and-horwitz-counterattack',
      'nimzo-indian-defense-classical-variation-belyavsky-gambit',
      'nimzo-indian-defense-classical-variation-romanishin-gambit',
      'nimzo-indian-defense-classical-variation-vitolins-adorjan-gambit',
      'nimzo-indian-defense-dilworth-gambit',
      'nimzo-indian-defense-leningrad-variation-averbakh-gambit',
      'nimzo-indian-defense-spielmann-variation-romanovsky-gambit',
      'nimzo-indian-defense-three-knights-variation-shocron-gambit',
      'nimzo-larsen-attack-norfolk-gambit',
      'nimzo-larsen-attack-pachman-gambit',
      'nimzo-larsen-attack-ringelbach-gambit',
      'nimzowitsch-defense-colorado-countergambit',
      'nimzowitsch-defense-colorado-countergambit-accepted',
      'nimzowitsch-defense-el-columpio-defense-el-columpio-gambit',
      'nimzowitsch-defense-hornung-gambit',
      'nimzowitsch-defense-kennedy-variation-bielefelder-gambit',
      'nimzowitsch-defense-kennedy-variation-de-smet-gambit',
      'nimzowitsch-defense-kennedy-variation-hammer-gambit',
      'nimzowitsch-defense-kennedy-variation-herford-gambit',
      'nimzowitsch-defense-scandinavian-variation-aachen-gambit',
      'nimzowitsch-defense-wheeler-gambit',
      'noahs-ark-trap',
      'nyezhmetdinov-rossolimo-attack-fianchetto-variation-gufeld',
      'nyezhmetdinov-rossolimo-attack-fianchetto-variation-lutikov',
      'nyezhmetdinov-rossolimo-attack-san-francisco-gambit',
      'old-indian-defense-aged-gibbon-gambit',
      'old-indian-defense-janowski-variation-grinberg-gambit',
      'orthodox-variation-classical-system-kozul-gambit',
      'owen-defense-hekili-loa-gambit',
      'owen-defense-matovinsky-gambit',
      'owen-defense-naselwaus-gambit',
      'owen-defense-smith-gambit',
      'owen-defense-wind-gambit',
      'panov-attack-fianchetto-defense-fianchetto-gambit',
      'panteldakis-countergambit-pawn-sacrifice-line',
      'panteldakis-countergambit-schillers-defense',
      'panteldakis-countergambit-symmetrical-variation',
      'petrovs-defense-classical-attack-marshall-trap',
      'petrovs-defense-cochrane-gambit',
      'petrovs-defense-cochrane-gambit-bishop-check-line',
      'petrovs-defense-cochrane-gambit-center-variation',
      'petrovs-defense-damiano-variation-kholmov-gambit',
      'petrovs-defense-marshall-trap',
      'petrovs-defense-modern-attack-tal-gambit',
      'petrovs-defense-moody-gambit',
      'petrovs-defense-stafford-gambit',
      'petrovs-defense-stafford-gambit-accepted',
      'philidor-defense-albin-blackburne-gambit',
      'philidor-defense-bird-gambit',
      'philidor-defense-lion-variation-bishop-sacrifice',
      'philidor-defense-lion-variation-delayed-bishop-sacrifice',
      'philidor-defense-lion-variation-forcing-line',
      'philidor-defense-lion-variation-shirov-gambit',
      'philidor-defense-lopez-countergambit',
      'philidor-defense-lopez-countergambit-jaenisch-variation',
      'philidor-defense-morphy-gambit',
      'philidor-defense-philidor-countergambit',
      'philidor-defense-philidor-countergambit-berger-variation',
      'philidor-defense-philidor-countergambit-del-rio-attack',
      'philidor-defense-philidor-countergambit-zukertort-variation',
      'philidor-defense-philidor-gambit',
      'pirc-defense-roscher-gambit',
      'polish-defense-spassky-gambit-accepted',
      'polish-opening-birmingham-gambit',
      'polish-opening-outflank-variation-schuehler-gambit',
      'polish-opening-schuehler-gambit',
      'polish-opening-tartakower-gambit',
      'ponziani-opening-caro-gambit',
      'ponziani-opening-flagship-trap',
      'ponziani-opening-neumann-gambit',
      'ponziani-opening-ponziani-countergambit',
      'ponziani-opening-ponziani-countergambit-schmidt-attack',
      'ponziani-opening-vukovic-gambit',
      'portuguese-gambit-melbourne-shuffle-variation',
      'portuguese-opening-miguel-gambit',
      'portuguese-opening-portuguese-gambit',
      'queens-gambit-accepted-old-variation-b5-trap',
      'queens-gambit-declined-albin-countergambit',
      'queens-gambit-declined-albin-countergambit-balogh-variation',
      'queens-gambit-declined-albin-countergambit-fianchetto-variation',
      'queens-gambit-declined-albin-countergambit-janowski-variation',
      'queens-gambit-declined-albin-countergambit-krenosz-variation',
      'queens-gambit-declined-albin-countergambit-modern-line',
      'queens-gambit-declined-albin-countergambit-normal-line',
      'queens-gambit-declined-albin-countergambit-spassky-variation',
      'queens-gambit-declined-albin-countergambit-tartakower-defense',
      'queens-gambit-declined-orthodox-rubinstein-trap',
      'queens-indian-defense-classical-variation-polugaevsky-gambit',
      'queens-indian-defense-classical-variation-taimanov-gambit',
      'queens-indian-defense-queen-amidala-trap',
      'queens-pawn-game-chandler-gambit',
      'queens-pawn-game-chigorin-variation-irish-gambit',
      'queens-pawn-game-chigorin-variation-shaviliuk-gambit',
      'queens-pawn-game-hubsch-gambit',
      'queens-pawn-game-liedmann-gambit',
      'queens-pawn-game-zilbermints-countergambit',
      'queens-pawn-game-zurich-gambit',
      'rat-defense-english-rat-lisbon-gambit',
      'rat-defense-english-rat-pounds-gambit',
      'rat-defense-fuller-gambit',
      'reti-opening-advance-variation-michel-gambit',
      'reti-opening-advance-variation-navara-gambit',
      'reti-opening-reversed-blumenfeld-gambit',
      'reti-opening-zaitsik-zichulidze-trap',
      'reti-opening-zilbermints-gambit',
      'reversed-brooklyn-defense-brooklyn-benko-gambit',
      'richter-veresov-attack-malich-gambit',
      'rubinstein-trap',
      'ruy-lopez-alapin-defense-alapin-gambit',
      'ruy-lopez-berlin-defense-rio-gambit-accepted',
      'ruy-lopez-berlin-defense-tarrasch-trap',
      'ruy-lopez-central-countergambit',
      'ruy-lopez-classical-variation-cordel-gambit',
      'ruy-lopez-classical-variation-konikowski-gambit',
      'ruy-lopez-classical-variation-spanish-wing-gambit',
      'ruy-lopez-classical-variation-zukertort-gambit',
      'ruy-lopez-closed-alekhine-gambit',
      'ruy-lopez-closed-basque-gambit',
      'ruy-lopez-closed-center-attack-basque-gambit',
      'ruy-lopez-closed-chigorin-defense-gajewski-gambit',
      'ruy-lopez-exchange-variation-alapin-gambit',
      'ruy-lopez-halloween-attack',
      'ruy-lopez-marshall-attack',
      'ruy-lopez-marshall-attack-main-line',
      'ruy-lopez-marshall-attack-main-line-spassky-variation',
      'ruy-lopez-marshall-attack-modern-main-line',
      'ruy-lopez-marshall-attack-modern-variation',
      'ruy-lopez-marshall-attack-original-marshall-attack',
      'ruy-lopez-marshall-attack-re3-variation',
      'ruy-lopez-marshall-attack-steiner-variation',
      'ruy-lopez-morphy-defense-jaffe-gambit',
      'ruy-lopez-morphy-defense-norwegian-variation-nightingale-gambit',
      'ruy-lopez-morphy-defense-schliemann-defense-deferred',
      'ruy-lopez-open-harksen-gambit',
      'ruy-lopez-open-karpov-gambit',
      'ruy-lopez-open-skipworth-gambit',
      'ruy-lopez-schliemann-defense',
      'ruy-lopez-schliemann-defense-classical-variation',
      'ruy-lopez-schliemann-defense-dyckhoff-variation',
      'ruy-lopez-schliemann-defense-exchange-variation',
      'ruy-lopez-schliemann-defense-jaenisch-gambit-accepted',
      'ruy-lopez-schliemann-defense-kostic-defense',
      'ruy-lopez-schliemann-defense-mohring-variation',
      'ruy-lopez-schliemann-defense-schonemann-attack',
      'ruy-lopez-schliemann-defense-tartakower-variation',
      'ruy-lopez-spanish-countergambit',
      'ruy-lopez-spanish-countergambit-harding-gambit',
      'ruy-lopez-steinitz-defense-center-gambit',
      'scandinavian-defense-balode-sondore-trap',
      'scandinavian-defense-blackburne-gambit',
      'scandinavian-defense-blackburne-kloosterboer-gambit',
      'scandinavian-defense-boehnke-gambit',
      'scandinavian-defense-icelandic-palme-gambit',
      'scandinavian-defense-kadas-gambit',
      'scandinavian-defense-kiel-variation-trap',
      'scandinavian-defense-kloosterboer-gambit',
      'scandinavian-defense-main-line-leonhardt-gambit',
      'scandinavian-defense-modern-variation-wing-gambit',
      'scandinavian-defense-portuguese-gambit',
      'scandinavian-defense-portuguese-gambit-banker-variation',
      'scandinavian-defense-portuguese-gambit-classical-variation',
      'scandinavian-defense-portuguese-gambit-correspondence-refutation',
      'scandinavian-defense-portuguese-gambit-elbow-variation',
      'scandinavian-defense-portuguese-gambit-jadoul-variation',
      'scandinavian-defense-portuguese-gambit-lusophobe-variation',
      'scandinavian-defense-portuguese-gambit-wuss-variation',
      'scandinavian-defense-zilbermints-gambit',
      'scandinavian-variation-bogoljubow-variation-brandics-gambit',
      'scandinavian-variation-bogoljubow-variation-erben-gambit',
      'scandinavian-variation-bogoljubow-variation-heinola-deppe-gambit',
      'scandinavian-variation-bogoljubow-variation-nimzowitsch-gambit',
      'scandinavian-variation-bogoljubow-variation-richter-gambit',
      'scandinavian-variation-exchange-variation-marshall-gambit',
      'scheveningen-variation-delayed-keres-attack-perenyi-gambit',
      'scholars-mate',
      'scotch-game-alekhine-gambit',
      'scotch-game-goring-gambit',
      'scotch-game-goring-gambit-bardeleben-variation',
      'scotch-game-goring-gambit-double-pawn-sacrifice',
      'scotch-game-goring-gambit-main-line',
      'scotch-game-haxo-gambit',
      'scotch-game-napoleon-gambit',
      'scotch-game-relfsson-gambit',
      'scotch-game-scotch-gambit',
      'scotch-game-scotch-gambit-advance-variation',
      'scotch-game-scotch-gambit-cochrane-anderssen-variation',
      'scotch-game-scotch-gambit-dubois-reti-defense',
      'scotch-game-scotch-gambit-goring-gambit-declined',
      'scotch-game-scotch-gambit-kingside-variation',
      'scotch-game-scotch-gambit-london-defense',
      'scotch-game-scotch-gambit-sarratt-variation',
      'scotch-variation-belgrade-gambit-modern-defense',
      'scotch-variation-krause-gambit-leonhardt-defense',
      'semi-slav-defense-anti-moscow-gambit',
      'semi-slav-defense-gunderam-gambit',
      'semi-slav-defense-marshall-gambit',
      'semi-slav-defense-marshall-gambit-forgotten-variation',
      'semi-slav-defense-marshall-gambit-main-line',
      'semi-slav-defense-marshall-gambit-tolush-variation',
      'semi-slav-defense-noteboom-variation-anti-noteboom-gambit',
      'siberian-trap',
      'sicilian-defense-alapin-variation-anti-alapin-gambit',
      'sicilian-defense-bobby-fischer-trap',
      'sicilian-defense-brussels-gambit',
      'sicilian-defense-coles-sicilian-gambit',
      'sicilian-defense-delayed-alapin-variation-basman-palatnik-gambit',
      'sicilian-defense-double-dutch-gambit',
      'sicilian-defense-dragon-variation-bb5-trap',
      'sicilian-defense-euwe-attack-prins-gambit',
      'sicilian-defense-halasz-gambit',
      'sicilian-defense-kotov-gambit',
      'sicilian-defense-kronberger-variation-nemeth-gambit',
      'sicilian-defense-mcdonnell-attack-tal-gambit',
      'sicilian-defense-modern-variations-ginsberg-gambit',
      'sicilian-defense-morphy-gambit',
      'sicilian-defense-morphy-gambit-andreaschek-gambit',
      'sicilian-defense-moscow-variation-haag-gambit',
      'sicilian-defense-moscow-variation-moscow-gambit',
      'sicilian-defense-najdorf-variation-dekker-gambit',
      'sicilian-defense-najdorf-variation-poisoned-pawn-accepted',
      'sicilian-defense-najdorf-variation-poisoned-pawn-variation',
      'sicilian-defense-okelly-variation-normal-system-cortlever-gambit',
      'sicilian-defense-okelly-variation-venice-system-gambit-line',
      'sicilian-defense-okelly-variation-wing-gambit',
      'sicilian-defense-polish-gambit',
      'sicilian-defense-portsmouth-gambit',
      'sicilian-defense-smith-morra-gambit',
      'sicilian-defense-smith-morra-gambit-accepted',
      'sicilian-defense-smith-morra-gambit-accepted-chicago-defense',
      'sicilian-defense-smith-morra-gambit-accepted-classical-formation',
      'sicilian-defense-smith-morra-gambit-accepted-danish-variation',
      'sicilian-defense-smith-morra-gambit-accepted-fianchetto-defense',
      'sicilian-defense-smith-morra-gambit-accepted-finegold-defense',
      'sicilian-defense-smith-morra-gambit-accepted-kan-formation',
      'sicilian-defense-smith-morra-gambit-accepted-larsen-defense',
      'sicilian-defense-smith-morra-gambit-accepted-morphy-defense',
      'sicilian-defense-smith-morra-gambit-accepted-paulsen-formation',
      'sicilian-defense-smith-morra-gambit-accepted-pin-defense',
      'sicilian-defense-smith-morra-gambit-accepted-siberian-variation',
      'sicilian-defense-smith-morra-gambit-accepted-sozin-formation',
      'sicilian-defense-smith-morra-gambit-accepted-taimanov-formation',
      'sicilian-defense-smith-morra-gambit-declined-alapin-formation',
      'sicilian-defense-smith-morra-gambit-declined-center-formation',
      'sicilian-defense-smith-morra-gambit-declined-dubois-variation',
      'sicilian-defense-smith-morra-gambit-declined-push-variation',
      'sicilian-defense-smith-morra-gambit-declined-wing-formation',
      'sicilian-defense-smith-morra-gambit-deferred',
      'sicilian-defense-taimanov-variation-gary-gambit',
      'sicilian-defense-wing-gambit',
      'sicilian-defense-wing-gambit-abrahams-variation',
      'sicilian-defense-wing-gambit-carlsbad-variation',
      'sicilian-defense-wing-gambit-deferred',
      'sicilian-defense-wing-gambit-deferred-variation',
      'sicilian-defense-wing-gambit-marienbad-variation',
      'sicilian-defense-wing-gambit-marshall-variation',
      'sicilian-defense-wing-gambit-nanu-gambit',
      'sicilian-defense-wing-gambit-romanian-defense',
      'sicilian-defense-wing-gambit-santasiere-variation',
      'slav-defense-czech-variation-krause-attack-fazekas-gambit',
      'slav-defense-diemer-gambit',
      'slav-defense-geller-gambit',
      'slav-defense-slav-gambit-alekhine-attack',
      'slav-defense-winawer-countergambit',
      'slav-defense-winawer-countergambit-anti-winawer-gambit',
      'smith-morra-gambit-accepted-morphy-defense-deferred',
      'smith-morra-gambit-accepted-open-d-file-trap',
      'smith-morra-gambit-accepted-scheveningen-formation',
      'smith-morra-gambit-declined-scandinavian-formation',
      'sodium-attack-durkin-gambit',
      'spanish-countergambit-harding-countergambit-fricke-gambit',
      'spanish-variation-harrwitz-attack-nikitin-gambit',
      'spanish-variation-rubinstein-variation-marshall-gambit',
      'st-george-defense-zilbermints-gambit',
      'stafford-gambit-rosen-trap',
      'steinitz-gambit-fraser-minckwitz-defense',
      'steinitz-gambit-paulsen-defense',
      'steinitz-gambit-sorensen-defense',
      'steinitz-gambit-zukertort-defense',
      'taimanov-variation-bastrikov-variation-ponomariov-gambit',
      'tarrasch-defense-classical-variation-classical-tarrasch-gambit',
      'tarrasch-defense-grunfeld-gambit',
      'tarrasch-defense-schara-gambit',
      'tarrasch-defense-tarrasch-gambit',
      'tarrasch-defense-von-hennig-gambit',
      'tarrasch-trap',
      'tarrasch-variation-open-system-shaposhnikov-gambit',
      'teichmann-defense-ciesielski-variation',
      'teichmann-defense-classical-variation',
      'teichmann-defense-seidel-hall-attack',
      'torre-attack-classical-defense-petrosian-gambit',
      'torre-attack-wagner-gambit',
      'traxler-counterattack-ke2-trap',
      'trompowsky-attack-edge-variation-hergert-gambit',
      'trompowsky-attack-raptor-variation-hergert-gambit',
      'two-knights-defense-polerio-defense-bishop-check-line',
      'two-knights-defense-polerio-defense-bogoljubow-variation',
      'two-knights-defense-polerio-defense-goring-variation',
      'two-knights-defense-polerio-defense-kieseritzky-variation',
      'two-knights-defense-polerio-defense-yankovich-variation',
      'two-knights-defense-traxler-counterattack-bishop-sacrifice-line',
      'two-knights-defense-traxler-counterattack-king-march-line',
      'two-knights-defense-traxler-counterattack-knight-sacrifice-line',
      'two-knights-defense-traxler-variation-trencianske-teplice-gambit',
      'two-knights-defense-ulvestad-variation-kurkin-gambit',
      'two-knights-variation-suttles-variation-tal-gambit',
      'van-geet-opening-berlin-gambit',
      'van-geet-opening-billockus-johansen-gambit',
      'van-geet-opening-dougherty-gambit',
      'van-geet-opening-dunst-perrenet-gambit',
      'van-geet-opening-dusseldorf-gambit',
      'van-geet-opening-gladbacher-gambit',
      'van-geet-opening-grunfeld-defense-steiner-gambit',
      'van-geet-opening-hector-gambit',
      'van-geet-opening-hergert-gambit',
      'van-geet-opening-hulsemann-gambit',
      'van-geet-opening-jendrossek-gambit',
      'van-geet-opening-kluever-gambit',
      'van-geet-opening-laroche-gambit',
      'van-geet-opening-liebig-gambit',
      'van-geet-opening-melleby-gambit',
      'van-geet-opening-nowokunski-gambit',
      'van-geet-opening-pfeiffer-gambit',
      'van-geet-opening-pfeiffer-gambit-sleipnir-countergambit',
      'van-geet-opening-sleipnir-gambit',
      'van-geet-opening-tubingen-gambit',
      'van-geet-opening-warsteiner-gambit',
      'vant-kruijs-opening-keoni-hiva-gambit-akahi-variation',
      'vant-kruijs-opening-keoni-hiva-gambit-alua-variation',
      'vant-kruijs-opening-keoni-hiva-gambit-ekolu-variation',
      'vienna-gambit-with-max-lange-defense',
      'vienna-gambit-with-max-lange-defense-cunningham-defense',
      'vienna-gambit-with-max-lange-defense-hamppe-allgaier-gambit',
      'vienna-gambit-with-max-lange-defense-hamppe-muzio-gambit',
      'vienna-gambit-with-max-lange-defense-knight-variation',
      'vienna-gambit-with-max-lange-defense-pierce-gambit',
      'vienna-gambit-with-max-lange-defense-quelle-gambit',
      'vienna-gambit-with-max-lange-defense-steinitz-gambit',
      'vienna-gambit-with-max-lange-defense-steinitz-gambit-main-line',
      'vienna-game-adams-gambit',
      'vienna-game-frankenstein-dracula-qd5-trap',
      'vienna-game-frankenstein-dracula-variation',
      'vienna-game-fyfe-gambit',
      'vienna-game-hamppe-muzio-gambit',
      'vienna-game-mieses-variation-erben-gambit',
      'vienna-game-omaha-gambit',
      'vienna-game-paulsen-variation-mariotti-gambit',
      'vienna-game-paulsen-variation-pollock-gambit',
      'vienna-game-philidor-countergambit',
      'vienna-game-pierce-gambit-rushmere-attack',
      'vienna-game-stanley-variation-bronstein-gambit',
      'vienna-game-stanley-variation-eifel-gambit',
      'vienna-game-stanley-variation-meitner-mieses-gambit',
      'vienna-game-vienna-gambit',
      'vienna-game-vienna-gambit-bardeleben-variation',
      'vienna-game-vienna-gambit-breyer-variation',
      'vienna-game-vienna-gambit-kaufmann-variation',
      'vienna-game-vienna-gambit-main-line',
      'vienna-game-vienna-gambit-modern-variation',
      'vienna-game-vienna-gambit-paulsen-attack',
      'vienna-game-vienna-gambit-steinitz-variation',
      'vienna-game-wurzburger-trap',
      'vienna-game-zhuravlev-countergambit',
      'ware-opening-cologne-gambit',
      'ware-opening-ware-gambit',
      'ware-opening-wing-gambit',
      'winawer-variation-alekhine-gambit-alatortsev-variation',
      'zukertort-opening-herrstrom-gambit',
      'zukertort-opening-lemberger-gambit',
      'zukertort-opening-lisitsyn-gambit',
      'zukertort-opening-lisitsyn-gambit-deferred',
      'zukertort-opening-pachman-gambit',
      'zukertort-opening-regina-nu-gambit',
      'zukertort-opening-ross-gambit',
      'zukertort-opening-shabalov-gambit',
      'zukertort-opening-speelsmet-gambit',
      'zukertort-opening-tennison-gambit',
      'zukertort-opening-tennison-gambit-briggs-trap',
      'zukertort-opening-vos-gambit',
    ])
  })

  for (const entry of taught) {
    test(`${entry.name} — ${entry.leaves.length} lines`, async ({ page }) => {
      // Clicking one leaf at a time from the entry root, so the budget is the number of
      // navigations rather than the default single-interaction one.
      test.setTimeout(120_000)

      /*
       * The default catalogue view is the taught tier, and a narrowed view under the
       * auto-expand limit opens its families — which covered every taught entry
       * unnarrowed through issue #103's batch, but the taught tier itself passed
       * `autoExpandLimit` (100, `filter.ts`) once #109 brought it to one hundred and
       * five, and again once #110's own search-by-name fix turned out to need
       * search-by-ECO instead (a name is translated to Vietnamese on this page —
       * 'Lasker Trap' renders as 'Bẫy Lasker' — and a search for the untranslated
       * content name against a Vietnamese-only haystack finds nothing). Past the limit
       * the index renders as collapsed family buttons (`CatalogueList.tsx`), which is
       * the intended behaviour for the unfiltered view — so this walk narrows by the
       * entry's own ECO code, which is not translated and so matches on every locale
       * this test might run against. Each of this repository's ECO codes matches at
       * most a few dozen taught entries (`sicilian-defense-*` tops out at ten),
       * comfortably under the limit, and the href-based locator below still finds the
       * one card that is this entry's.
       */
      await page.goto(`${cataloguePath}?q=${encodeURIComponent(entry.eco)}`)
      /*
       * Waited for by the result count rather than by the heading. The catalogue payload
       * is a separate request, and the heading is on the page before any of it has
       * arrived — so without this the locator below races the fetch and reports a slow
       * server as a missing entry. The count has to be non-zero for the same reason: an
       * empty list is a payload that did not arrive, not a catalogue with nothing in it.
       */
      await expect(page.getByRole('main').getByRole('status')).toContainText(/Đang hiện [1-9]/)

      const card = page
        .getByRole('main')
        .locator(`a[href$="/vi/${routeSegments.catalogue}/${entry.id}"]`)
      await expect(card).toHaveCount(1)
      await card.click()

      await atGambit(page, entry.id, [])
      await expect(page.getByRole('navigation', { name: vi.learn.navigation })).toBeVisible()
      /*
       * Issue #54 marked the ply that produced the position; #70 gave the root one. The root
       * is the position after the defining line, whose last ply the page now walks through,
       * so the two squares of that ply are tinted here exactly as they are everywhere else
       * (2026-09-18: two tinted squares, no ring on either).
       */
      await expect(
        page.locator(
          '.learning-surface__board .board__square--from, .learning-surface__board .board__square--to',
        ),
      ).toHaveCount(2)

      const entryPath = `${cataloguePath}/${entry.id}`

      for (const leaf of entry.leaves) {
        await page.goto(entryPath)
        await expect(page.getByRole('navigation', { name: vi.learn.navigation })).toBeVisible()

        /*
         * Walk down by clicking, choosing each control by the address it carries rather
         * than by its text: a link's `href` is the same `?line=` contract the URL
         * round-trips on, so this cannot drift from the encoding the site publishes.
         *
         * Which control it is follows from the node, which is the asymmetry the whole
         * model rests on (docs/CONTEXT.md, *The central asymmetry*). An opponent's reply
         * is one of several branches and is a `ChoiceLink`; the gambit's own prescribed
         * move is not a choice at all and is reached with the navigator's *next*. A
         * learner node with more than one child is the deliberate exception — a real
         * choice of plans — and renders `PlanChoices`, which are `ChoiceLink`s too.
         */
        for (const [index] of leaf.entries()) {
          const parent = nodeAt(entry.tree, leaf.slice(0, index))
          const isChoice = parent.kind === 'opponent' || (parent.children?.length ?? 0) > 1
          const target = lineSearch(leaf.slice(0, index + 1))
          const control = isChoice ? '.choice-link' : '.move-navigator__control--next'

          await page.locator(`${control}[href$="${target}"]`).click()
          await atGambit(page, entry.id, leaf.slice(0, index + 1))

          /*
           * Issue #54, on published content rather than on a fixture. The highlight was
           * complete and unreachable for four waves precisely because nothing asserted it
           * anywhere a visitor actually goes, so every step of every taught line is asked
           * for the two tinted squares — the square the ply left and the square it reached.
           */
          await expect(
            page.locator(
              '.learning-surface__board .board__square--from, .learning-surface__board .board__square--to',
            ),
          ).toHaveCount(2)
        }

        const outcome = nodeAt(entry.tree, leaf).outcome
        expect(outcome, `no outcome at ${leaf.join(' ')}`).toBeDefined()
        if (outcome === undefined) return

        // The leaf shows its own outcome card, and it really is a leaf: nothing to click on.
        await expect(page.locator(CARDS[outcome.kind])).toBeVisible()
        await expect(page.locator('.choice-link')).toHaveCount(0)

        if (outcome.kind === 'mate') {
          // The proof is named on the page, so the claim can be checked in the repository
          // rather than believed (ADR-0005).
          await expect(page.locator(CARDS.mate)).toContainText(outcome.basis.certificate)
        }
      }
    })
  }
})
