// @vitest-environment node
import { Chess } from 'chess.js'
import { describe, expect, it } from 'vitest'
import { matingMove, searchMate } from './search.ts'

/**
 * The bounded search, and above all the value it is allowed to return when it does not know.
 *
 * ADR-0005 names fail-soft as the single most likely bug in the project: a search that runs
 * out of budget saying "no mate found", a caller reading that as "not refuted", and a mate
 * claim generated for a position that is not mate. The hundred-node test below is the one
 * that would catch it, and it is a required test rather than a code-review note.
 */

const fenAfter = (line: readonly string[]): string => {
  const chess = new Chess()
  for (const ply of line) chess.move(ply)
  return chess.fen()
}

/** The real trap positions, verified move by move rather than taken from a published line. */
const LEGAL = fenAfter([
  'e4',
  'e5',
  'Nf3',
  'Nc6',
  'Bc4',
  'd6',
  'Nc3',
  'Bg4',
  'h3',
  'Bh5',
  'Nxe5',
  'Bxd1',
])
const BLACKBURNE = fenAfter([
  'e4',
  'e5',
  'Nf3',
  'Nc6',
  'Bc4',
  'Nd4',
  'Nxe5',
  'Qg5',
  'Nxf7',
  'Qxg2',
  'Rf1',
  'Qxe4+',
  'Be2',
])
/** The same line where White plays the move that holds, which the published version omits. */
const BLACKBURNE_SAVED = fenAfter([
  'e4',
  'e5',
  'Nf3',
  'Nc6',
  'Bc4',
  'Nd4',
  'Nxe5',
  'Qg5',
  'Nxf7',
  'Qxg2',
  'Rf1',
  'Qxe4+',
  'Qe2',
])
/** 1.e3 a5 2.Qh5 Ra6 … 10.Qe6 — the shortest known stalemate. */
const STALEMATE_IN_ONE = fenAfter([
  'e3',
  'a5',
  'Qh5',
  'Ra6',
  'Qxa5',
  'h5',
  'Qxc7',
  'Rah6',
  'h4',
  'f6',
  'Qxd7+',
  'Kf7',
  'Qxb7',
  'Qd3',
  'Qxb8',
  'Qh7',
  'Qxc8',
  'Kg6',
])

describe('what the search proves', () => {
  it("finds Légal's mate in two and reports the minimum, not the bound", () => {
    expect(searchMate(LEGAL, { withinMoves: 2 })).toEqual({ kind: 'mate', inMoves: 2 })
    // Asked for more room than it needs, it still answers 2: iterative deepening returns the
    // first depth that succeeds, which is what makes the result usable as a minimality check.
    expect(searchMate(LEGAL, { withinMoves: 4 })).toEqual({ kind: 'mate', inMoves: 2 })
  })

  it('proves there is no faster mate, which is what minimality rests on', () => {
    expect(searchMate(LEGAL, { withinMoves: 1 })).toEqual({ kind: 'no-mate' })
  })

  it('finds the mate in one after the Blackburne Shilling blunder', () => {
    expect(searchMate(BLACKBURNE, { withinMoves: 1 })).toEqual({ kind: 'mate', inMoves: 1 })
  })

  it('finds no mate after 7.Qe2, the move the published trap line leaves out', () => {
    expect(searchMate(BLACKBURNE_SAVED, { withinMoves: 3 })).toEqual({ kind: 'no-mate' })
  })

  it('never reads a stalemate as a mate', () => {
    // White can stalemate here in one. A search that scored "opponent has no legal move" as
    // success would call that a mate; this one calls it a draw and keeps looking.
    expect(searchMate(STALEMATE_IN_ONE, { withinMoves: 1 })).toEqual({ kind: 'no-mate' })
    expect(searchMate(STALEMATE_IN_ONE, { withinMoves: 2 })).toEqual({ kind: 'no-mate' })
  })
})

describe('what the search refuses to claim', () => {
  /**
   * The required test (ADR-0005, "Failing safe"; issue #5, AC 5).
   *
   * A hundred nodes is far too few to settle a mate in two. The only sound answer is
   * `unknown`. The assertion that matters is the second one: `no-mate` here would mean the
   * minimality check silently reporting "nothing shorter exists" because it ran out of
   * budget, and a false mate claim generated by the mechanism built to prevent one.
   */
  it('returns unknown, and specifically not no-mate, when the cap truncates a known mate in two', () => {
    const capped = searchMate(LEGAL, { withinMoves: 2, nodeCap: 100 })

    expect(capped).toEqual({ kind: 'unknown' })
    expect(capped.kind).not.toBe('no-mate')
    expect(capped.kind).not.toBe('mate')
  })

  it('answers the same question correctly once the budget is enough', () => {
    expect(searchMate(LEGAL, { withinMoves: 2, nodeCap: 100 })).toEqual({ kind: 'unknown' })
    expect(searchMate(LEGAL, { withinMoves: 2, nodeCap: 100_000 })).toEqual({
      kind: 'mate',
      inMoves: 2,
    })
  })

  it('poisons upward: one truncated branch makes the whole answer unknown', () => {
    // Small enough to settle depth 1 (no mate in one) and be cut off inside depth 2. The
    // deeper pass is not reported as "no mate at that depth" just because it was truncated.
    for (const cap of [50, 100, 250, 500]) {
      expect(searchMate(LEGAL, { withinMoves: 2, nodeCap: cap }).kind).not.toBe('no-mate')
    }
  })

  it('refuses the Fishing Pole mate in four at a cap it cannot settle it under', () => {
    // 1.e4 e5 2.Nf3 Nc6 3.Bb5 Nf6 4.O-O Ng4 5.h3 h5 6.hxg4 hxg4 7.Ne1. Measured here: still
    // `unknown` after 3,000,000 nodes and 159 seconds, so the tooling refuses the claim and
    // the leaf goes back to the author. That is the design working, not a gap in it — the
    // cap stays where it is until the claim passes honestly.
    const fishingPole = fenAfter([
      'e4',
      'e5',
      'Nf3',
      'Nc6',
      'Bb5',
      'Nf6',
      'O-O',
      'Ng4',
      'h3',
      'h5',
      'hxg4',
      'hxg4',
      'Ne1',
    ])

    expect(searchMate(fishingPole, { withinMoves: 4, nodeCap: 20_000 })).toEqual({
      kind: 'unknown',
    })
  })
})

describe('the move the generator records', () => {
  it('is a move that actually forces the mate', () => {
    const chosen = matingMove(LEGAL, 2, 100_000)

    expect(chosen?.san).toBe('Bxf7+')
  })

  it('is nothing at all when the budget cannot settle it', () => {
    expect(matingMove(LEGAL, 2, 10)).toBeUndefined()
  })
})
